### ISSUE TITLE
Bitfinex :: IOT, BCH, OMG, XMR, ...

### ISSUE THREAD

**Issue by netcoding** [askmike/gekko#1011]
* **failed crypto assets**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** 

* **Expected result**
more crypto assets

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by decoye** [comment]
ill work on that during the day

**Comment by kalzso** [comment]
the same would be nice for Kraken. For example I would like to trade in EUR / XRP (Ripple), Kraken allows it, but I cannot choose the option in the bot.

**Comment by decoye** [comment]
Hey.
Currently at work. Im consideribg kraken updates as well.
-------- Ursprüngliche Nachricht --------Von: kalzso <notifications@github.com> Datum: 20.08.17  20:35  (GMT+01:00) An: askmike/gekko <gekko@noreply.github.com> Cc: decoye <schindler.andreas@gmail.com>, Comment <comment@noreply.github.com> Betreff: Re: [askmike/gekko] Bitfinex :: IOT, BCH, OMG, XMR, ... (#1011) 
the same would be nice for Kraken. For example I would like to trade in EUR / XRP (Ripple), Kraken allows it, but I cannot choose the option in the bot.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/askmike/gekko","title":"askmike/gekko","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/askmike/gekko"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kalzso in #1011: the same would be nice for Kraken. For example I would like to trade in EUR / XRP (Ripple), Kraken allows it, but I cannot choose the option in the bot."}],"action":{"name":"View Issue","url":"https://github.com/askmike/gekko/issues/1011#issuecomment-323603118"}}}

**Comment by decoye** [comment]
Uploaded a patch to my fork.
Gekko patch 2. Wait for mike to implement it.

**Comment by askmike** [comment]
This has been fixed by @decoye (see #1015).

**Comment by netcoding** [comment]
@decoye 
thx for you patch, but this won't work.

`ERROR: Gekko does not support this currency/assets pair at Bitfinex`

i think the problem is this (IOTA vs. IOT).
`{ pair: ['USD', 'IOTA'], minimalOrder: { amount: 0.01, unit: 'asset' } }, `

after change this to "IOT" and then this will work but with a other problem.

`2017-08-21 17:05:55 (INFO):	Setting up:
2017-08-21 17:05:55 (INFO):		 Paper Trader
2017-08-21 17:05:55 (INFO):		 Paper trader that simulates fake trades.
/gekko/plugins/paperTrader/paperTrader.js:14
  this.fee = 1 - (calcConfig['fee' + calcConfig.feeUsing.charAt(0).toUpperCase() + calcConfig.feeUsing.slice(1)] + calcConfig.slippage) / 100;
                                                        ^`

`TypeError: Cannot read property 'charAt' of undefined
    at new PaperTrader (/gekko/plugins/paperTrader/paperTrader.js:14:57)
    at load (/gekko/core/pluginUtil.js:100:22)
    at /gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/gekko/node_modules/async/dist/async.js:1015:17)
    at /gekko/node_modules/async/dist/async.js:988:16
    at /gekko/node_modules/async/dist/async.js:1158:13
    at load (/gekko/core/pluginUtil.js:68:14)
    at /gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/gekko/node_modules/async/dist/async.js:1015:17)
    at /gekko/node_modules/async/dist/async.js:988:16
    at /gekko/node_modules/async/dist/async.js:1158:13
    at load (/gekko/core/pluginUtil.js:68:14)
    at /gekko/node_modules/async/dist/async.js:1156:9
    at replenish (
/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (
/gekko/node_modules/async/dist/async.js:1015:17)
    at /gekko/node_modules/async/dist/async.js:988:16
    at /gekko/node_modules/async/dist/async.js:1158:13
    at load (/gekko/core/pluginUtil.js:68:14)
    at /gekko/node_modules/async/dist/async.js:1156:9
    at replenish (
/gekko/node_modules/async/dist/async.js:1030:17)`

**Comment by askmike** [comment]
@netcoding It seems like you are running Gekko over the CLI. In that case please update your config so that is has these 2 properties: https://github.com/askmike/gekko/blob/stable/sample-config.js#L203-L204

**Comment by netcoding** [comment]
Ohh yes, you are faster as i am ;-)
I've also see this and added this in my config.
'feeMaker: 0.15,
  feeTaker: 0.25,
  feeUsing: 'maker','

But the the failure in the string description "IOT != IOTA" will keep.

**Comment by decoye** [comment]
Hey hey, 

im not a user of bitfinex, so i could not test it.
just went to the website and tried to figure out how they name their asset pairs.
So IOTA is infact IOT?

**Comment by netcoding** [comment]
@decoye 
Yes, IOTA is infact IOT.
See here, https://bitfinex.readme.io/v2/docs/ws-general .

Anyway, thanks so much to @askmike & all other submiters for this fantastic tool. i love it.
