### ISSUE TITLE
installation problems.

### ISSUE THREAD

**Issue by jonboy510** [askmike/gekko#1019]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did) instalation command 
npm install --only=production does not work. but npm install command does. also MACD does not show buy and sell in back test over any length of time. plus can not use MACD to trade.

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
What are the errors?

**Comment by pelletencate** [comment]
I agree with @askmike, your description is not very clear, and it seems you're reporting 3 separate bugs in one report, with a title that's not very indicative about what exactly your problem is.

As for npm: I'm inclined to say "who cares". (I use yarn because it's so much faster)

As for the MACD: I might have run into something that might help you. Depending on the pair you're trying to trade, try drastically lowering the thresholds. I remember on Poloniex, the defaults didn't do anything for me, and I had to change it from 0.025 to 0.0001 (and -0.0001) order for the MACD signals to be picked up.

Try setting it to 0 first, and then gradually increase it in small steps to figure out the right order of magnitude for your pair.

**Comment by jonboy510** [comment]
thanks for that tip dude. but i cant even get gekko to load now. looks like
i have to uninstall it and reinstall every time i want to use it.

**Comment by jonboy510** [comment]
after a shutdown. i cant get gekko to run or load? this is the error i am
getting now. im not a programmer. just a user. it worked before i shut my
computer down.

**Comment by askmike** [comment]
@jonboy510 if you have an error we can only help you if you tell us what the error is..

**Comment by jonboy510** [comment]
![ice_screenshot_20170822-115943](https://user-images.githubusercontent.com/31219972/29562976-863e083a-8733-11e7-9beb-978da026fbe2.png)

**Comment by askmike** [comment]
what is the output fo the following two commands?

    node -v
    npm -v

**Comment by jonboy510** [comment]
![ice_screenshot_20170822-121845](https://user-images.githubusercontent.com/31219972/29563107-127e9530-8734-11e7-92a5-484b3607c3f8.png)

**Comment by jonboy510** [comment]
![ice_screenshot_20170822-121954](https://user-images.githubusercontent.com/31219972/29563151-465add50-8734-11e7-96fa-aa962874e513.png)

**Comment by jonboy510** [comment]
i am going to uninstall and reinstall gekko. ive found that this works. but its a pain in the ass.

**Comment by askmike** [comment]
I have never seen this before. To give some context: Gekko is a tool that is written in nodejs, so you can only use Gekko once your nodejs is working probably (which is rarely a problem).

It seems like node does not run on windows XP or vista (see https://github.com/nodejs/node/issues/3804), so that automatically means that Gekko is not supported on these operating systems. If you are running one of these you could run gekko in a (linux based) virtual machine.


If that is not your case, could you maybe look at the following similar issues to see if they apply to you?

- https://github.com/nodejs/node/issues/8234
- https://github.com/nodejs/node/issues/2979
- https://github.com/nodejs/node/issues/11959

**Comment by jonboy510** [comment]
im on windows 7 pro

**Comment by jonboy510** [comment]
tried that dude. sadly no luck? will not trade on macd or show buy and
sells in back testing?

**Comment by jonboy510** [comment]
but it is working after a reinstall.

**Comment by askmike** [comment]
great, so to sum up: the installation issue you had is an issue with nodejs (an external project, has nothing to do with Gekko). If the issue persists please post it here: https://github.com/nodejs/node/issues

**Comment by jonboy510** [comment]
so is gekko stable on windows 10? you said xp and vista where a problem?

**Comment by askmike** [comment]
It should be yes, I don't use windows but a lot of people are using Gekko on windows 10 without to many problems (some advanced use cases like TAlib support and using other databases might be hard on windows).

However the errors you reported have likely to do with your specific windows setup, and not windows 10 in general.

**Comment by askmike** [comment]
I also put an installation video of Gekko on youtube, the OS in that video is also windows 10:

https://www.youtube.com/watch?v=R68IwVujju8

**Comment by jonboy510** [comment]
when i try to restart gekko after a shutdown. i get this error. nothing to
do with the nodes tho?
