### ISSUE TITLE
How to set candle size in second?

### ISSUE THREAD

**Issue by hamzauzumcu** [askmike/gekko#1022]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[X] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Hi there,
i want to set candle size in second. Is it possible?

**Comment by askmike** [comment]
Unfortunately this is not possible! Gekko aggregates everything into minutely candles and stores those on disk. This is a design decision.

If you need more precision you want a few things that Gekko does not offer:

- You probably want to have a clear picture of the orderbook, this is out of scope for gekko (the OB is only used for order execution, not for strategies).
- You probably want to get market data as fast as possible, gekko has a slow polling fetch model (it polls the exchange for market data every 20 sec, you probably want to be subscribed to a websocket if you care about second precision).
- You don't want to deal with candles ay all anymore (abstraction breaks down on small timescales), you want to deal with trades. Gekko doesn't deal with trades (only up the point they are aggregated into candles).
- If you are looking at below the minute mark you are looking at micro market structures, TA is (imo) not the best tool. for studying those. TA (and Gekko) is designed for trends / momentum that develop over time.
- Speed becomes essential and you want to act as fast as possible (gekko is pretty slow because of all the ways data gets aggregated), you probably want to be below the 1ms mark and that's not what I had in mind when designing Gekko.
