### ISSUE TITLE
Add information to notification plugins

### ISSUE THREAD

**Issue by developdaly** [askmike/gekko#1028]
Provide more information via notification plugins when gekko is live trading.

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

_This is a placeholder for more specific criteria around what information should be added to notifications._

**Comment by gweedobtc** [comment]
I believe the plugin system of gekko kinda needs to be reworked. I think wordpress has a great system for plugins. It allows plugins to be coded over core as well as other plugins. Right now I tried to create a stop loss plugin and found it challenging. So I just left it in my strat.

**Comment by askmike** [comment]
@gweedobtc the plugin system is a lower level systems that allows "pieces of code" to subscribe to events flowing through Gekko. This system is used heavily internally. Most "core functionality" is simply a plugin subscribed to a stream of events, examples are: the trader, the paper trader, the tradingAdvisor (=stratrunner), performanceAnalyzer, etc. Stoploss implementations belong in userland (=your strategy).

Here are the docs: https://gekko.wizb.it/docs/extending/add_a_plugin.html

-----

This issue came out of a small discussion on discord about the possibility of enbaling plugins in when starting a live gekko in the UI. While this is not hard I have been reluctant to put a focus on plugins since they plugin system is so outdated.
