### ISSUE TITLE
Gekko through apache reverse proxy

### ISSUE THREAD

**Issue by solipsist01** [askmike/gekko#1049]
I use a reverse proxy to access all my webbased applications remotely.

Gekko however, does infact load the website, but instantly keeps giving me the message Disconnected.
These are my Apache directives.

ServerName gekko.omfg.com
<Location "/">
AuthType Basic
AuthUserFile "/etc/password/htpass.z0mg"
AuthName "This is a private system. Please authenticate."
require valid-user
</Location>

ProxyPass / http://192.168.2.185:3000/
ProxyPassReverse / http://192.168.2.185:3000/

ProxyPreserveHost on
ProxyVia on

**Comment by askmike** [comment]
Could you provide more information on the exact `Disconnected.` message you are getting?

**Comment by solipsist01** [comment]
it's a 'popup'
the same one when i stop the gekko process.

Disconnected

Something happened to either Gekko or the connection. Please check the terminal where Gekko is running or your network connection.

**Comment by askmike** [comment]
That means gekko is unable to setup a websocket connection between the
frontend and the server (Apache). Can you configure it to tunnel websockets?

**Comment by solipsist01** [comment]
what is the URL to the websocket ?

**Comment by askmike** [comment]
the same as the API, which means whatever you configured in your UIConfig as the frontend :)

**Comment by solipsist01** [comment]
usually a websocket URL looks like this:
  ProxyPass /api/websocket ws://localhost:8123/api/websocket
  ProxyPassReverse /api/websocket ws://localhost:8123/api/websocket

however, the 'api' doesn't have a 'host' directive. so that's plain ws://localhost:3000 (which doesn't work)

What am i missing here ?

**Comment by askmike** [comment]
> usually a websocket URL looks like this

So the websocket URL looks like:

    wss://[UIConfig.ui.host]:[UIConfig.ui.port][[UIConfig.ui.path]

(or ws instead of wss if you set ssl to false in the UIConfig).

Example:

if you UIConfig has this as the UI object:

    ui: {
        ssl: false,
        host: 'myserver.com',
        port: 3117,
        path: '/whatever'
    },

The websocket URL would be: `ws://myserver.com:3117/whatever`

> however, the 'api' doesn't have a 'host' directive. so that's plain ws://localhost:3000 (which doesn't work)

I am sorry, what does this mean?

**Comment by sgnac** [comment]
I had the same issue and this post with this stackoverflow entry gave me the solution : https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel

Just putting the websocket url in the proxy pass directive was not enough, since as explained in the stackoverflow post : 

> As of Socket.IO 1.0 (May 2014), all connections begin with an HTTP polling request (more info here). That means that in addition to forwarding WebSocket traffic, you need to forward any transport=polling HTTP requests.

You have to use the apache rewrite engine.
My apache configuration : 
```
	ProxyPass /geko/ http://127.0.0.1:3000/
	ProxyPassReverse /geko/ http://127.0.0.1:3000/
	ProxyPreserveHost on
	ProxyVia on
	
	RewriteEngine On
	RewriteCond %{QUERY_STRING} transport=polling [NC]
	RewriteRule /geko/api/(.*)	http://localhost:3000/api/$1 [P]

	RewriteCond %{HTTP:Upgrade} websocket [NC]
	RewriteRule /geko/api/(.*)	ws://localhost:3000/api/$1 [P]
```

And my UIconfig.js  : 
```
 const CONFIG = {
  headless: true,
  api: {
    host: '127.0.0.1',
    port: 3000,
  },
  ui: {
    ssl: false,
    host: 'yourHostname',
    port: 80,
    path: '/geko/'
  },
  adapter: 'sqlite'
 }
```


Nb : To serve the page from another context root than / (/geko/ in my case), I had to edit gekko/web/vue/index.html to add my context root in every URL.
I still have some minors issues : 
```
GET /assets/gekko.jpg 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found) select-arrow.png
```
But it's working! 

Thanks a lot everyone!

**Comment by askmike** [comment]
Awesome! I myself never use apache so unfortunately couldn't be of much help.

**Comment by blast1987** [comment]
For me it's not working, i am using sgnac config but what i get is:

5/gekko/#/home:1 WebSocket connection to 'wss://myhost:3000/api/' failed: WebSocket is closed before the connection is established.

Gekko connects to the UI but it seem that from external host gekko still tries to go on port 3000 for the APIs...
 to make this work it has to go on the same port  (and parth+/api) i connect from external host, in my case: https://myhost:443/gekko/api

in my config, port 443 and 80 are open, but port 3000 is closed
here's the completed chrome console log connecting to my gekko using https://myhost:443/gekko

> WebSocket connection to 'wss://myhost:3000/api/' failed: WebSocket is closed before the connection is established.
build.js:16 OPTIONS https://myhost:3000/api/imports net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/gekkos net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/gekkos net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/apiKeys net::ERR_CONNECTION_TIMED_OUT
build.js:16 OPTIONS https://myhost:3000/api/exchanges net::ERR_CONNECTION_TIMED_OUT


How can i solve this? Is there a way to tell gekko to connect to the current port instead of the 3000?

**Comment by BannanaDJoe** [comment]
Hello I guys looks like i found a workaorund for this issue with apache on port 80 and gekko

here some informations : 
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2018-04-25T11:38:24
npm -v
5.6.0
node -v
v8.11.2
Gekko Stable at this moment. 05/23/2018

command : a2enmod proxy proxy_http proxy_wstunnel rewrite

/*/gekko/web/vue/UIconfig.js
const CONFIG = {
  headless: true,
  api: {
    host: '127.0.0.1',
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: false,
    host: 'FQDN',
    port: 80,
    path: '/geko/'
  },
  adapter: 'sqlite'
}
if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

/etc/apache2/sites-available/yourconfig.config

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ErrorLog ${APACHE_LOG_DIR}/error.log
        ServerName www.yourservername.com
        ProxyPass /geko/ http://127.0.0.1:3000/
        ProxyPassReverse /geko/ http://127.0.0.1:3000/
        ProxyPreserveHost on
        ProxyVia on
        RewriteEngine On
        RewriteCond %{QUERY_STRING} transport=polling [NC]
        RewriteRule /(.*)       http://localhost:3000/api/$1 [P]
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteRule /(.*)       ws://localhost:3000/api/$1 [P]
</VirtualHost>

I hope that can help :) enjoy it guys

**Comment by ettorix** [comment]
Thank you for the solution !
Just a correction :
I use : 
```
RewriteRule /(.*) http://localhost:3000/api/$1 [P]
```
instead of : 
```
RewriteRule /(.) http://localhost:3000/api/$1 [P]
```

**Comment by blastbeng** [comment]
For me it is not working, my config is as follow:


apache2 conf:
```
<Location/gekko/> 
		Order allow,deny 
		Allow from all
		ProxyPass http://192.168.1.180:3000/ flushpackets=on
                ProxyPassReverse http://192.168.1.180:3000/
                RewriteCond %{QUERY_STRING} transport=polling [NC] 
		RewriteRule /(.*) http://192.168.1.180:3000/api/$1 [P]
		RewriteCond %{HTTP:Upgrade} websocket [NC] 
		RewriteRule /(.*) ws://192.168.1.180:3000/api/$1 [P]
</Location>
<Location/gekko/api>
                Order allow,deny
                Allow from all
                ProxyPass ws://192.168.1.180:3000/api 
		ProxyPassReverse ws://192.168.1.180:3000/api
</Location>
```


UIConfig.js:
```
const CONFIG = {
  headless: true,
  api: {
	host: '192.168.1.180',
	port: 3000,
	timeout: 120000 // 2 minutes},
  ui: {
	ssl: false,
	host: '192.168.1.180',
	port: 3000,
	path: '/'
  },
  adapter: 'sqlite'
} 
```

I keep getting in chrome console:

> WebSocket connection to 'wss://192.168.1.180:3000//api' failed: WebSocket is closed before the connection is established.

My doc root is not /gekko/ it is just a location on my web server, so i proxy single locations /gekko/ to ip:3000 and /gekko/api to ip:3000/api

Looks like the apache2.4 mod_rewrite or the mod_proxy is not working as it should...

Is it correct to put these rewrites inside /gekko/ location?

What am i doing wrong?

Thanks



EDIT:

SOLVED. the problem was in UIConfig.js, now it is working fine with:

```
const CONFIG = {
  headless: true,
  api: {
	host: '192.168.1.180',
	port: 3000,
	timeout: 120000 // 2 minutes},
  ui: {
	ssl: false,
	host: 'myexternalhost',
	port: 80,
	path: '/gekko/'
  },
  adapter: 'sqlite'
} 
```
