### ISSUE TITLE
[request] Adding more Parameters to DEMA

### ISSUE THREAD

**Issue by jeeyer** [askmike/gekko#1066]
Hi!

I was wondering if adding more parameters for DEMA is possible (see also #146). I noticed @askmike replied to copy the DEMA and add it but I'm staring at the code for hours and can't seem to manage it. 

I would like to add: 6 short EMA's and 6 Long EMA's. It would buy when all of the short-term EMAs cross above all of the long-term EMAs, and sell when the short term EMAs cross below the long-term EMAs. 

Let me know what your thoughts are :)

**Comment by askmike** [comment]
Hey!

> #146: on 13 Jan 2014

Woah you did some digging to find that haha!

----

Note that the D in DEMA stands for double (meaning 2 EMAs) - while you want 6, so you are not really talking about DEMA anymore.

If you want to create a strategy that uses multiple EMA indicators, that's actually not too hard with gekko. If we draw inspiration from #1060 we can make a new strategy like this: https://gist.github.com/askmike/f6d0b12c1ef9a9989c717fc4e12b7620

It works in 2 steps:

1. register all EMA indicators you want with Gekko
2. check the results.

As for the results, when you say:

>  It would buy when all of the short-term EMAs cross above all of the long-term EMAs

This is the same as saying "when the lowest short EMA crosses above the highest long EMA" (and vice versa for sell).

I am not sure in what market you want to run this, but in my initial testing this did not perform very well (though that's all based on the numbers I plugged in the EMAs which I did randomly):

<img width="1438" alt="screen shot 2017-09-01 at 22 41 29" src="https://user-images.githubusercontent.com/969743/29988746-bc6bfb0c-8f66-11e7-87e4-05c7ea33d3f1.png">

(That's over 1hour USD/ETH gdax data).

-------

you can uncomment the console.log lines if you want to see all the values each tick :)

**Comment by askmike** [comment]
Note: There was a bug in the code, I updated the gist.

**Comment by jeeyer** [comment]
Hey Mike,

> Woah you did some digging to find that haha! 

Haha ,well I know it's appreciated before opening a new thread you do some digging!! ;).

Thanks for providing the code! This is exactly what I was looking for. So for the backtest you just used the random numbers stated in the multiple-ema.js?

I want to try the code myself, with some numbers I think should work well, but now getting an error while starting  Gekko with node.js. I used 
`node gekko --ui` to start it again after I just closed the window in Chrome.

```
Error: Cannot find module '/Users/folderblabla/gekko'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```
Cheers.
J.

**Comment by askmike** [comment]
>  So for the backtest you just used the random numbers stated in the multiple-ema.js?

Yes, you can change them into whatever you like :)

> I want to try the code myself, with some numbers I think should work well, but now getting an error while starting Gekko with node.js.

When you want to run Gekko you need to first navigate on the commandline to the folder where you downloaded Gekko. How to do this very much depends on your OS. So to sum everything up:

- Download the script I posted earlier.
- Open your file browser (windows explorer on windows, finder on mac) and place the script into the gekko folder (wherever you stored it) into the strategies folder inside it.
- Open your terminal (called command line on windows) and browse into the gekko folder you downloaded. For example: on most linux systems and mac you can `cd` fro this, if you downloaded Gekko to your downloads it should be something similar to `cd ~/gekko`. Only after this you can type `node gekko --ui`.

I am closing this since your original issue (strat with 10 EMAs) is solved, if you are having more problems starting Gekko feel free to keep commenting :)

**Comment by jeeyer** [comment]
Hi Mike,

Thanks for the follow-up.  I'm running on mac OSX. 

I changed the code with the Guppy Multiple Moving Average indicators.
For short its: 3, 5, 8, 10, 12.
For long its: 30, 35, 40, 45, 50.

Results are better; but not optimal like you said. 

But I think it's a good basis for a trend following bot. Needs more tweaking, I've read adding a MACD + StocRSI is one of the best trend following strategies out there...

Visualisation of what a GMMA (Guppy Multiple Moving Average) looks like: https://monosnap.com/file/Jm77EjwIjODOOMwTghHu1Di1JjlLXe

You can clearly see if Red (long term traders) is beneath Blue (short term traders) it's bullish, and vice versa. Cross overs are a signal for trend changes, and the more the lines separate the more steady the trend (and vice versa).

What do you think?

**Comment by askmike** [comment]
> Visualisation of what a GMMA (Guppy Multiple Moving Average) looks like: https://monosnap.com/file/Jm77EjwIjODOOMwTghHu1Di1JjlLXe

By the way: we are working on an update for Gekko that plots the indicator lines on the graph! See #793 for details!

-----

> You can clearly see if Red (long term traders) is beneath Blue (short term traders) it's bullish, and vice versa. Cross overs are a signal for trend changes, and the more the lines separate the more steady the trend (and vice versa).
> What do you think?

I am not an expert in applying indicators in markets, which is why Gekko is not very biased (I am actualy pretty bad haha). But if you want my opinion: It looks like this specific graph really gets the best out of this specific strategy, though I am not sure if this really behaves that much different than a DEMA or MACD indicator. This is just what my instinct tells me, haven't really tested it at all.

> But I think it's a good basis for a trend following bot. Needs more tweaking, I've read adding a MACD + StocRSI is one of the best trend following strategies out there...

Go for it! Gekko supports both of these indicators (note that for StochRSI you need to install TAlib).

**Comment by jeeyer** [comment]
@askmike is there any documentation about combining indicators? I assume it would get quite difficult because you need to match the output of different indicators and then issue an advice?

**Comment by askmike** [comment]
>  I assume it would get quite difficult because you need to match the output of different indicators and then issue an advice?

Exactly! And because everyone has different opinions on how this should exactly work (if indicator X says buy but Y says sell, what do we do?) this logic goes in your own strategy. **The only purpose of the strategy is to look at indicator output & market data and decide when to trigger BUY and SELL.**

> is there any documentation about combining indicators?

All documentation regarding strategies (including how to add indicators and read the output) can be found here: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

**Comment by jeeyer** [comment]
I understand, you also need to bear in mind what to do when you got conflicting indicators!!

**Comment by askmike** [comment]
Have a look at the documentation, and if you think we can improve the documentation (around indicators for example) just let me know :)
