### ISSUE TITLE
Lingering questions...

### ISSUE THREAD

**Issue by score1more4me** [askmike/gekko#1126]
First - thank you very much for all your effort AskMike!  And thanks to all the other contributors as well!

I've been running the bot in paper trade mode, and backtesting for some time now.  I've decided to let it run in live trading mode, and it brought up a few questions.

1.  For live trading, do you need to start from an all cash or all crypto position?  Or can you have a mix of assets for the pair traded?

2.  What happens when you add to your position with Gekko running?  Will Gekko re-query eventually to see that either crypto or cash has been added?  Or do I need to restart?

3.  Is there a config file setting to log console output to a log file?  Or should I just pipe stdout to a file?

4.  It seems there is a connection to the candle persistence and live trading.  I'm using a TALib RSI that I rolled and the RSI is undefined until the 5th hour of live trading, but there is sufficient local data stored to calculate this.  I have a 4 hour persistence for market condition confirmation.

Thank you again!

**Comment by askmike** [comment]
> For live trading, do you need to start from an all cash or all crypto position? Or can you have a mix of assets for the pair traded?

You can have a mix, as soon as there is a specific signal Gekko will check if you have something to buy/sell and try to execute.

> What happens when you add to your position with Gekko running? Will Gekko re-query eventually to see that either crypto or cash has been added? Or do I need to restart?

The order execution will work fine, but the profit reporting will not. Since profit is calculated by comparing your start balance versus your current balance. If you are fine with doing this manually yourself it is not a problem.

> Is there a config file setting to log console output to a log file? Or should I just pipe stdout to a file?

There are two ways of running Gekko:

- if you use the UI: a log per gekko is stored inside the logs folder.
- if you use the commandline: you need to pipe stdout to a file! You can also use something like pm2.

> It seems there is a connection to the candle persistence and live trading. I'm using a TALib RSI that I rolled and the RSI is undefined until the 5th hour of live trading, but there is sufficient local data stored to calculate this. I have a 4 hour persistence for market condition confirmation.

Can you open a new issue with the logs (preferably debug logs)? Thanks!
