### ISSUE TITLE
Limit error retries

### ISSUE THREAD

**Issue by infohoard** [askmike/gekko#1232]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Run gekko for a few days on BitFinex with screen -dr

* **Expected result** (what you hoped would happen)
Retries on error for a few times before giving up on a particular invalid action

* **Actual result** (unexpected outcome)
Receive "Bitfinex returned an error, retrying..." messages continuously, possibly because it was constantly trying to perform an action that is no longer valid. And also, these error messages will accumulate in amount, growing larger and displaying them every few moments.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I'm not sure which action is causing the error, but I suspect it's due to race conditions, gekko attempting to do something but the action is no longer valid. In any case, there are no set limits on error retries, so if gekko attempt to perform the invalid action, it will get an error and then it will retry again and again, resulting in gekko retrying forever.

**Comment by zartrade** [comment]
I just noticed that a couple of hours ago with bitfinex also. Limit orders dont execute anymore but it worked fine since the 9th until 19th. It returns for me buy order failed to fill full order, cancelling and retrying and then it simply throws an error of buy amount less than minimum even though it never filled any partial order and the failed order amount is some random btc amount notwhere close to my full value to purchase.

**Comment by cmroche** [comment]
@askmike I've been giving some thought to this problem in general, related to other Kraken issues we've look at recently. This is what I think we could do

1) limit retries to 1 per api call, except buy/sell/cancel
2) add retries to a queue and have the queue processed with a delay in between (prevent api rate limits triggering further retries)

The only issue of course is that it would have to be implement per exchange, unless we change the exchange API to centralize higher level retry behaviour. Off the cuff I think this would imply returning promises from each API function instead of using callbacks, adding a new exchange function to check if a retry should be attempted on a particular result, have an exchange parameter to define the API retry rate.

Any thoughts?
