### ISSUE TITLE
Where Can I Block The Start of Gekko

### ISSUE THREAD

**Issue by Guceri** [askmike/gekko#1243]
I would like to have Gekko start based on clock time and the candleSize.  For example, if I am running 15 min candles, I want gekko to pull the system time, and then start at the next 15 min increment on an hourly clock.  For example, if I start gekko (node gekko --config config.js) at 12:07, I want it to start gekko at 12:15.

I don't need help with the code itself, but this is more of an architecture question....

Does anyone know where the correct place to put a timer would be?  My first thought was within the gekko.js file which is what runs first, but I thought I would ask just in case it would make more sense somewhere else.

**Comment by askmike** [comment]
This is not supported yet but will be in the future, the main problem is that you don't just want Gekko to start on `12:15`. But you want the earliest candle to be available to be from `12:15`, else Gekko will start on `12:15` but find candles from maybe `12:07`.

Because of that the most obvious place is here: https://github.com/askmike/gekko/blob/stable/core/budfox/tradeBatcher.js

Just filter out all trades before the time you want to start.
