### ISSUE TITLE
Unable to use data from other files, regarding two strategies

### ISSUE THREAD

**Issue by DeBelserArne** [askmike/gekko#1244]
* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I've integrated this script into gekko:
https://github.com/pushkarnagle/gekko-buyatsellat
And right now I'm trying to run it together with strategies/rsi.js

* **Expected result** (what you hoped would happen)
Not really expecting a result yet, but I'm encoutering some issues.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
First of all, I was able to import the buyatsellat.js script into RSI.js
Now I want to use some of the data in this script in the RSI.js script, but my lack of knowledge prohibits me from doing so.

I was wondering if anyone could help/teach me how to use variables, or cont's or other things from two scripts with each other?

Kind Regards!

**Comment by askmike** [comment]
> I was wondering if anyone could help/teach me how to use variables, or cont's or other things from two scripts with each other?

As soon as I have more time I want to publish some videos on how to write strategies for Gekko. But note that it's basic javascript. Any online course that teaches javascript will help you :)

----

> And right now I'm trying to run it together with strategies/rsi.js

With Gekko you can only run 1 strategy (in 1 tradebot), so in order to do what you want you need to create a new strategy that uses both buysellat and the RSI strat (which simply registers an RSI indicator). Unfortunately how exactly to do this depends a lot on how you want the strategy to behave in certain situations (RSI signals UP but `buysellat` you cannot buy just yet, what should your strat do)?
