### ISSUE TITLE
exchange recommendation

### ISSUE THREAD

**Issue by Kirbylix** [askmike/gekko#1283]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ X] question about the decisions made in the repository

at the moment there are some problems with kraken.....
what other exchange provider would you advise me to use?

**Comment by askmike** [comment]
It depends on where you are based, but overall I'd say bitfinex and bitstamp are high on the list for their stability and high liquidity. But this is a very personal question, I would recommend browsing through a forum like bitcoinmarkets: https://www.reddit.com/r/BitcoinMarkets/ because everyone you ask about this will have a different opinion.
