### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by krebbi** [askmike/gekko#1290]
I had 3 market watchers and 2 paper traders running and suddenly this error occurred:

Error: SQLITE_BUSY: database is locked
RECEIVED ERROR IN GEKKO 157946277318988
Child process has died.

maybe this should be handled instead of exiting the process?

**Comment by askmike** [comment]
This cannot be handled, because the sqlite is unable to give data reqiured for Gekko to function. How do you think Gekko can handle this?

There are some workarounds to address this, as well as other databases you can use (postgresql or mongodb). I'll work on the docs for this.

**Comment by askmike** [comment]
If you want some possible workarounds on how to configure Gekko or sqlite let us know the following:

- what kind of system (computer, SSD, server, etc)?
- what markets where you watching?
- what OS?
- where you doing other things at the same time (backtest / import)?

But as for your:

> maybe this should be handled instead of exiting the process?

I don't think this is doable practically speaking, if gekko would try again later we'll just make the problem worse by pushing sqlite to a level where (it specifically said) it cannot go.

So please reopen if you want these workarounds instead.

**Comment by krebbi** [comment]
You could Handle that error. I don't know if it's doable in your code structure.
https://www.sqlite.org/c3ref/busy_handler.html

I'm running Gekko on 
VirtualBox with
Ubuntu 17.10
node v9.0.0
On Core i7 with 16GB Ram. 

I'm trying to reproduce this error.

**Comment by askmike** [comment]
The page you linked to describes ways of of juggling access to a sqlite database by configuring behaviour in case it is locked, but (one of) the big gotcha is:

> There can only be a single busy handler defined for each database connection

Which would mean restructuring a lot of the code: Right now each "gekko instance", like strat runner or market watcher, runs in in it's child process, they don't share any resources.

> VirtualBox

What is the underlying OS and (disk) hardware? I am quite sure you are seeing these errors more than anyone else because of heavy IO restrictions.

**Comment by krebbi** [comment]
The Host is OSX 10.13.1 with SSD

interestingly the error is not reproducible. so i keep this issue closed until it occurs the next time and will provide more debugable data. 

thx

**Comment by askmike** [comment]
Awesome, just to be sure: I do like to work on this issue. But the main problem with sqlite is that if you are doing multiple gekkos you are opening multiple sqlite handles. This is a very bad practise in sqlite. Doing this properly as hard because of architecture choices that were made, so my normal response is:

If you are seeing this because you are doing a lot of things at the same time use a different database (postgresql or mongodb).

**Comment by thegamecat** [comment]
Sqlite is horrible for this unfortunately - and I think it makes some sense to use postgres instead although that means more setup etc.

**Comment by krebbi** [comment]
I'm new to Nodejs, but what about having a pooling process handling this?

**Comment by askmike** [comment]
That would be the logical way to solve it, but it won't get very high priority from me anytime soon: the hardest part about this is the communication in a fast and cross platform way (depending on the situation backtesting is very IO heavy, not sure what the negative performance impact would be - but it won't be good).

**Comment by krebbi** [comment]
so would it be a big deal to change to postgress, like @thegamecat suggested? seems to be installable via npm as well: https://www.npmjs.com/package/pg
