### ISSUE TITLE
Automatic selection a trade coin

### ISSUE THREAD

**Issue by John1231983** [askmike/gekko#1291]
This is not a bug. This is a request function.

As we know, the bittrex has many coins. If we choose a good coin to trade, we will have a good profit. For that purpose, I think we can make a function to scan all coins in bittrex (or bitfinex...) within a certain time, then we have a list candidate coins that are in the uptrend. After that, we will automatically insert it in the configure file and do the auto trade. 

That is just idea. For implementation, I welcome anyone can implement it. Thanks all.

Update: the uptrend will be based on given strategy such as MACD.

**Comment by askmike** [comment]
Interesting idea!

> then we have a list candidate coins that are in the uptrend

This is the hard part, right now Gekko has 0 opinion on what is an uptrend. This is 100% up to the strategy, to determine (based on indicators, etc). So something like this would always be based on a "strategy" defined by the user.

As such I think it would be better to create an external tool that uses Gekko to quickly backtest all bittrex markets with a strategy and outputs the best "uptrend" candidates.

**Comment by askmike** [comment]
@thegamecat and @generalectric do you guys have opinions on how to do this?

**Comment by John1231983** [comment]
@askmike : You are right. The uptrend will be based on the strategy such as MACD. We just use it as initialization. After getting the candidate coin, we will do as normal trading with configure file

**Comment by Linuxrules** [comment]
if ma 1 > ma 2, using the indicators, then, we have an uptrend, else we have a downtrend. But, you know i spend most of my time actually selecting the right coin. The rest is just a stop-loss on support and a decent limit below resistance. I do concur that statistical tools such as ma are useful. But market price action is largely psychological. Takes WAVESBTC for example, support resistance trading on there makes me money that statistics cannot. Don't get me wrong, I am myself a statistician/mathematician. But, support/resistance trading is most profitable. Triarbitrage and other trading strategies are also useful, but these require thousands of trades within a few seconds and with trading fees, even when arbitrage is possible, it is not always profitable. I have been inquiring about implementing support/resistance trading strategy in javascript. But, i think that simple rules can allow automatic selection of coins. I usually use https://cryptoxscanner.com/binance/live on weekly timeframe to select coins that dumped most, then followed by a daily time frame to further the filtration, and 4-hourly and 15 minutes. This works great for a lot of coins, RVN, GRS and others worked great the past days. However, i realised that i purchased MOD. It met all criteria for a buy. But then, it was because Binance was unlisting some coins that the price dropped at such a speed. So, it would be great to select the coins automatically and search for news on the coins before final approval for trade in the bot. I am not a programmer but any help to code simple rules will be much appreciated.

**Comment by Linuxrules** [comment]
@askmike @John1231983 Any ideas?
