### ISSUE TITLE
Realtime update price for Bitfinex

### ISSUE THREAD

**Issue by John1231983** [askmike/gekko#1294]
I am using Bitfinex and development branch. I found that the processing of Gekko to get the price for Bitfinex has some delay as the attached file. The Gekko print the price that delays about 4~5 seconds than what I saw in office bitfinex website (and tradeview). What parameter should I change to see realtime price in bitfinex? It means the newest buy/sell price. Thanks

![untitled](https://user-images.githubusercontent.com/24875971/32483941-6dd17738-c3e1-11e7-9a9c-47dafef7f172.png)

**Comment by askmike** [comment]
Gekko is not designed for speed. Even if Gekko were to fetch all the trades straight away, your strategy would not do much since everything is aggregated into 1 minute candles (or probably even bigger, like hourly candles). And on top of that most indicators smooth out calculations over a set historical candles.

There are a lot of trading bots that are a lot more realtime (arbitrage bots, market making bots, etc), though they solve different problems than Gekko. Read this page for details about the scope of the project and limitations: https://gekko.wizb.it/docs/introduction/scope.html

**Comment by John1231983** [comment]
Thanks @askmike for reply. I found that bittrex can support realtime, while bitfinex is not. I guess that is API issue, not gekko.

**Comment by askmike** [comment]
They both have websocket APIs (realtime stream APIs), but Gekko doesn't use either.
