### ISSUE TITLE
Unable to stop a market watcher or Strat runner

### ISSUE THREAD

**Issue by djh82uk** [askmike/gekko#1306]
Is there any way?

**Comment by StevenHop** [comment]
Lurking for a while now: this is a question i can answer easily :)
The documentation states:

> Stopping Gekko :  In the command line hold ctrl + c.

It is on the bottom of this page: [https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html](url)

**Comment by djh82uk** [comment]
Yeah I can stop the script, but I just want to stop the Strat from running

**Comment by StevenHop** [comment]
Ah. I recognize the problem. If you have two Strats running you have to kill both. Somewhere i read this is on the roadmap. I have solved this for now by starting each gekko in a separate directory with their own port. C:\Gekko0=3000, C:\gekko1=3001, enz..  I sometimes copy the database between them or to a third directory to test strategys..

**Comment by tomand285** [comment]
Another way of doing this is saving the [PID](https://nodejs.org/api/process.html#process_process_pid) of each process into the database and then [KILL](https://nodejs.org/api/process.html#process_process_kill_pid_signal) the process you want to remove. You could make a html button to remove each processes. I recommend saving them in the DB because if the main program crashes, the child processes can still be controlled upon restart of the UI program. Of course you would have to check to see if the processes are still running every now and then and remove the ones that are not from the DB but that should be simple.

**Comment by askmike** [comment]
The UI is very basic for now. This will be properly supported in the next version. See #911 for details :)

**Comment by hilkoc** [comment]
I finally got this fixed. See my last comment on #2059.
