### ISSUE TITLE
Formatting and linting standards

### ISSUE THREAD

**Issue by levithomason** [askmike/gekko#1323]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository

**Action taken**

Perusing the codebase, learning how to write strategies.

**Expected result**

Formatting and linting tooling to keep the code consistent and catch common errors. Especially given the domain, I think users would feel much more comfortable with a very polished and solid product.  Also, having auto enforced format and lint standards reduces the chances of a small snafu going horribly wrong.

**Actual result**

No formatting and no linting standards.  Quickly spot checking some things I find some concerning code that would be captured and fixed by a linter.

Example, there is ample use of [implicitly declared variables](https://stackoverflow.com/questions/2485423/is-using-var-to-declare-variables-optional) which is of concern.  These variables will traverse parent scopes until they find a scope containing a declared variable.  This _could_ wreak havoc in a trading situation if a particular variable happen to bubble to a particular parent scope and change a setting.

There are also less harmful code such as unused `require()`d modules that, none the less, should not exist.

**Other information**

I propose the following:
1. consistent formatting using [prettier](https://github.com/prettier/prettier), which automatically reprints code
1. lint code using [eslint](https://github.com/eslint/eslint) to catch common mistakes and potential issues
1. Configure this to run automatically on pre-commit, ensuring all commits are consistently formatted and, more importantly, lint free.

***

Note, I'm able to provide pull requests for this if there is interest.

**Comment by cmroche** [comment]
@askmike Worth while to add a .jsbeautifyrc to the project?

I have to admit that I am uncertain on the official standard you are using since there are a few different approaches being used in the code.

Can you clarify which standard you prefer?

**Comment by levithomason** [comment]
Regarding code style standards, I prefer to use [prettier](https://github.com/prettier/prettier).  Prettier is a different animal, instead of throwing errors when there are style problems, or only fixing some style problems, it simply reprints the AST to a consistent standard.  This removes nearly all time wasted around bikeshedding, config, and fixing style issues.  Just print it and be done.  It also has gotten massive adoption.

As far as linting standards, [eslint](https://github.com/eslint/eslint) is the defacto tool in this space in terms of adoption.  I think starting with the `eslint:recommended` preset would be a great start.  It will prevent things like unused variables, bad treatment of scope, dangerous operators, etc.  Essentially, it would enforce many well-known and widespread best practices and avoid common pitfalls in JavaScript.

Overall, I prefer the least config and most benefit.  I also believe it is important to avoid debate on style (e.g. double vs single quotes) and instead focus on pragmatic issues.  I think code consistency and avoiding errors is a big win to the project and the developer.

**Comment by askmike** [comment]
A tiny bit of context:

This is a valid concern, the current codebase uses a lot of different styles that are not considered best practise anymore. Do keep in mind that some parts of the codebase are 4 years old and I basically only work on Gekko whenever I have an hour to spare. As for where to go from here (read on, but IMO) the quality of a codebase is about more than the styling of the current code, I highly value other things like the git history as well.

----

> Example, there is ample use of implicitly declared variables which is of concern. These variables will traverse parent scopes until they find a scope containing a declared variable. This could wreak havoc in a trading situation if a particular variable happen to bubble to a particular parent scope and change a setting.

These might be actual bugs, not related to a coding style or standard. Please point to them when you see them :)

-----

> Configure this to run automatically on pre-commit, ensuring all commits are consistently formatted and, more importantly, lint free.

In my understanding of git hooks, how do we get all people who send in PRs to adhire to this? A better place would be CI (travis) imo.

-----

> There are also less harmful code such as unused require()d modules that, none the less, should not exist.

I agree these should not exist, but to be on the same boat. These are not "less" harmful, these are not harmful at all (but could point to bigger problems like dead code).

---

I use prettier for all my new projects, and I like it a lot. Personally I don't link eslint (eshint is fine).

**The main problem I have with using Prettier right now is that we it would mean recommitting almost the complete codebase and messing up the audit trail (git blame) in the process. For linting the problem would be even worse since we first have to fix all linting errors in the current codebase.**

I am ready to jump on prettier right now if we can work around this in any way. Thoughts @levithomason @cmroche?

----

@cmroche 

> I have to admit that I am uncertain on the official standard you are using since there are a few different approaches being used in the code. [..] Can you clarify which standard you prefer?

In general I would love to see es6 (for as far as supported by node v6.0 - the current minimum requirement for Gekko, we should bump this soon) and as styled by prettier (any version above 1.5). I personally use `prettier --single-quote --trailing-comma es5`. BUT: looking at the current state of the complete codebase, I am not strict and it doesn't matter that much (would not be fair of me to require code to be styled in a way when the codebase is not).

**Comment by cmroche** [comment]
@askmike I agree about the GIT auditing, generally checking in a bunch of code isn't a great approach. But at the very least we could start updating code that we are modifying, it will muddy compares a little bit (unless you have diffing tools capable of ignoring whitespaces) but it will keep the changes to areas of code or files that are modified for logical reasons in any particular change. Usually this is how I've seen this type of modification handle with larger development teams :)

As far as how to enforce it, that I am less sure of. A precommit hook is always possible I suppose, but perhaps just part of the process of reviewing PR's would be enough? As long as a guide is in the wiki I would imagine it isn't too big of problem.

In any case I'll start prettifier'ing my work in the near future.
