### ISSUE TITLE
Feature request: BITMEX support

### ISSUE THREAD

**Issue by LooOOooM** [askmike/gekko#1331]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Please implement  BitMex, as it does all we need for successfull trades: Short, long, Laverage, and it is deam fast. I sew this is already on the roadmap, however just wanted to request for more priority as Kraken i.e is just not usable anymore -- they have far to much lags and random errors.

**Comment by Johannnnes** [comment]
I implemented BitMex partly. Only for strategy testing at the moment, so not ready for real trading yet. Will finish the rest one of these days.

![screen shot 2017-11-20 at 23 27 27](https://user-images.githubusercontent.com/591213/33044767-75b15f9a-ce4a-11e7-961a-682f143f41f8.png)

**Comment by askmike** [comment]
The biggest hurdle with Bitmex is that it all trading is margin trading. The exchange integration is not that hard, but in order to properly calculate profit Gekko needs to understand that a SHORT on bitmex is not the same as a SELL on another exchange:

If you are trading on Bitstamp and you sell your BTC for USD, you are out of the market and NOT exposed at all anymore. So your strategy can signal "LONG" in which case Gekko will buy (and calculate statistics accordingly). However on Bitmex you can actually short the market meaning that you are still exposed to the price. But you can also close all your positions which is the same as "selling your BTC" on bitstamp (with the exception that you are always holding bitcoin on bitmex).

**Comment by Johannnnes** [comment]
Thanks for clarifying that. I will try to find a solution and am always open to suggestions...

**Comment by STRML** [comment]
A good way to handle that is to keep track of your actual exposure in Bitcoin terms; shorting the swap or futures at 1:1 puts you flat. For example:

1. User has $1000 (flat Bitcoin exposure)
2. User converts that $1000 to Bitcoin (long Bitcoin exposure)
3. User sells 1000 contracts of XBTUSD or XBTZ17 (flat Bitcoin exposure)

This is exposed via the API as `markValue`. This is the value of the position in Bitcoin terms at the current price; note it is negative on a long XBT position because they are inverse contracts (that is, long Bitcoin is actually short USD). 

It's not a simple task but the same calculations could be reused for margin trading to a certain degree.

**Comment by Yoganesh** [comment]
Mike, since BitMEX also has a Testnet (http://testnet.bitmex.com), I assume I have to make everything twice (exchange file, importer file) since they both have their own respective API keys and there is no option in the Gekko UI to add multiple keypairs per exchange?

**Comment by jaydeeleefree** [comment]
I would also love this please :)

**Comment by timchepeleff** [comment]
@Johannnnes I'm looking to start working on this -- do you have any code you can share to potentially jumpstart the process?

**Comment by Johannnnes** [comment]
Will put what I have on my Github this weekend.

**Comment by ctwhome** [comment]
any news on this?

**Comment by goushijie** [comment]
++1

**Comment by kevin-valerio** [comment]
No news ? :(

**Comment by alexo382** [comment]
@Johannnnes I'm trying to integrate bitmex into gekko too, do you still have the code for what you did? I can't find it on your profile. Thanks!
