### ISSUE TITLE
General question, needing suggestion

### ISSUE THREAD

**Issue by dem1g0d** [askmike/gekko#1338]
Hey Mike, wanted to say your advice worked, reset API and everything is good. I'm running tradebot on poloniex right now (live trading or i assume thats what this is) and was wondering what is a basic no risk profile/trade setting you'd recommend? I'm not looking to get rich...if i can make a few cents or a couple bucks here and there I'll be happy, as I don't have a lot of money on the exchange to begin with lol. 

My understanding is the currency (usdt) is what i choose to trade with, and the asset is what i want to trade against (in my case, ripple), right? The bot hasn't made any trades yet which is cool, because I don't even think I'm doing this right. I'm using MACD with this parameter:
 {
    "short": 10,
    "long": 21,
    "signal": 9,
    "thresholds": {
        "down": -0.025,
        "up": 0.025,
        "persistence": 1
    }
}
TBH i really have no idea what im doing, just wanted a set it and forget it method to make a few bucks here and there. Do i need a minimum amount of USDT on the exchange? What happens when I run out of USDT to trade with? Will the bot move USDT to XRP and back and forth? I only have $5 of USDT to trade with and am wondering if the fees per trade will dwindle the overall funds and make my efforts pointless, if that makes any sense. I appreciate any help.

**Comment by greenbigfrog** [comment]
> TBH i really have no idea what im doing

Maybe you shouldn't try running a tradebot then

But to give you a more proper answer:
`Do i need a minimum amount of USDT on the exchange?` - Not unless there's a minimum trade size on your exchange.
`What happens when I run out of USDT to trade with?` - Nothing.
`Will the bot move USDT to XRP and back and forth?` - If you set it to trade USDT/XRP it'll trade USDT/XRP back and forth.
`I only have $5 of USDT to trade with and am wondering if the fees per trade will dwindle the overall funds`? - Yes. As long as the fee is higher as your profits, you'll end up with less then $5.

**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)** ( @askmike would be cool, if you could be a bit more active there now and then :smile: )
