### ISSUE TITLE
Cancel order and wait for next advice

### ISSUE THREAD

**Issue by kz0** [askmike/gekko#1340]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)
Option to cancel order and wait for the next advice if it's not filled after x minutes.

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Right now there is only one execution strategy: make the market, which is slow but the cheapest (no spread, no slippage, at some exchanges less fees). There are some ideas about how to add more options / configurations to impact this behaviour.

Why do you want Gekko to cancel after x minutes?

**Comment by kz0** [comment]
Sometimes the order gets in queue and isn't executed for 30 minutes and the price is changing so gekko isn't buying on the optimal calculated price, when cases like this happen it would be nice to cancel the order and wait for the next advice

**Comment by askmike** [comment]
Gekko is designed that whenever your strategy suggests a signal (buy or sell), Gekko will try to do it no matter what. There used to be an option to signal 3 things: BUY, SELL or WAIT. And if you strategy went from BUY to WAIT 30 minutes later, the order would get cancelled. Though we moved away from that because it was to complex (for Gekko as well as for users).

A better option would be to give users more control on different execution strategies: you can specify you want the trader to BUY no matter what, instead of trying to get the best deal (as is right now). See here for more context: https://github.com/askmike/gekko/pull/1349#issuecomment-345917433

Though an option to specify a time: I don't see the point? You care about Gekko getting a good price right, what does it matter how long it takes (assuming the signal did not reverse from BUY to SELL)?

**Comment by kz0** [comment]
Maybe i'm thinking about it the wrong way but suppose when the BUY signal is received the price is 10$, now the order isn't filled for 25 minutes and when it's filled the price is 12$. Now the signal reverses and the sell is filled at 11$. Since there isn't an option to cancel the order that wasn't executed in a timeframe you would lose your profit.

This was my point to on having this option which would prevent unwanted buys or sells.

**Comment by chrisdenley** [comment]
Maybe a setting to make gekko complete trades more promptly? Like instead of waiting minutes for someone to take our order, lower the price after a couple seconds if it hasn't been filled yet. Maybe even a setting to sacrifice X percent on the price of your order to make sure the order is filled quickly.

**Comment by Stealthbomber76** [comment]
I jump in here too. I have the problem with Binance that the order is placed but get's cancelled pretty much each second or so and many times until i get a email from Binance about API rules =( So how can i make the orders more Wait until next order is placed? Thx
