### ISSUE TITLE
Indicator with a different timeframe

### ISSUE THREAD

**Issue by illion20** [askmike/gekko#1377]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I wanted to implement a 15 min MACD on a 4 min candle size. I created a new indicator based on MACD.js and added a modulus in the update 
`if(this.age % 3.75 == 0)`
However it gives very different results from Tradingview 

* **Expected result** (what you hoped would happen)
Be similar to the Tradingview result for the same 15 min MACD security running n a 4 min chart

* **Actual result** (unexpected outcome)
It is sometimes off with more than 20 points. Perhaps its due to that Tradingview calculates the 15 min with the latest value meaning whenever a new tick comes along its used and recalculated until the 15 min candle close.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I would greatly appreciate any suggestions

**Comment by illion20** [comment]
Seems the highs and lows are off a bit too, how can that be since this is imported historical data?
![image](https://user-images.githubusercontent.com/29117895/33350395-e1263b22-d4e1-11e7-9e16-c95e0ef350e9.png)

**Comment by askmike** [comment]
Two things first:

- Gekko calculates candles based on the minute you start it, to take away bias around round hours (which in crypto markets don't make sense). So MACD is calculated over different most likely already.
- There are certain differences between MACD implementations, such as history size (which in Gekko depends on your settings + internal settings).

Than:

`if(this.age % 3.75 == 0)` you can do this, but it would never hit, age is only ever incremented by 1 (when a new candle of the candleSize you configured is calculated). Having different indicators in different candle sizes (timeframes) is out of scope for now. But people have altered versions of Gekko that supports this in the past. Here is some reading material:

- #496.
- #762.
- #796.

I want to make Gekko's codebase more modular and extendable, so this will become easier in the future. However I am not likely to merge different timebased indicators into stable  @gekko because of the complexity around configuration. Closing this as dup of above issues, but feel free to keep commenting.

**Comment by illion20** [comment]
Thanks for your reply.

Actually it did work with just the modulus. I can now have multiple timeframe indicators.
`if(this.age % targetTF/baseTF == 0)`

The updated MACD as an example looks like this now and it also supports the same kind of incremental increase as Tradingview before the longer TF candle is closed.

`Indicator.prototype.update = function(price) {
  if(this.age % this.period == 0) {
     var shortEMA = this.short.update(price);
     var longEMA = this.long.update(price);
     this.diff = shortEMA - longEMA;
     this.result = this.signal.update(this.diff);
  } else {
     var shortEMA = this.short.partialUpdate(price);
     var longEMA = this.long.partialUpdate(price);
     this.diff = shortEMA - longEMA;
     this.result = this.signal.partialUpdate(this.diff);
  }
  this.age++;
}
`
