### ISSUE TITLE
Simulate backtest with existing strategies/param combo to find highest profit?

### ISSUE THREAD

**Issue by patjk** [askmike/gekko#1383]
So say I have a dataset from date range A to B.  I want to backtest this same data set with each built in strategy and parameter configuration and output the parameters that would return the highest profit on the data set over A to B.  Ideally it would test the multiple thousands of combinations and return which configurations return the highest profit on the dataset.  Is it possible to do this? And if so, how?

Thanks.

**Comment by askmike** [comment]
Gekko is quite basic, however it does provide an API you can script against. I would recommand reading these issues:

- #1302
- #1095
- #997 
- #1102

GA (genetic algorithms) is most likely the closest to what you describe (you are talking about simply brute forcing parameters). Whatever you want: you need to script this yourself on top of Gekko or use an GA tool available for Gekko (see issues above). Closing this as a dup, since further questions are most likely better answers in these issues :) But feel free to ask questions here nonetheless.
