### ISSUE TITLE
Problem to connect with kraken

### ISSUE THREAD

**Issue by jp054** [askmike/gekko#1431]
Hi,
When I start Gekko on my Raspberry with my config-file, I have this `error:`

```
2017-12-06 20:36:37 (DEBUG):            Available local data:
2017-12-06 20:36:37 (DEBUG):                    from: 188 minutes ago
2017-12-06 20:36:37 (DEBUG):                    to: 136 minutes ago
2017-12-06 20:36:37 (INFO):             Usable local data available, trying to match with exchange data..
2017-12-06 20:36:37 (DEBUG):            Fetching exchange data since 151 minutes ago
2017-12-06 20:36:54 (ERROR):    error getting trades { HTTPError: Response code 504 (Gateway Timeout)
    at StdError (/home/pi/gekko/node_modules/got/index.js:410:3)
    at /home/pi/gekko/node_modules/got/index.js:454:3
    at stream.catch.then.e (/home/pi/gekko/node_modules/got/index.js:182:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'HTTPError',
  host: 'api.kraken.com',
  hostname: 'api.kraken.com',
  method: 'POST',
  path: '/0/public/Trades',
  protocol: 'https:',
  url: 'https://api.kraken.com/0/public/Trades',
  statusCode: 504,
  statusMessage: 'Gateway Timeout',
  headers:
   { date: 'Wed, 06 Dec 2017 20:36:54 GMT',
     'content-type': 'text/html; charset=UTF-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'set-cookie': [ '__cfduid=d2225df5596070091ac2835824c93db4c1512592597; expires=Thu, 06-Dec-18 20:36:37 GMT; path=/; domain=.kraken.com; HttpOnly' ],
     expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
     'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
     pragma: 'no-cache',
     'x-frame-options': 'SAMEORIGIN',
     server: 'cloudflare-nginx',
     'cf-ray': '3c9209d93e85151b-CDG' } }
2017-12-06 20:36:54 (ERROR):    [kraken.js]  kraken returned an irrecoverable error

```
I have not idea of the problem.
Thanks you.

**Comment by askmike** [comment]
We are working on Kraken stability, which is quite hard given the current state of the exchange. See
#1426 and #1411.

@cmroche looks like we have another recoverable error for the whitelist.

**Comment by jp054** [comment]
Thank you for your answer. I try several times to run gekko, I still have this error. it can not come from my config?

**Comment by askmike** [comment]
Not if the error is the same as you posted above. The problem is that right now most "requests" to kraken fail. It's exactly the same if you try to use the website, most of the time it will look like this:

<img width="1255" alt="screen shot 2017-12-07 at 17 45 16" src="https://user-images.githubusercontent.com/969743/33708799-6c887d66-db76-11e7-94a2-a9ca85445395.png">

When Gekko sees that it should retry, but it's not. This is exactly what we are working on right now. If you feel mega adventures you can try this version of Gekko: https://github.com/askmike/gekko/tree/cmroche-retry_handling-hotfixes However note that we are currently working on this exact issue so things might not work as expected.

(remove current one, download and install that one.)

**Comment by jp054** [comment]
Thank you I will try. I have also this error:

![error](https://user-images.githubusercontent.com/34319814/33709107-a24f286c-db3c-11e7-8240-4ebd6925f1d0.PNG)

**Comment by askmike** [comment]
pretty sure that new version should take care of that as well.

**Comment by jp054** [comment]
It's working now ! Thanks

**Comment by greenbigfrog** [comment]
@askmike this can be closed
