### ISSUE TITLE
Started Tradebot from bash, got a bunch of gibberish [win 10]

### ISSUE THREAD

**Issue by BenVlodgi** [askmike/gekko#1500]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken**
> Using Windows 10 ubuntu bash
> Set up trading bot to trade on binance using the RSI strat.
> Start process using custom config
> Process starts, but then spits out a bunch of gibberish and ends

* **Other information** 
Log screenshot:
![image](https://user-images.githubusercontent.com/1462374/34078686-467e7d5e-e2ed-11e7-8873-6787cc3bddf8.png)

I'm running on nearly the latest of stable https://github.com/askmike/gekko/commit/448900d9099ff2daf5511b0a3a47f1081669bc1e the only commits after are textual

**Comment by madaerodog** [comment]
Try another exchange to see if you get the same result. Seems something related to the binance one.

**Comment by cmroche** [comment]
@BenVlodgi Sometime binance API errors are met with this type of response, it's terrible.. but that's a binance issue. In this case I would recommend trying again later, however hard to know for certain that the cause isn't temporary since there are little details in the output from the server.

FYI, I've pushed a change to the binance API wrapper to better report errors instead of dumping the payload, this will give better reporting once implemented https://github.com/aarongarvey/binance/pull/9

**Comment by BenVlodgi** [comment]
This is still a problem on stable and develop
