### ISSUE TITLE
standard_init_linux.go:185: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by huglester** [askmike/gekko#1597]
* **I'm submitting a ...**
[x] bug report

* **Action taken** (what you did)
https://gekko.wizb.it/docs/installation/installing_gekko_using_docker.html
$ docker-compose build
$ docker-compose up -d

* **Expected result** (what you hoped would happen)
localhost:3000 to show the UI

* **Actual result** (unexpected outcome)
after viewing logs: docker logs -f gekko_gekko_1
I see  lot of these messages, and container keeps restarting
standard_init_linux.go:185: exec user process caused "no such file or directory"

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to Docker version 17.09.1 (on macos sierra)

Where could I search for a sollution?

Thank you!

**Comment by kerberjg** [comment]
Bump, I have the same problem

**Comment by damiengogo** [comment]
hi, exactly the same pbm ! :s

**Comment by damiengogo** [comment]
git config --global core.autocrlf false

then normal git download ;)

**Comment by vietlongn** [comment]
This issue will occurred if you're running on windows. Git automatically converted docker-entrypoint.sh to windows-styled line ending.
The proper way to fix this issue is convert docker-entrypoint.sh back to Unix-styled line ending by run this command on your cmd:

`dos2unix.exe docker-entrypoint.sh`

Then rebuild your docker images by:

`docker-compose build --force-rm`

Enjoy!
