### ISSUE TITLE
Multiple market orders on advice

### ISSUE THREAD

**Issue by jurepetrovic** [askmike/gekko#1608]
Hello, 

I've seen, that the strategy should either give "BUY" or "SELL" advice. 

Is it possible to execute multiple orders on specific signal? 
For example I'd like to issue simultaneously:  
BUY @ X$
SELL @ X+Y$
SELL @ X-Z$

As I see gekko architecture, I can only imagine the current workaround would be to keep order state
within the strategy and issue sell orders later when the price hits the limit...

Any Ideas? 

I'd like to prevent loss in case market api gets unreachable as it recently happened on coinbase...
Thanks, 
Jure

**Comment by ianwaldrop** [comment]
I've been thinking about this too, and one possibility I've considered is implementing a limit-based stop-loss when a purchase is made such that once an order is filled a sell limit order is placed for an identical amount at some point from current asking down. This way the limit will fill if the price drops too much without gekko needing to wait for the data to get to it and for the strategy to be checked. 

To me it seems like the strategy could be a good candidate for informing the portfolio manager of the stop price though since a) that's how we express our intent to gekko and b) stop loss strategies often go hand-in-hand with long/short strategies. I've considered another agent doing this work too, however, something that monitors the order book and determines where the best places to buy/sell are; in my experience it's rarely the very next price on the book.

**Comment by askmike** [comment]
This is not possible right now, though it might be in the future: Have a look in this discussion #1942 and this PR #1968.
