### ISSUE TITLE
Long backtesting simulations stop

### ISSUE THREAD

**Issue by gianni76** [askmike/gekko#1614]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I am using Gekko 0.511 (latest development branch) with the browser GUI under Windows and attempting to simulate real-life action.
With longer-sized candles (30m, 1h), the simulations run smoothly.
But for shorter-sized candles (say 2m or 5m), even a limited samples set of 4 weeks cannot finish simulating.

* **Expected result** (what you hoped would happen)
I am expecting Backtesting to complete all the simulations.

* **Actual result** (unexpected outcome)
In some cases, the Backtesting section starts correctly, I can see the flow of information in the console window. But after a while (around 5-8 minutes), the 'ongoing action' (moving vertical bars) gif (the one which should then be replaced by the Graph and the results) disappears from the Gekko GUI and nothing happens anymore on the main GUI.
The console window still runs and most of the time seem to complete the points of the simulation, but the main GUI seem disconnected and never shows the final results nor the graph. 
(for longer simulations even the console stops after a while)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Might be a memory problem? Not sure how to avoid it...
This bug shows both calling gekko normally:
node gekko --ui

and using the extended memory node call:
node -max-old-space-size=8192 gekko --ui

**Comment by philmodin** [comment]
I've been able to run 2 min candles on 3 months worth of data (takes a few minutes). No success with 1 min though. Using Chrome for ui on Win 7.

**Comment by Duwaynef** [comment]
you have to increase the timeout value in the UIconfig.js for the web portal.

change it from the 2 minutes to like 2 hours. and when gekko is done it will pop up.

**Comment by JoeTeglasi** [comment]
![8b53a5e8-3914-4664-aa39-9870b5bc221c](https://user-images.githubusercontent.com/35932269/36365436-915c7e28-1517-11e8-8441-1d6851483ec8.png)

I have the same problem. Using 1min candles, and after 2k-3k candles I get this error message:
Error: read ECONNRESET 
(See pic for rest of error message). 

I am also using max-old-space-size=8192, but that’s because running any less than that could cause my Gekko to crash if I’m running a papertrader and backtesting and importing all at the same time. 

I have also increased the timeout value in UIconfig.js to like 20 weeks, so idk why it’s having any problems. 


@askmike, are there any pending pull requests regarding this issue? Or could you explain what causes this error?
