### ISSUE TITLE
[request] Logs display within UI

### ISSUE THREAD

**Issue by zzmike76** [askmike/gekko#1732]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started paper trading in UI
Started paper trading via command line

* **Expected result** (what you hoped would happen)
Display some logs in the UI to understand what's happening in background. While the command line returns tons of data, within the UI it's not clear whether the batch jobs are currently working properly

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
I am going to do a major overhaul to the UI. Wouldn't it be better for the UI to give more details in a more visual way? The log is supposed to only contain debug information.

**Comment by zzmike76** [comment]
yes i was just wondering whether the background process could output to the UI just to see what's happening.

**Comment by hilkoc** [comment]
I'd like to have this feature too. For each (paper) trader that is running a page to view the debug log. Visualizations are nice to have, but not necessary.

**Comment by mladenmilev** [comment]
@askmike Hi, for the UI it is important to be "simple but functional". I can offer my help in reviewing and helping some suggestions. I am using mainly the UI last weeks and I see several problems. 

- UI should allow to start and stop a bot instance (currently only allows to start new one)
- UI should present correct information in the trade history. Currently many errors, not sure why - bad parameters or rounding, different formatting. (**see attached image**)
- UI should allow ordering/filtering on the pairs, so that when bot works for a long time and it accumulates many pairs, and history it is easier to select correct pair in the UI.
- UI should allow enabling and configuring of different plugins per bot instance (sending emails per bot instance, not general for all bots).
- Export/Save trading history to CSV or Excel file.
- UI should indicate if there open order on the exchange for execution and what are the parameters of that order. If the user allowing the user to manually overwrite it. 
- A very nice feature would be to have the possibility to overwrite/anticipate trade manually by a button.  In a certain way anticipate a strategy signal. "Go Short" "Go Long".  


![image](https://user-images.githubusercontent.com/18348943/35508861-dd97ae22-04e9-11e8-9e89-f5ec735b013e.png)
