### ISSUE TITLE
Wrong Buy Order on Custom USDT

### ISSUE THREAD

**Issue by TheAISlop** [askmike/gekko#1749]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Using Gekko custom to place USDT order on Kraken.  Using 1.0050

* **Expected result** (what you hoped would happen)
Order should show up as 1.0050

* **Actual result** (unexpected outcome)
Order showing up as 1.000

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Created .js from custom example.

// Prepare everything our strat needs
strat.init = function() {
  // setting buy price
  this.buyPrice = 1.0050;

  // setting sell price
  this.sellPrice = 1.000;
}

**Comment by cmroche** [comment]
The precision is set wrong for this market, currently 2 and should be 4.

This is fixed in PR #1550 which uses a script to generate the correct market configurations from the exchange web API, alternatively you can open kraken.js on your local build, find the market for USDUSDT near the bottom and change `precisions: 2` to `precision: 4`. This will fix your clamping issues.
