### ISSUE TITLE
Web UI: Show Paper Trader vs TradeBot

### ISSUE THREAD

**Issue by rcoenen** [askmike/gekko#1766]
It's currently impossible to tell live Tradebots apart from Paper Traders in the WebUI
<img width="935" alt="paper-vs-live-tradebot" src="https://user-images.githubusercontent.com/753704/35248802-6158e41a-ffc7-11e7-9421-96fd02c2977f.png">

**Comment by rcoenen** [comment]
relates to #1767

**Comment by askmike** [comment]
@rcoenen thanks for this issue, it's a very valid suggestion. I want to improve this. Because the redesign requires more than just writing some code I've posted a topic in the Gekko forum, might I suggest we use that to discuss a new design for the UI?

Here is the link: https://forum.gekko.wizb.it/thread-65.html

(closing this to move the discussion to the forum)
