### ISSUE TITLE
StratRunner page missing crucial info

### ISSUE THREAD

**Issue by rcoenen** [askmike/gekko#1767]
Unable to see if this is a Live or Paper trader
Unable to see what candle size and warmup were specified

![candle-size](https://user-images.githubusercontent.com/753704/35250742-14eab76c-ffd0-11e7-80c1-51e039d3cd45.png)

**Comment by askmike** [comment]
Very good points, I want to redesign this page and have been working on some sketches. What do you think of the following:

(list of what I want to show on this page)

![img_20180123_010355](https://user-images.githubusercontent.com/969743/35251026-a4395d20-ffd9-11e7-91c8-5e2c2fa8d0bd.jpg)

(sample sketch of how that might look)

![img_20180123_010407](https://user-images.githubusercontent.com/969743/35251032-acd1b75c-ffd9-11e7-859d-3ad08877e16c.jpg)

**Comment by rcoenen** [comment]
Yeah that makes a lot of sense. The start-stop feature is pretty crucial too indeed!

try getting a free license of Balsamiq to sketch some wireframes out perhaps? ( https://balsamiq.com/free/ )

**Comment by askmike** [comment]
Haha yea the paper sketching wasn't meant for sharing directly. Even though the UI is pretty straightfoward, this requires an overhaul of the API logic. I'll work on this over the next few weeks, so don't expect this soon.

**Comment by gvdhoven** [comment]
@askmike i like the redesign. Related: it would also be cool to have a 'update' button on the import page/local data after each data-set where you can specify what date range to add to your local data. After clicking this button and filling in the parameters it will re-import for you. Maybe add 'market' as a column there? 
Partially it relates to my pull request; https://github.com/askmike/gekko/pull/1726

Is it also going to be possible to 'graph' the indicators in the charts? e.g. RSI etc?

**Comment by askmike** [comment]
@Webunity that is definitely functionality we want, I'll look at your specific implementation asap (apologies for the delay, I am way behind on Gekko).

@rcoenen thanks for this issue, it's a very valid suggestion. I want to improve this. Because the redesign requires more than just writing some code I've posted a topic in the Gekko forum, might I suggest we use that to discuss a new design for the UI?

Here is the link: https://forum.gekko.wizb.it/thread-65.html

(closing this to move the discussion to the forum)
