### ISSUE TITLE
Migrate codebase to TypeScript

### ISSUE THREAD

**Issue by IlyaGulya** [askmike/gekko#1777]
I've just started to explore the Gekko codebase. And i found that it is written in js.
Did someone think about migrating to TypeScript to get more clear, expressive and typesafe codebase?
If i will do that, will it be useful for you? I wanted to start migration but i want to get any feedback about this idea before starting.

**Comment by bafxyz** [comment]
ES6 is better approach in my opinion, native solutions are better, and it's easier to write new components in chosen way, instead of migrating everything, IMHO it's not a prio task.

**Comment by IlyaGulya** [comment]
So, migration to ES6 is okay and will be useful, right? I found that there's no even ES6 in the project :slightly_smiling_face:

**Comment by fredmarques** [comment]
Hey guys... Is there a WIP on this issue? I would like to contribute

**Comment by yaruzo11** [comment]
What about WebAssembly? Can we use that for even better performance?

**Comment by dcworldwide** [comment]
Massive Typescript proponent based on 2 years of working with it and Babel. I can not vouch for the technology enough, especially in large collaborative projects like this one. 

Typescript has the benefit of being something we can introduce gradually (file by file) and is essentially idiomatic es6 with excellent support fo ES7 features like async wait, async iterators and decorators. Typescript emits pure js and can downlevel emit es7 features all the way back to es3.

**Comment by askmike** [comment]
The codebase is huge and old, migrating everything to typescript would take a long time.

On top of that I personally dislike typescript a lot (I do have experience with it. I have been forced to use it in the past). If I had to choose a typesystem I rather go with flow, but I also dislike that unfortunately.

People are free to maintain a fork of Gekko that has typescript added, however I won't be maintaining it :(

----

My suggestion for people who want a free language that is typed is to write it in golang instead, that is what would do if I were to start Gekko today instead of in 2013.

:(

---

> ES6 is better approach in my opinion, native solutions are better, and it's easier to write new components in chosen way, instead of migrating everything, IMHO it's not a prio task.

@bafxyz agree, I am using more ES6 features in all newer code that hits the codebase. The current REST API is written in koa v1 (generator functions instead of async/await) but I want to upgrade that to koa v2 (async/await) soon as well.

@IlyaGulya 

> I found that there's no even ES6 in the project 🙂

Not sure where you have been looking, there is loads.
