### ISSUE TITLE
QuadrigaCX API fails to authenticate

### ISSUE THREAD

**Issue by BennZoid** [askmike/gekko#1803]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Start gekko with QuadrigaCX in trading mode

* **Expected result** (what you hoped would happen)
Connect and start monitoring for trades

* **Actual result** (unexpected outcome)
Fails to connect with `{"code":101,"message":"Invalid API Code or Invalid Signature"}`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I have tried resetting my API secret multiple times and always confirmed that the key is correct.

According to the [API documentation](https://www.quadrigacx.com/api_info) Quadriga requires a signature to be generated with each API call.  Is it possible gekko is missing this signature calculation?

**Comment by cmroche** [comment]
Your client id (visible on the QCX login form) is entered as the "username" when providing credentials to Gekko.

FYI: Live trading hasn't undergone a great deal of testing for this exchange, so please be mindful and report bugs if you encounter any. I am the maintainer of this exchange, so to speak, so ping me in any reports please.

**Comment by BennZoid** [comment]
Thanks for taking a look @cmroche !  I tried with and without using my client id as username previously.

For further testing I just took a clean checkout of the dev branch and modified the following config values from the default.  In `config.watch` I set `exchange: 'quadriga',
  currency: 'CAD',
  asset: 'BTC',` and confirmed the paper trader is working for the exchange.  

Following that I disabled `config.papertrader`, enabled `config.trader` and set the key and secret to the ones on quadriga and the username to the client ID.  Also set the disclaimer to true.

Upon starting I get the same Invalid API code or signature error

**Comment by cmroche** [comment]
I vaguely remember a confusing problem with their API where in the end they expected the client_id to be passed as a string and not a number, ie: username: '1' and not username: 1 to compute the correct signature. Please try that and let me know if it resolves the issue as we can force the type, if not I'll take a look at some point during the week.

**Comment by BennZoid** [comment]
Just tested with no quotes, '1' and "1" for username.  All of the above are giving me the same error.  Also I tested running quadriga through the web version and it doesn't visibly error out but it doesn't appear to be trading either.

**Comment by jchudon** [comment]
Hello,

I too have been encountering the same problem.
I have fixed the API connection but then got stuck on Quadriga not accepting currency in upper case. 

I've also fixed this but since, I'm stuck on a crash involving getting orders after having placed a buy/sell order. So far, I haven't been able to circumvent this one.

I unfortunatly don't have the knowledge to do more than quick patches without really knowing the impacts on other things. There seems to be quite a few bugs in this section and I'm unfortunately not knowledgable anough to fix them all.

**Comment by cmroche** [comment]
@jchudon Please open a new issue with the details of the crash you are not encountering, including the log output and ping my name in there. I will look at it as time permits. Also if you have a fix for the authentication, copy and paste it here, I will check it an make a push request, unless you would like to prepare one.

Thanks.

**Comment by jchudon** [comment]
In the following function in  /node_modules/quadrigacx/lib/quadrigacx.js, drop "secret_hash" and use "Secret from parameters instead in  Quadrigacx.prototype.private_request = function(path, params, cb) { .... }

**Comment by cmroche** [comment]
@jchudon Sorry, but I am not following, can you paste the change you made? I don't think we should have to modify the node module to make this work, I've been able to trade on QCX with this module without modifications, but if I can see the change you made perhaps I can find another source for the error.

Thank you.

**Comment by jchudon** [comment]
signature = crypto.createHmac("sha256", this.secret).update(signature_string).digest('hex');

using this.secret instead of this.secret_hash where this.secret is the parameter from private_request

**Comment by cmroche** [comment]
this.secret isn't defined in the quadrigacx.js module. I'm not sure that this should be generating a correct hash for you.

**Comment by cmroche** [comment]
@BennZoid @jchudon I remember the problem now! The issue is the secret key you are using. When you create a new API key manually in QCX you are asked to input a value that will be used to compute a hash, the value you input manually is the "secret". If you use the API key summary page you will only see the hash of this value, that is not the correct value to use.

This is an ambiguity in the QCX settings which isn't very clear. I wish they would change that!

https://www.quadrigacx.com/assets20180209/images/api/figure.2.png

The secret you see here is the wrong value. If this is what you see, then you will have to create a new key since there is no way to get the original value used to make that hash (unless you saved it).

**Comment by jchudon** [comment]
Confirmed as working.

**Comment by BennZoid** [comment]
Can also confirm its working, closing the issue now.  Thank you @cmroche!

**Comment by jcoder76** [comment]
I can't even see the option for QuadrigaCX.

**Comment by cmroche** [comment]
@daflame That more likely indicates a problem with your installation of gekko, you may want to consider download and re-installing in another location and see if that resolves the issue for you. If not, then try moving t the develop branch.

If you continue to have problems please open a new issue.

**Comment by jcoder76** [comment]
@cmroche I may do just that since I can't get it to work no matter what I do, yet all the other ones show up.  Unfortunately I am ONLY looking to use QuadrigaCX right now.  I'm a developer so if possible I can help improve integration as well and drop a PR.
