### ISSUE TITLE
Strat for MFI and MACD on Windows? (Could also get a Pi if that's easier.)

### ISSUE THREAD

**Issue by Hardwyre** [askmike/gekko#1844]
Hello.

I have found that I've had good luck trading manually using MFI in cooperation with MACD.

I'm having a hard time understanding how Gekko's MACD settings work because backtesting doesn't seem to give results, but I'm running this on a Windows 7 system and I understand that not all of the indicators work properly.

I have considered getting a Raspberry Pi and running Linux for this along with a battery backup as I've already had some power outages here before which stopped my more clumsy bot in the past.

I couldn't find an MFI example in the stock strats, and I'm having trouble understanding and incorporating new ones since I don't understand javascript all that well.  

So a few questions:
1. Does anyone have an MFI and MACD set up they'd share?  

1. Is there a good resource/documentation for adding new strats (I saw the tutorial on the website but it was a bit sparse)?

Would running it off a Pi be a bit easier over all?

Appreciate the help.

**Comment by askmike** [comment]
> I'm having a hard time understanding how Gekko's MACD settings work because backtesting doesn't seem to give results

Most of the time when I hear someone talking about this the problem is quite simple: when running MACD over a market where a coin is very cheap (say a BTC/ALT market where the ALT is few satoshis or so) the [thresholds](https://gekko.wizb.it/docs/strategies/example_strategies.html#MACD) never get hit since the price is lower than the when the thresholds get hit.

Try adjusting the thresholds under Parameters to lower number more reflective of the price of the market. If that doesn't work please reply here.

> Is there a good resource/documentation for adding new strats (I saw the tutorial on the website but it was a bit sparse)?

I am making a new one very soon, in the meantime please ask around in [the discord](https://discord.gg/26wMygt) or head over to [the forum](https://forum.gekko.wizb.it/). We'd like to keep this place for discussing technical issues :)

(though do reply if the threshold adjustment does not work, there might still be a technical bug).
