### ISSUE TITLE
new strategy

### ISSUE THREAD

**Issue by jjhesk** [askmike/gekko#1861]
is that possible to add ANDERSON-DCA strategy to gekko?

**Comment by askmike** [comment]
Yes, though you need to script the strategy/indicator yourself.

- This documentation is a good starting point: https://gekko.wizb.it/docs/strategies/creating_a_strategy.html
- If you want to do this yourself you can ask around on the forum if you run into issues: https://forum.gekko.wizb.it/forum-12.html
- if you want someone else to do it you can create a bounty for it: https://forum.gekko.wizb.it/thread-71.html

Closing this since this is the bug tracker.
