### ISSUE TITLE
Attempting to run Gekko on AWS EC2 with NGINX

### ISSUE THREAD

**Issue by ricksternyc** [askmike/gekko#1868]
Hi,

Running in circles here with varying results, at the point where I've lost track of what was almost working and not working at all. Was looking at #967, but did not solve.

Following instructions here.....
https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#configuring-gekko-to-run-in-the-cloud

**cd gekko/web/vue
vi UIconfig.js**

CONFIG = {
headless: true,
api: {
host: 'xx.xx.xx.xx', // IP
port: 3000,
},
ui: {
ssl: true,
host: 'gekko.example.com', //trying localhost here as well 
port: 443,
path: '/' // change this if you are serving from something like example.com/gekko
},
adapter: 'sqlite'
}
//this bit not in the installation docs, but read in previous thread it should be included?
if(typeof window === 'undefined')
module.exports = CONFIG;
else
window.CONFIG = CONFIG;

**nginx/sites-enabled
sudo vi default**

server {
listen 80;
listen [::]:80;
server_name gekko.example.com;
return 301 https://$server_name$request_uri;
}

upstream websocket {
server localhost:3000;
}

server {
listen 443 ssl;
listen [::]:443 ssl;
root /var/www/html;

ssl_certificate /etc/nginx/ssl/nginx.crt;
ssl_certificate_key /etc/nginx/ssl/nginx.key;

location / {
proxy_buffers 8 32k;
proxy_buffer_size 64k;

running from gekko directory node gekko --ui

**Result:**

events.js:163
throw er; // Unhandled 'error' event
^

Error: listen EADDRNOTAVAIL xx.xx.xx.xx:3000 //again using IPv4 Public IP from EC2
at Object.exports._errnoException (util.js:1050:11)
at exports._exceptionWithHostPort (util.js:1073:20)
at Server.setupListenHandle [as _listen2] (net.js:1243:19)
at listenInCluster (net.js:1307:12)
at doListen (net.js:1432:7)
at _combinedTickCallback (internal/process/next_tick.js:83:11)
at process._tickCallback (internal/process/next_tick.js:104:9)
at Module.runMain (module.js:607:11)
at run (bootstrap_node.js:427:7)
at startup (bootstrap_node.js:151:9)
at bootstrap_node.js:542:3

I previously had it working to the point where it said "Serving on gekko.example.com:443"
tried localhost in place, that didn't work. At the point where I give up, lol, any advice? Thanks!

**Comment by askmike** [comment]
> Error: listen EADDRNOTAVAIL xx.xx.xx.xx:3000 //again using IPv4 Public IP from EC2

Means something else on your server is already bound to the part, you most likely have gekko running somewhere else in another tab (ssh shell I mean, NOT browser tab).

----

Here is a gist of how things should work:

- Server should have nginx (with ssl certs configured), nginx should be listening on port 433.
- if you use nginx you need to make sure the UI connects to the nginx port (which will sit between the frontend and backend), for this configure config.ui.port to 443 (and ssl to true).
- nginx will then try to upstream (assuming you have proper nginx config) all requests hitting it to the server:
- the gekko process (= web server) should be started ONCE and listening to port 3000.

----

Note that installing gekko securely on a live webserver requires a lot of knowledge about servers and ssh and such. I am working on a hosted solution people can use so that don't have to go through all of the problems you are experiencing, instead of renting a server and maintaining the complete installation I will do that for them. See here for details: https://forum.gekko.wizb.it/thread-1435.html

----

Unfortunately I need to close this now, this is a bug tracker and not the perfect place for installation help. Please use this forum for that: https://forum.gekko.wizb.it/forum-19.html

**Comment by ricksternyc** [comment]
Thanks for linking to the forum Mike, didn't even know that existed. Will poke around there. Great project, been using it on Desktop!
