### ISSUE TITLE
Binance Gekko recvWindows = 60000. Binance actually recommends < 5000

### ISSUE THREAD

**Issue by thisisloze** [askmike/gekko#1880]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ x ] question about the decisions made in the repository

* **Action taken** (what you did)
Looking at Binance API.
An additional parameter, recvWindow, may be sent to specific the number of milliseconds after timestamp the request is valid for. If recvWindow is not sent, it defaults to 5000.
Serious trading is about timing. Networks can be unstable and unreliable, which can lead to requests taking varying amounts of time to reach the servers. With recvWindow, you can specify that the request must be processed within a certain number of milliseconds or be rejected by the server.

Recommended to use a small recvWindow of 5000 or less!

* **Expected result** (what you hoped would happen)
Im assuming it should be 5000 as I cannot find where this suggested 60000 is?

* **Actual result** (unexpected outcome)
Gekko binance.js //line 27
recvWindow: 60000, // suggested by binance (cant find any suggestions on this actually infact its the exact opposite of what is suggested)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Was this a typo? Am I not understanding something?

**Comment by thisisloze** [comment]
Would there be any downside to gekko if I switched my window to the default of 5000?

**Comment by askmike** [comment]
> Serious trading is about timing.

Not with Gekko, this 100% depends on the type of trading you do. Gekko is not designed to be fast. The fastest Gekko can be (even before doing an actual trade) is 1 minute precision. However most people actually use it at hourly or daily precision. Reacting milisecond fast is only necesarry for a different kind of trading relient on orderbooks, microstructures, etc.

---

I actually rather turn the number up than down. A ton of users are still having problems, see #1855 for example.

---

> Would there be any downside to gekko if I switched my window to the default of 5000?

A ton of people encountering more errors since they are on slow wifi on the other side of the world (binance is hosted in japan).

**Comment by askmike** [comment]
I'm open to discussing this, but please let's do it on the forum: https://forum.gekko.wizb.it

There is a reason this number is so high right now, until we change that this is intentional and not a bug.

**Comment by thisisloze** [comment]
Not sure what #1855 has to do with this? Not sure what your saying here at all. But alright. I'm not on WiFi and my connection isn't slow.

**Comment by thisisloze** [comment]
Well even with 1m candles I'm getting over 5-6 mins of slippage. Just trying to not loose coins every trade. Will make an account on the forum. Thanks
