### ISSUE TITLE
Is it possible to trade parts of my asset at a time, not the whole?

### ISSUE THREAD

**Issue by jeongmincha** [askmike/gekko#1885]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ v ] question about the decisions made in the repository

* **Action taken** (what you did)

I'm digging into a little bit deep parts of your project codes because I want to buy or sell parts of assets I have at one trade.

For example, assume that I have 1 BTC. When I want to take a short position at a specific time, but I don't want to sell my all BTC, I don't know how to get gekko to do this. 

I know that I can use `this.advice("short")` or `this.advice("long")` in my strategy code, but you know, the method doesn't seem to provide other parameters that we might need, for instance, amount or percentage.

If this feature has not been developed, but all of you want to specify amounts of each trade, I think this feature should be developed shortly.
Please let me know if I can make small transactions with existing codes.
Thank you in advance.

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
This question comes up a lot and here is what we are working on: A way to only let Gekko play with a part of your funds: if you have 1 BTC but want to limit gekko to 0.1BTC you can configure that in the future.

----

However partial balance trades (like sell 0.1BTC now and sell 0.1BTC in 10 minutes) make all the current statistics moot since since they assume you are getting in and out of full positions. Exposure becomes a lot harder to calculate  as well. It is never going to work with the current interface and current codebase (right now you cannot sell twice in a row, you can only sell after a buy and vice versa).

----

If you want to hotpatch it yourself:

- Run gekko via the commandline interface (See [here](https://gekko.wizb.it/docs/commandline/about_the_commandline.html)).
- Disable the peformanceAnalyzer since it won't work properly.
- Remove [this restriction](https://github.com/askmike/gekko/blob/develop/plugins/tradingAdvisor/baseTradingMethod.js#L319).
- figure out a way to measure profit yourself (since you can't use gekko's code)
- hack in a payload in the advice event that specifies the amount to trade.
- hack code into the trader that uses this amount instead of max.

**Comment by askmike** [comment]
I am definitely thinking about a different type of tradebot that actually manages a portfolio of different things and uses different strategies to come up with a risk & hedge model and execution model (how to go from LTC into XRB?).

What you describe sounds more like this than like gekko.

That's just very much out of scope for gekko right now, see here what's in scope: https://gekko.wizb.it/docs/introduction/scope.html
