### ISSUE TITLE
Remove No Issue

### ISSUE THREAD

**Issue by newgithubacc1v** [askmike/gekko#1887]

**Comment by askmike** [comment]
Please post logs, they are stored in the `gekko/logs` folder (if you were using the UI).

**Comment by ferrari3rider** [comment]
I did not do live trading with Dema or MACD on Binance yet because of the following. I only did 3 day backtesting for example from 01-02-2018 through 04-02-2018. There were 0 trades with the default settings. When I switched some settings randomly, there were also 0 trades like in your introduction video when you were showing backtesting.

Now, that I am observing the command line in Terminal, I see that both methods result in "No Trend" all the time. Maybe I just don't understand what correct settings to input, but I tried many different settings.

**Comment by ferrari3rider** [comment]
Also, I have many logs, but I don't see the one from today's backtesting. But on command line, I see "No Trend" so that's probably the problem. Does it work for you on those days above?

**Comment by ferrari3rider** [comment]
Oh yes, I forgot to add its between BTC - ICX. That's all I tested so far.

**Comment by sparkes25** [comment]
binance stopped trading so they could do a sync to their master system, sites been down for a day or two now. this could be your problem

**Comment by sparkes25** [comment]
i have set my bot to trade on a different site after the binance problems, i have not gone back to binance as yet

**Comment by scragz** [comment]
Keep in mind that MACD is not a normalized value so depending on the current average price you will have to tailor the threshold values, and depending on the coin pair they might need to be several orders of magnitude smaller.

Take a look at the MACD Histogram Momentum Oscillator for the common method of normalizing the value to work across different markets.

@ferrari3rider
