### ISSUE TITLE
Can I change the assets (simulationBalance) during running a strategy?

### ISSUE THREAD

**Issue by jeongmincha** [askmike/gekko#1889]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ v ] question about the decisions made in the repository

* **Action taken** (what you did)

I think the ratio between crypto and real money is very important in executing a trading strategy. Can I change the value of parameters in `simulationBalance` while I'm running a strategy code?

For example, if I needed to buy more BTC after I call `this.advice("long")`, I would want to change the value of `currency` to another number, which means adding more currency to buy.

Can I do this action with your gekko library?
I think this feature will be very useful when I'm doing REAL trading.

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
You can only set the simulationBalance on start.

If you start changing your balance while Gekko is running (either actual or simulated money) Gekko can't track what profit came from your strat and what was an extra deposit. For simulation purposes it doesn't make sense either: it's supposed to measure what happens when you run a strat with X balance, excluding all other outside forces (like you depositing extra money).

Note that the real trader works fine if you start changing the balance while it is running, the only thin that doesn't work is proper profit statistics (for reasons outlined above).

**Comment by askmike** [comment]
If you want to continue the dicussion please do so on the forum: https://forum.gekko.wizb.it/index.php

This is a bug tracker :)
