### ISSUE TITLE
bug report ...

### ISSUE THREAD

**Issue by meidays** [askmike/gekko#1909]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ● ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

binance 1.3.3
https://gist.github.com/askmike/2c4b8e9201c380503ac347ff69c199d5

* **Expected result** (what you hoped would happen)

I think the calculation seems to be wrong.

* **Actual result** (unexpected outcome)

![20180212_072400](https://user-images.githubusercontent.com/36381244/36079465-8675ae04-0fc6-11e8-80b4-5be2890b2161.jpg)

![20180212_073952](https://user-images.githubusercontent.com/36381244/36079640-b9e44e1a-0fc8-11e8-95a2-4ad844533a34.jpg)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
what do you mean with sell timing?

**Comment by meidays** [comment]
@askmike I thought I should sell, but he tried to buy. (Sorry my English is very poor.) ^^

**Comment by askmike** [comment]
> I thought I should sell

Your strategy told Gekko to (try to) sell. Note that Gekko actually didn't sell since you had insufficient funds. Unless you have logs showing that your strategy actually triggered a LONG advice and Gekko still tried to sell I am assuming this is an issue with your strategy (or with your understanding of the strategy).

Please post this here instead: https://forum.gekko.wizb.it/forum-12.html

Since this is the bug tracker for the project (not third party strategies).

Note that it will be very hard to debug the strategy if it doesn't include any logging. People on that forum can help you add that to the strat.

**Comment by meidays** [comment]
@askmike thank you~
