### ISSUE TITLE
[request] smaller candle size (smaller than 1min)

### ISSUE THREAD

**Issue by JoeTeglasi** [askmike/gekko#1930]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I've looked through the docs trying to find out where candleCreator got its "1min" minimum candle size from, hoping that there would be one variable referenced from a config file specifying the length of time in each mini candle (the ones from which 1hr/1day/etc candles are made).

* **Expected result** (what you hoped would happen)
There would be a variable in some config file somewhere that was set to 60000 milliseconds or something like that, which could easily be changed to 10000ms or even 1000ms for smaller candle sizes.

* **Actual result** (unexpected outcome)
the 1min candle size seemed to be hard-coded into the candleCreator, not something that could easily be changed.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I would suggest if someone is familiar with the gekko's internals, that they re-code the candleCreator to operate using a candle size that can be set either from a config file, or even set in just one variable at the top of the page. Maybe using a switch(minCandleSize) statement to determine some of the syntax for the candle start dates and such

**Comment by ortschun** [comment]
I'm guessing this was for performance reasons? How difficult/valuable would it be to support this

**Comment by askmike** [comment]
Hey! There are a few different reasons why the candle is limited to 1 minute, the short story is [here](https://gekko.wizb.it/docs/introduction/scope.html#Market-data). The longer story:

- It makes the whole codebase a lot simpler: throughput is limited (since in most situations you get one tick a minute outside of backtesting). It makes calculating bigger candles (say hourly candles) very lightweight: Gekko stores 1 minute candles on disk, converting those to hourly candles on the fly is not a heavy operation. If Gekko had second candles the performance would look very different for people who want to run over hourly candles. Since if you want second candles in your strategy Gekko can't store minute candles, since than you can't backtest over 1 second candles.
- Since gekko is storing market data to disk, if we store minute candles we are not dealing with a lot of data, but secondly candles would mean up to 60 times bigger storage size. If we were to offer users to configure a small candle size but not store them on disk they are not able to backtest their strategies, at which point I'm not sure why you would even use gekko.
- If you trade on a small timeframe you want more control over execution (how your trades are executed), Gekko doesn't allow you to by design.

The biggest thing though:

Gekko is a platform to create trend watching trading bots, this involves looking at how the price has historically developed and trying to base predicitons of of that. But the smaller your timeframe the more noise and the less reliable the concept of candles work. You can definitely build strategies that trade on shorter timeframes, but you wouldn't use candles:

- You'd use raw trades.
- You'd look at the orderbook since that directly impacts where there is price resistance right now. You'd study things like micro market structures and order flow imbalance.

Even though it sounds similar, it's a very different problem space. And when building strategies that trade on short timeframes you'd build a completely different system in all aspects. (Gekko is 100% based on candles).
