### ISSUE TITLE
[gdax.js] (cancelOrder) returned an irrecoverable error: order not found

### ISSUE THREAD

**Issue by shimanotaka** [askmike/gekko#1999]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Ran Gekko live on GDAX

* **Expected result** (what you hoped would happen)
Successful trading

* **Actual result** (unexpected outcome)
Error that order is not found after repeted attempts to sell.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

After five sell orders (one of them partially filled) I got the following error:

2018-03-06 05:59:27 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2018-03-06 05:59:27 (ERROR):    [gdax.js] (cancelOrder) returned an irrecoverable error: order not found
2018-03-06 05:59:27 (ERROR):    Error cancelling order: [gdax.js] order not found

Could someone explain why this happens and what "irrecoverable" means? Should I enable debug? Does this error mean that I have to restart Gekko to resume trading? After this error Gekko did not attempt to sell the rest of the assets even though the short advice remained active.

**Comment by zappra** [comment]
Yeah I'm getting this too running live on GDAX right now.

I've had a quick look at the code and I can see logic for aggregating multiple trades, but for some reason this is failing, for both buys and sells. What you end up with is a trade notification with a price of zero.

This only happens when the buy/sell is split over multiple trades. Where the trade is filled by a single order, the price is reported correctly.

Happy to take a look but could use some pointers on the logic. GDAX don't support a sandbox environment meaning I'd need to be testing with real money, even if it is the minimum!

**Comment by JoeTeglasi** [comment]
1) I’m pretty sure gdax does have a sandbox api. 

2) I’ve always understood that to mean that the order was either filled and so there was nothing to cancel, or my strat changed it’s mind and advices the opposite and so it was cancelled due to that and due to asynchronous JavaScript the callback for the first cancel order returned last and so didn’t find the order. 

I could be wrong but when I look at my orders on gdax and my CLI log and it looks like everything that’s supposed to happen is happening. But maybe something else is happening with you guys

**Comment by zappra** [comment]
Yep there is a sandbox but I couldn't get it working, and there were reports of it being shutdown. However I've just seen a post on stack overflow reporting it working so I'll try again!

It's definitely not the strat changing it's mind, as I'm triggering the buys/sells via a telegram bot (I haven't taken the training wheels off yet!)

**Comment by shimanotaka** [comment]
Same here, I'm completely sure that Gekko didn't change its advice, since I run a slow and simple strat and about a quarter of the assets were still left in my account.

**Comment by zappra** [comment]
So this looks like the same error as in #1852 

@askmike in a comment you say you know what the issue is, and it's being fixed as part of #1834 

In the meantime, is there a workaround? Or more info?

Thanks :)

**Comment by zappra** [comment]
2018-03-12 17:47:18 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2018-03-12 17:47:18 (ERROR):	[gdax.js] (cancelOrder) returned an irrecoverable error: order not found
2018-03-12 17:47:18 (ERROR):	Error cancelling order: [gdax.js] order not found

**Comment by zappra** [comment]
Seems there are two places you can get this error; with one, the trade will complete but you'll get a zero price reported. With the other, as above, the trade will not complete

**Comment by shimanotaka** [comment]
I got the same error again with debug enabled but it didn't give any more info. This is the second time in a while I get non-filled orders, and the second time I get this error.

**Comment by shimanotaka** [comment]
I've started looking a bit at the code, but I'm quite inexperienced regarding this. Anyway... If the cancelOrder function can't find the order to cancel, why does Gekko stop all trading? Twice now, Gekko adviced short for me, started selling and failing in the middle, leaving partly unsold assets in my account. If Gekko can't find the order to cancel (because it does not exist), shouldn't it check the account balance and resume selling according to the short advice, or react to new advice, instead of seemingly halting all actions?

**Comment by ghost** [comment]
Same error here :( does there are a fix ?

**Comment by JoeTeglasi** [comment]
If you guys want to patch it (not a true fix for the cause, but tells Gekko to keep going as best it can) you can do the following:

In gdax.js,

Where it says:
“
var recoverableErrors = new RegExp(
  /(SOCKETTIMEDOUT|TIMEDOUT|CONNRESET|CONNREFUSED|NOTFOUND|Rate limit exceeded|Response code 5)/
);
“

You can add your error into the list of “recoverable errors”. So just add “|order not found|” in there somewhere. Next time it throws that error, it should keep on running regardless.

**Comment by zappra** [comment]
Yeah I tried that a while back, it just keeps trying to find the order that doesn't exist... forever! There's another changelist knocking around that spoofs the order info if the order can't be found. Do a search for 'gdax' in the issues.

Anyway I've changed gdax to use marketable limit orders for the time being. It means paying the taker fee but I can account for that in backtesting. YMMV obvs but potential market moves whilst waiting for a limit order to fill can far exceed the 0.25% fee.

**Comment by ghost** [comment]
@JThobbyist for me gekko continue to run but it not give me the good price for event.price on onTrade :(
And i really need it for my strategy.
Hope a fix soon because on gdax 0% fees on btc/eur ...

**Comment by JoeTeglasi** [comment]
yeah that issue was really annoying. To work around it, I made a module that basically has my gdax authedClient and uses fibers and futures to synchronously check if a trade occurred by checking of the state of my portfolio is different from its last state (like if the last time it checked my portfolio was {$20 and 0 ETH}, and then it checks again (on the next candle) and my portfolio is {$0 and 0.04 ETH} then it lets my strategy know not only that a trade happened, but also it tells it the price at which the trade occurred (in the example, the price would be calculated as $20/0.04ETH = $500/ETH). Thanks to the fibers/futures, I don’t let my strategy give any more advice until that synchronous code has finished and it knows if any trades recently happened. It only takes a couple seconds for it to send the requests and get the response so even with 1min candles it doesn’t miss anything.

**Comment by shimanotaka** [comment]
@JThobbyist, Any chance that you could share your solution or make a PR out of it?
@askmike, I know you have a lot of other things on your mind but is there any chance for a fix for this? Gekko is more or less unusable for me, because almost every time it initiates a trade it crashes.

**Comment by zappra** [comment]
The solution I've got is to create an immediate callback when an order is placed that will check for rejected order status. I think what happens [see also #2067] is the price moves and the order is rejected. This works just fine but there's been no response from @askmike on this or any related issue, plus I don't know if my change will merge against recent commits.

In the meantime you could try using post_only=false, or using market orders

**Comment by askmike** [comment]
fixed in 0.6! Please update your gekko!
