### ISSUE TITLE
Adding bitmex exchange to gekko

### ISSUE THREAD

**Issue by sanjucta** [askmike/gekko#2007]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X ] question about the decisions made in the repository

* **Action taken** (what you did)
 I'm trying to add the bitmex exchange to my gekko installation. 

* **Expected result** (what you hoped would happen)
When I run gekko in realtime mode (node gekko --config config.js) , the trades should be processed

* **Actual result** (unexpected outcome)

'No new Trades' is printed on the console

* **Other information** 

The public trade method for bitmex does not return a numeric trade id .  {
    "timestamp": "2018-03-06T18:27:17.612Z",
    "symbol": "string",
    "side": "string",
    "size": 0,
    "price": 0,
    "tickDirection": "string",
    "trdMatchID": "string",
    "grossValue": 0,
    "homeNotional": 0,
    "foreignNotional": 0
  }  However, the getTrades method in the exchange class is expected to return a numeric trade id. I could maintain a trade id  myself (in a local database, for example) that I keep updating , but I was wondering if there is a better way to do this in gekko itself

**Comment by askmike** [comment]
Besides from your issue it is hard to add bitmex to Gekko:

Bitmex is not a spot exchange, instead orders end up representing a position. Depending on the product you might pay interest on your position (depending on the basis). Making money depends on if the price moves with or against your position, as such calculating PnL is very different. So even if gekko can fetch market data, there isn't much we can properly do with yet since Gekko does not support margin trading calculations.

**Comment by askmike** [comment]
As for your specific issue:

you can convert their timestamp to ms (or even microsecond) and use that as an id.

As for the complete story, closing this as a dup of #1331.

**Comment by sanjucta** [comment]
Thanks for the clarification !
