### ISSUE TITLE
resign Warmup Period through downloading historical Data

### ISSUE THREAD

**Issue by nimasTT** [askmike/gekko#2009]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ X] feature request
[ ] question about the decisions made in the repository

It would be great if gekko downloads the needed historical data (f.e. for sma long) from the Exchange Server. It would speed up Live Trading and make it easy to optimize strategy parameters almost on the fly.

**Comment by askmike** [comment]
Very open to a PR for this!

Note that only some exchanges expose historical data.

**Comment by nimasTT** [comment]
Because of me. All sources that we can use for backtesting. are pretty much :)
I use BitFinex and Binance for trading.
After some time I try to recalibrate my strategy with the help of japonicus. (for example during ralley or sideways trends)
For backtesting, I have to download historical data that I've already collected in live trading.
After the optimization, I have to restart and wait to gather enough data for sma long. This, in turn, is the same data I used during the backtest except for a small delta.
I think all needed parts are already implemented in Gekko.

**Comment by JoeTeglasi** [comment]
I run a market watcher (via the UI, since it’s convenient), and then I set my config.candleWriter.enabled = false. Then I use the importer in the UI to get the candles for the last day (or however long I need, but it has a 1-day import minimum). It usually takes about 5-10 min to get all the data I need, and since the market watcher is running, my database is up-to-date and my strat can be seeded with all the recent historical data without having to wait a long time

**Comment by JoeTeglasi** [comment]
It would be cool though if Gekko could take care of all that automatically

**Comment by donkykong017** [comment]
i try this a well. tried to put the config.candleWriter.enabled in the strat. but it also just uses the date only from the marketwatcher not the import. how can we tell the strat that it should use all the data.

**Comment by JoeTeglasi** [comment]
Did you wait for the import to finish?

**Comment by donkykong017** [comment]
yes had all the strat needs. market watcher running and historical data plenty available. have to say  i run everything in webUI.  would love to put that in gekko but have no idea where to start

edit: in the strat log it does not say that it needs more data but in the ui it says using e.g 30 mins of data, which is not enough

**Comment by JoeTeglasi** [comment]
I’m not sure why it’s not working on the UI, but I suspect that the config that the UI uses is different than the config that you fill out for the CLI, and I’d bet that it’s because you’re running your live Gekko on the UI. I’d look into running your live gekkos via the CLI. It doesn’t take long to learn how to do it, and they walk you through how to do it in the docs.

**Comment by donkykong017** [comment]
yeah thought about looking into CLI. maybe i will this weekend when i have the time. should have started with CLI from the start. but there has to be some way to get that in the UI as well. just have not found the missing link and i have to say im pretty much a noob still. but eager to learn

from what i know, the UI uses at least to running gekkos (child processes). if it works for the CLI there has to be a way. just dont have the needed knowledge how the CLI gekko works, for now

**Comment by askmike** [comment]
> I’m not sure why it’s not working on the UI, but I suspect that the config that the UI uses is different than the config that you fill out for the CLI, and I’d bet that it’s because you’re running your live Gekko on the UI. I’d look into running your live gekkos via the CLI. It doesn’t take long to learn how to do it, and they walk you through how to do it in the docs.

The reason is that Gekko uses a different architecture in the UI: when you run a paper trader on bitfinex usd/btc it will actually start two processes: one that fetches market data (called the market watcher) and one that runs the strategy (called the strat runner). The idea is that you can run 5 paper traders on bitfinex usd/btc without getting rate limited because you are fetching the same data 5 times.
