### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by lqtacy** [askmike/gekko#2011]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_BUSY: database is locked
RECEIVED ERROR IN GEKKO 5773123979696666
Child process has died.

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Poloniex Btc/Other coins live and paper trader

**Comment by JoeTeglasi** [comment]
I’ve received that error when multiple gekkos were trying to write the candles for the same currency pair on the same exchange at the same time. Like I had a market watcher running via the UI, and had a live Gekko running via the CLI. I needed to change the plugin settings for the live Gekko as follows:

config.candleWriter = {enabled: false}

That fixed this issue for me. I think it was because they were both trying to write to the same database at the same time and that throws an SQLite error
