### ISSUE TITLE
when a ORDER is REJECTED on GDAX after an advice gekko stop making order

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#2067]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I have start the develop version of gekko live.
After an advice gekko made an order but it was rejected.
After the rejected order gekko stop making new orders :(

**Expected result** (what you hoped would happen)
I was expecting than gekko continue to buy.

**Actual result** (unexpected outcome)
gekko has made a buy order.
The order has been rejected.
Nothing has been bought and gekko stop to make orders :(

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Enabling "Post Only" when creating a limit order will ensure that your limit order is posted to the order book and sits on the order book to be charged a Maker Fees if it is filled. If any part of the order would execute immediately due to its price when arriving at the matching engine, the entire order will be rejected. This is useful for ensuring that an order is not subject to Taker Fees, if desired.

**Comment by ghost** [comment]
I think when the order is rejected, gekko think the order has been filled.
Maybe a simple fixe will be to check if balance has been change and if gekko can make a new order like one minute later.
I m not enough good in js to make a bug fix but it will great to have one because in my case it was for a buy order but if it s happen in a short advice and gekko not sell and btc dump it will be more problematic.

**Comment by ghost** [comment]
Seems post_only: true produce sometime rejected order which stop buying or selling because gekko live think the order has been filled :(
I want use gdax because 0% fees but it seems it s not work when gekko make an order which match with the market :( with post_only: true
If someone can have a look it will be great, thanks.

**Comment by zappra** [comment]
Unfortunately Gekko doesn't check if an order has been placed successfully on the exchange. The checkOrder callback can only report if an order has been filled or not. I think there either needs to be an overhaul to the checkOrder function in order to report an exchange agnostic order state, or there needs to be another check function - eg. checkOrderPlaced that will report if the order has been placed successfully on the exchange. If it has, then the normal checkOrder flow can begin, otherwise the trade can be retried. I am assuming the reason that the order is rejected is that the market is in a state with a narrow spread and the price had moved, putting the limit price on the wrong side of the order book, in which case retrying the trade should see the order placed successfully.

This is non-trivial as it would mean touching the code for all exchanges!

@askmike does this sound about right?

@yepla you could try post_only: false I think, if I understand correctly it would mean you paid taker fees once in a while

**Comment by ghost** [comment]
@zappra if i use gdax it s for not pay fees so i don t want use post_only: false. But actually it s the only way to trade on gdax :(

**Comment by zappra** [comment]
Also #1999 - order not found

I've been testing on the sandbox and by deliberately placing marketable limit orders with post_only set to true I can easily repro the "order not found" issue. I guess by the time (1 minute) gekko comes to perform the checkOrder the order has been deleted on the exchange?

**Comment by ghost** [comment]
@zappra in my case when gekko have made the order the order has match with the sell so gekko has think it s has been bought but in fact it was rejected
