### ISSUE TITLE
Multiple Gekko streams

### ISSUE THREAD

**Issue by positonic** [askmike/gekko#2079]
**I'm submitting a ...**
[ ] bug report
[x ] question about the decisions made in the repository

Just a quick architecture question, @askmike you mentioned that you use Redis Beacon and multiple gekkos, I was wondering if there was a specific reason you went that way instead of creating several Gekko streams?

The idea being to be able to run Gekko on many markets (coins) and exchanges. I thought to ask about multiple Gekko streams, before I put a load of effort into trying it out, just in case you had any warnings?

**Comment by askmike** [comment]
Could you explain a bit more what you mean? If you run two gekkos (one on bitstamp and one on bitfinex) you effectively have 2 different gekkostreams, they are both wrapped in a node process.

**Comment by positonic** [comment]
I mean rather than running 2 gekko processes (one on bitstamp and one on bitfinex), you have a single process that spawns 2 or gekko streams from within a single instance of Gekko. 

A Gekko appears to consist of the candles stream coming in and that feeds into the plugins. 

I'm talking about doing this for more than one set of candles at a time on a single Gekko. 

So for each market do what is currently done, but without having to spawn multiple Gekkos.

This means that the streams can be self aware and managed from within the instance rather than in seperate processes, unaware and have to commuicate with Redis. 

I hope I'm making sense :)

**Comment by askmike** [comment]
Ah I see what you mean, the biggest problem is that all plugins (modules inside gekko that do something with market data such as the trader, stratrunner, etc) only work with a single market.

There is an interface in how plugins get data (from both market and other plugins), the current version is here: https://gekko.wizb.it/docs/extending/add_a_plugin.html#What-kind-of-events-can-I-listen-to- and I am working on a new one as part of 0.6, see here: https://github.com/askmike/gekko/blob/8e2760a3cf0ab4b4d30506930d51368a261f3f16/docs/internals/events.md That interface is designed for a single market, and all events being deterministic outputs of that same single market.

----

> This means that the streams can be self aware and managed from within the instance rather than in seperate processes, unaware and have to commuicate with Redis.

So the main reason you want this is that you still want to have gekkostreams (sets of plugins) that interact with a single market, but you want to make it easier for them to talk to eachother? What type of communication do you want to do between them?

Note that the UI uses IPC communication when you start a gekko via the UI (the UI is the main process, it starts child processes that actually do all the work). I only use redis to scale that kind of stuff up.

**Comment by positonic** [comment]
@askmike the main aim it to use an overall strategy that takes into consideration position sizing across markets. I'm aware of the direction the [trade class is going](https://github.com/askmike/gekko/pull/1968), and this will eventually lead to position sizing and multiple strategies on each market, but I would like to apply position sizing across many markets.

I know Redis beacon may be an option. With a single dedicated Gekko or otherwise responsible for all trades. Are you still using this approach? Is Redis currently working in Gekko?

**Comment by askmike** [comment]
> @askmike the main aim it to use an overall strategy that takes into consideration position sizing across markets.

So to take a step back:

- Most complex trading systems use a more advanced trading strategies, portfolio and execution manager: Gekko is setup to be a simple starting point: Everything is build around the simple idea of buying/selling a single asset in a single market. Not just the gekko streams but also:

- the trading strategy is designed to consume from a single market:
  - the strategies people build around the strategy lifecycle (init method with defining indicators, update and check method for consuming new market data).
  - gekko's wrapping code to make it all work (calculate indicators - possible async, batch 1min candles, pass around events)
- there is no portfolio manager (in the traditional sense): when the strategy triggers a signal this is translated into a trade (long becomes a simple buy, short becomes a simple sell) on that same market. Usually you have a few layers between your alpha model deciding what to do AND some other model determining what kind of position to take based on output of the alpha AND a final model that figures out how to do to the actual execution most effectively.
- the performance analyzer is quite simple: it only really deals with one market and everything happening there.

> I know Redis beacon may be an option. With a single dedicated Gekko or otherwise responsible for all trades. Are you still using this approach? Is Redis currently working in Gekko?

I'd suggest we first take a step back and thing about what kind of system you want to build:

Gekko is a very simple framework to build simple automated strategies that work on a single market (with very limited execution models). Most more complex trading systems consist of a bunch of different parts:

- alpha model (determine how to generate profit)
- risk model (determine how to shield from potential risk)
- transaction cost model (if the 2 above determine you need some kind of exposure to X, how to go about it?)
- portfolio model (based on the above, what kind of "portfolio" should you hold)
- execution model (how to most effective time/price wise go about getting from the current portfolio to the new one?)

*(See inside the black box: https://www.amazon.com/Inside-Black-Box-Quantitative-Trading/dp/1480590061 for a good starter on more complex systems)*

Gekko skips most of those, it only focusses on the alpha (and risk model if you want, but that's baked into the strategy). Instead of focusing on how to get multiple markets in current gekko, maybe think about what kind of system you want to build, for example:

If you have a multiple markets, how do you deal with your strategy saying you should buy USD/ETH and buy USD/BTC (which one to actually buy, or both?), etc. etc.

**Comment by askmike** [comment]
May I request we move the discussion to the forum? https://forum.gekko.wizb.it/forum-21.html Before we can talk code we need to figure out what we want the system to do. I think the forum is a better place for that. Thanks :)
