### ISSUE TITLE
Digital Ocean VPS connection problem

### ISSUE THREAD

**Issue by gamacoin2017** [askmike/gekko#2100]
Hi,
I can't open http://46.101.84.246:3000/
It's stucking like this.

![image](https://user-images.githubusercontent.com/33009826/38620209-9da63658-3da6-11e8-8e4c-f0b8a677f542.png)

My UIconfig.js file

const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: 3000,
  },
  ui: {
    ssl: false,
    host: '46.101.84.246',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by gamacoin2017** [comment]
help please

**Comment by ghost** [comment]
api host: '127.0.0.1'
api port: 3000
####
ui host: '46.101.84.246'
ui port: 443

And you need install nginx
All it s explain here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html
If your port 443 just change 443 by an other number in the UIconfig.js and in the nginx config ...

**Comment by SirTificate** [comment]
You did not open port 3000 in your firewall, hence you can't access the GUI/API directly. 
Furthermore it's not a good idea to make Gekko directly accessable on a public server. You should put a reverse proxy like nginx in front of it (like yepla suggested) and enable basic authentication. You'll have to open port 80 (and 443 when using TLS/SSL) in the firewall. Otherwise you won't get anywhere.
If you don't know how to set this up, Gekko might not be the right tool for you.
