### ISSUE TITLE
Margin trading (bitfinex... )

### ISSUE THREAD

**Issue by elcerqua** [askmike/gekko#2154]
Hi, does anybody knows how to set the gekko trading bot on bitfinex margin trading?
Thanks

**Comment by mmvasa** [comment]
Hi ! I'm currently working on it: https://github.com/martinvasapollo/gekko
The change is a little bit disrruptive, because now your strategy should advice long, short and close.
e.g: this.advice('long');
This advice will close your margin position, short or long.
If you not close between short and long, it will have not effect because there is no money for the second operation.
Feel free to ask me about anything.

**Comment by askmike** [comment]
It's not supported, read here why: https://forum.gekko.wizb.it/thread-1516-post-57452.html#pid57452

**Comment by sahilnanda1995** [comment]
Hi @martinvasapollo 
I was looking for ways to do margin trading on gekko. Can you share a sample strategy using long, short and close so that i can have a better understanding on how to write a strategy with your code.

Thanks!!
