### ISSUE TITLE
DEMA strategy results

### ISSUE THREAD

**Issue by Luke2407** [askmike/gekko#2225]
I'm submitting a ...
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
DEMA strategy in Gekko v0.5.13 or v0.5.14 provides wrong results.

**Expected result** (what you hoped would happen)
Correct results for DEMA strategy are obtained in Gekko v0.5.12.

**Actual result** (unexpected outcome)
Buy and sell points in Gekko v0.5.13 or v0.5.14 disagree to the ones obtained with Gekko v0.5.12 (same data)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Gekko v0.5.12-v0.5.13-v0.5.14
Node v8.11.2

**Comment by ptdev** [comment]
Having just started using gekko about a month ago, I also had some issues with the DEMA indicator.

I think the main issue I had was that the DEMA indicator is [used as an example](https://gekko.wizb.it/docs/strategies/example_strategies.html#DEMA) on Gekko's website, then goes on to describe it as an [implementation of Goomboo's strategy from bitcointalk](https://bitcointalk.org/index.php?topic=60501.0)  

The problem is that Goomboo's strategy isn't really DEMA but instead it's just 2 basic EMA's with different periods and trading signals on the crossovers.
[Real DEMA](https://www.investopedia.com/articles/trading/10/double-exponential-moving-average.asp) is a different indicator that has its particular formula and according to its author it is described as:  

> "the DEMA is not just a double EMA with twice the lag time of a single EMA, but is a composite implementation of single and double EMAs producing another EMA with less lag than either of the original two." In other words, the DEMA is not simply two EMAs combined, or a moving average of a moving average, but it is a calculation of both single and double EMAs.

@askmike then [posted a bounty on Gekko's forum](https://forum.gekko.wizb.it/thread-93.html) in order to have the DEMA indicator fixed, [which it was](https://github.com/askmike/gekko/pull/1822).

I still think Gekko's website should have the DEMA example fixed, either to provide a correct description of the indicator, or changing the DEMA example with another that actually does what Goomboo describes. (but in order to avoid confusion, instead of DEMA, maybe call it Dual-EMA or something like that)

**Comment by askmike** [comment]
Very open to a PR for this!
