### ISSUE TITLE
installed gekko but now cannot get started can anyone PLEASE help

### ISSUE THREAD

**Issue by brownbag26** [askmike/gekko#2228]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by ptdev** [comment]
I see this is your first Github issue ever.

And it shows because your issue has absolutely no information about the actual problem. You didn't even fill in the bug report fields. How are people supposed to know what issue exactly you are having?

All your post states is: "it doesn't work, please help". No context, no error messages, no logs, nothing.

So I doubt you'll get any sort of useful reply and this issue will probably get closed.

To get any help you'll need to thoroughly describe your problem, any errors you're getting, what you've tried, etc.
Still, Gekko works. So I'm guessing your actual issue is that you can't install it due to some other problem. That means that your issue is not really a Gekko issue but more of a support/help request, so you should try asking for help at [the forum](https://forum.gekko.wizb.it/) since github issues should really be reserved to actual bugs in the software and not for installation help requests.

**Comment by askmike** [comment]
@ptdev is exactly right!
