### ISSUE TITLE
events.js:183        ever since the update in ubuntu.  fix windows killed ubuntu with update?

### ISSUE THREAD

**Issue by Hackertalkz** [askmike/gekko#2237]
Gekko v0.5.14
	I'm gonna make you rich, Bud Fox. 

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by Hackertalkz** [comment]
how do you read the errors?

I am assuming it is a file called "events.js" and it is line 183 thats throwing the error
to not allow node gekko --ui to load.  But I dont see a file called events.js
unless it is located in the module folder somewhere??

**Comment by Hackertalkz** [comment]
and if this is the case, I did find a file called events.js
But one file named this was located in directory:
gekko/web/vue/node_modules/events.js
and line 182 & 183 read...
  if (!this._events || !this._events[type])
    return this;
and the second file named events.js was located in node_modules/coingi/node_modules/mocha/lib/browser
**and around the code 183 was these lines...**
var args = Array.prototype.slice.call(arguments, 1);

  if (typeof handler === 'function') {
    handler.apply(this, args);
  } else if (isArray(handler)) {
    var listeners = handler.slice();

    for (var i = 0, l = listeners.length; i < l; i++) {
      listeners[i].apply(this, args);
    }
  } else {
    return false;
  }

  return true;
};

so I am assuming the problem is  is here actually...  since this deals with the browser???
I am new to programming...  took classes 10 years ago.  But still learning.  Is this where I need to look and backtrack the issue??

**Comment by jmcklondonuk** [comment]
Hi, 
"Error: listen EADDRINUSE 127.0.0.1:3000." is the cause of your issue. It means port 3000 is already in use, hence the app cannot start. As a super user, run "netstat -anp | less" (without quotes) and you will see running processes and their port number. Look for 3000 to see which process occupies that port.

Once you know the process, kill it, i.e. "killall processName". 
If it doesn't help, describe the steps to reproduce this issue incl. your command that runs Gekko. 

Regarding the file that is throwing the error, it is deliberately thrown as an unhandled exception because when the port is occupied the app cannot continue. It has to terminate with an error message.

**Comment by askmike** [comment]
@jmcklondonuk is correct, this is not an issue with Gekko!

**Comment by CHAMOD** [comment]
You should check whether your 3000 port is currently used. it then you should kill that process.
