### ISSUE TITLE
Backtest impossible when trader is enabled (and no paper trader)

### ISSUE THREAD

**Issue by mark-sch** [askmike/gekko#2303]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Perform a backtest, trader enabled and paper trader disabled in config.

**Expected result** (what you hoped would happen)
Peform a backtest

**Actual result** (unexpected outcome)
3x times error in console: Performance Analyzer wanted to listen to the undefined, however the  is disabled.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
The workaround is to enable to paper trader (and trader) while in backtest mode - then it completes fine. But this config with both traders enabled will not work in realtime mode (and should not of course).

**Comment by askmike** [comment]
Do you encounter this in the UI or using the CLI interface?

**Comment by mark-sch** [comment]
Yes, this happens with CLI version (right now I am not using UI anymore).

**Comment by askmike** [comment]
The CLI interface is a bit lower level: you do need to manually configure all plugins you intend to run. And the trader (live trading plugin) is not supported when doing backtests (to step gekko from doing actual orders based on backtest advice).

To work around your issue, it's best to use different config files for each gekko instance, you basically have 3 options:

1. use 1 file and edit it every time just before you run the Gekko (which you call the workaround). Since the config is only imported once and kept in memory for as long as the gekko runs.
2. copy your main config file into another file and switch the trading plugin here.
3. create a new js file where you import your main config file and overwrite the plugin settings, example:

```
const config = require('main-config.js');

config.trader.enabled = fales;
config.paperRrader.enabled = true;

// whatever else you want to change

module.exports = config;
```
I don't really consider this is a bug, since the CLI interace (and config file) is supposed to be very low level. And I don't want Gekko to go and enable plugins you did not enable yourself. But if you have other ideas I am all open, first thing would be better documentation around this stuff.

**Comment by mark-sch** [comment]
I like your third approach with config import.

The problem is, Gekko will run backtest mode without the paper trader enabled, gives lot of debug output, but never returns a backtest result. I think most users do not know what to do.

I have commited two small changes to inform the user and prevent misconfigured runs:

In backtest.js:
if(!config.paperTrader.enabled)
  util.die('You need to enable the \"Paper Trader\" first to run a backtest.')

In trader.js:
if(config.trader.enabled && config.paperTrader.enabled) {
  //this can only happen in realtime mode - during backtest the trader is disabled by design
  util.die('You can not run Gekko in realtime mode with both \"Paper Trader\" AND \"Trader\" enabled.')
}

**Comment by askmike** [comment]
I think your second case is already catched by gekko (in core/pipeline.js)
a little bit more abstractly: if there are 2 plugins that emit the same
event gekko won't run. I remember testing this in 0.6, but might need to
recheck.

As for your first case: it's not really documented, but a lot of people use
the backtesting mode for a lot more. For example for quickly writing
candles to disk or importing from 1 DB to another. As the backtesting mode
will read candles from the DB as fast as whatever plugins can consume them.
We can definitely put a warning in there, but not stop the process.
