### ISSUE TITLE
[KRAKEN] Warning: exchange did not provide fee information

### ISSUE THREAD

**Issue by jeroenve86** [askmike/gekko#2336]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Live Tradebot to Kraken exchange shows a warning in the tradebot log file that the exchange did not provide any information on the fee amount per each trade.

**Expected result** (what you hoped would happen)
The fee amount was correctly taken into account by Gekko

**Actual result** (unexpected outcome)
The fee amount did not pass correctly from Kraken towards Gekko

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I noticed on a live tradebot with Kraken account the fees are not correctly taken into account. The log file states information on the fee amount is missing, and assumes (incorrectly) no fees. Is this a known issue with the Kraken exchange? Or something which needs configuration on my end in Gekko?

**Comment by askmike** [comment]
I have recently released a major Gekko upgrade with a completely reworked exchange integration (with a library called [Gekko Broker](https://gekko.wizb.it/docs/gekko-broker/introduction.html)).

While this library is already a lot more stable than how Gekko previously dealt with exchange integration, there are still some kinks like this one.

**What does warning means**

It simply means that since Gekko was unable to properly track fees paid it is unable to accurately calculate your profits. This does NOT impact trading behaviour, since your strategy does not take fee information (or anything else related to execution) into account.

I'll keep this issue open until we fix.

**Fixing this**

The reason for this problem is because in my local integration tests (using my own Kraken account), Kraken reports fees of 0. See here:

https://github.com/askmike/gekko/blob/7be6bcce8db4a81b3a7cf88ff9691730767f800c/exchange/wrappers/kraken.js#L217-L236

We need to figure out if that has to my with my kraken account or if I am not calling the API correctly, etc.
