### ISSUE TITLE
Gekko UI layout on mobile

### ISSUE THREAD

**Issue by nicolasbonnici** [askmike/gekko#2347]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Open the UI on any mobile browser or even in chrome devtool. 

**Expected result** (what you hoped would happen)
The whole layout, header menu and graph to be responsive. 

**Actual result** (unexpected outcome)
The menu and the graph appear inside a small width div. 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

This bug occur on the last stable release using Gekko v0.6.2 and Gekko UI v0.2.2.

**Comment by askmike** [comment]
Hey! Thanks for the report.

> This bug occur on the last stable release using Gekko v0.6.2 and Gekko UI v0.2.2.

Note that last stable is 0.6.3, but unfortunately nothing has changed regarding a responsive layout.

----

Two things:

1. The current UI is very old and I am already working on a new one, see this forum post for [more info](https://forum.gekko.wizb.it/thread-1429-post-58996.html#pid58996). I don't want to put a lot of time into making this one responsive while also working on the new one.
2. The Gekko UI currently serves three different purposes: A) experiment using strategies with different parameters (backtest) B) create and manage gekko trading bots C) look at how your gekko trading bots are doing.

Does it make sense to do all these things on mobile?

- A maybe, but very hard (evaluating a backtest requires you to look at a lot of datapoints and look closely at graphs)
- B definitely not IMO: Gekko will manage your money, we don't want users to fat finger a setting and lose money because of it.
- C that would be awesome.

As such just squeezing down a desktop UI so it fits on a mobile will be a terrible experience for everyone. Instead we need to think about what makes sense in a mobile context and go from there.

-----

This is a technical bug tracker, am I am trying (and failing) to keep it a bit clean and bug.tech focussed. Let continue the discussion on the forum!
