### ISSUE TITLE
Backtesting VS Reality 

### ISSUE THREAD

**Issue by DevCode01** [askmike/gekko#2375]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Hi !
Recently I create a Gekko strategy (+500% per month with simulation). 
But when I realize a backtesting of data (BNB/OST) for a period of one day (25/07/14 - 26/07/14), I realized that I could increase my earnings by 10%. But that same day by launching my tradebot, I lost 5% of my stake. Why such discrepancies between backtesting and reality? Especially since Gekko is installed on a Raspberry connected by Ethernet .. Thanks in advance!

**Comment by askmike** [comment]
You can tweak the paper trader to better simulate exeuctions. Especially in very illiquid markets like the one you describe, here is some documentation on it: https://gekko.wizb.it/docs/features/backtesting.html#Simplified-simulation

Gekko had to make a choice between a very accurate simulation which requires a lot of very hard to get data (orderbook data) or require little data for a default simulation which works pretty reliable for bigger markets but requires tweaking (to spread and slippage) for smaller ones like the one you tested.

Since many people are asking questions about this I'll try to explain this better in the UI (besides just the docs).
