### ISSUE TITLE
Importer Not Showing Exchanges - Error

### ISSUE THREAD

**Issue by smokenmirrors2** [askmike/gekko#2376]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Went to importer, http://localhost:3000/#/data/importer

**Expected result** (what you hoped would happen)
Selecting an exchange to import from

**Actual result** (unexpected outcome)
No exchanges available

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

In dev console, the following error appears:
`VM99 chunk-vendors.f8e19183.js:7 TypeError: Cannot read property 'markets' of undefined
    at a.currencies (VM100 app.9aa8dda3.js:1)
    at un.Kw5r.un.get (VM99 chunk-vendors.f8e19183.js:7)
    at un.Kw5r.un.evaluate (VM99 chunk-vendors.f8e19183.js:7)
    at a.currencies (VM99 chunk-vendors.f8e19183.js:7)
    at a.n (VM100 app.9aa8dda3.js:1)
    at a.t._render (VM99 chunk-vendors.f8e19183.js:7)
    at a.r (VM99 chunk-vendors.f8e19183.js:7)
    at un.Kw5r.un.get (VM99 chunk-vendors.f8e19183.js:7)
    at un.Kw5r.un.run (VM99 chunk-vendors.f8e19183.js:7)
    at tn (VM99 chunk-vendors.f8e19183.js:7)`

**Comment by askmike** [comment]
Seems like you did not install Gekko Broker dependencies, read here: https://gekko.wizb.it/docs/installation/installing_gekko.html#Installing-Gekko-39-s-dependencies

If that doesn't solve it please comment here and I'll reopen.

**Comment by mbartyzel** [comment]
It didn't help.

**Comment by terabyte84** [comment]
I've performed complete installation (Gekko Broker dependencies too), but list is still empty.

**Comment by theunknownX** [comment]
Same here

![image](https://user-images.githubusercontent.com/53580690/62320813-81af6280-b4a1-11e9-978d-c17afa467239.png)

![image](https://user-images.githubusercontent.com/53580690/62320858-9b50aa00-b4a1-11e9-9c83-4f35a65bf5e9.png)

**Comment by oalansilva** [comment]
I have the same problem.
Does anyone have any ideas?
I'm running on Windows

**Comment by PGTBoos** [comment]
There is something wrong with the windows package.
I had installed at first in virtual box on linux  ( i planned to buy a cheap linux box for it).
The linux version worked OK.
So then i was thinking its all executed by nodejs so, it should work in both versions.
But as it didnt something wasnt right, in the installers.

So I renamed (windows) g:\gekko to g:\gekoo-broken 
Inside my virtualbox i zipped the gekko folder
And then i made another directory for the gekko folder on Windows to unzip that.

initially, that gave errors about SQLite, reinstall through npm failed.
Then i downloaded Winmerge, I checked for folder and file differences, and yes there where a lot of differences.

Most notably in the "G:\Gekko-broken\node_modules", turns out each module had original file path's included, so i copied from windows install Gekko-broken, over the G:\gekko linux dir.
After that the loader page worked fine and it is now (just finished) importing, 

Still keeping my fingers crossed not sure if this is all. (as essentially i now use the gekko folder that was on linux, on winsdows), and i'm not sure if thats ok.. i'm just thinking its nodejs who executes so... 

but it might go wrong on other libraries perhaps 
Well at least so far the buildin indicator macd worked.
I plan to use this windows gekko only for strategy development, eventually i'll hand those over to my linux PC, so since paper trader works its now fine to me  (but this could still be broken on other parts).

I hope this helps, one might also install it using virtualbox, or docker

**Comment by scottie** [comment]
reopen ?

**Comment by criptohelios** [comment]
I am having the same issue with Linux Mint and Ubuntu. Gekko starts running but when you go to import data it does not show the exchangers, neither the pairs, I got the same as @theunknownX .
This is the error i am getting:

![image](https://user-images.githubusercontent.com/59773237/72208089-27c6b600-349f-11ea-9366-a5a0eeca6e84.png)
Any idea how to solve it? I did do npm install --only=production in both folders, /gekkko and /gekko/exchanger

**Comment by criptohelios** [comment]
I think it is finally working, i downgrade the nodejs to 8.17.0, the other 2 newer versions didnt seems to work, neither the 10x or 12x in theory the 2 newer LTS versions.

taking from the repository:

Installing nodejs

Gekko requires nodejs to be installed. Go ahead and install this if it's not already (Gekko requires at least version 8.11.2). We advice to download the current LTS.

so i took the latest -lts version, didnt work
