### ISSUE TITLE
[Gekko Broker] limit order is broken

### ISSUE THREAD

**Issue by PaulGuo** [askmike/gekko#2398]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Code**

```
class LimitOrder extends BaseOrder {
  constructor(api) {
    super(api);
  }

  create(side, amount, params) {
    this.side = side;

    this.postOnly = params.postOnly;

    this.status = states.SUBMITTED;
    this.emitStatus();

    this.createOrder(price, amount);
  }

  createOrder(price, amount) {
    this.amount = this.api.roundAmount(amount);
    this.price = this.api.roundPrice(price);
```

**File Path**

`exchange/orders/limit.js`

**Action taken** (what you did)

while `.createOrder` method has been called, `price` always has no value. Because `price` never been declared inner `.create` function.

**Comment by askmike** [comment]
Ahhh yea I should have NOT pushed the limit order to github, apologies.

Context: Gekko Broker is a library to do advanced (and normal) orders, however only the sticky order is actually working and hooked up right now.

Mostly because I am super busy and (for now) the sticky order is the only order type used by Gekko (for now).

Feel free to propose a PR that does one of the following:

1. fixes the current limit order (note: the base "order" class is a bit of a mess)
2. adds a comment in the code noting that it's not working.
3. removes the code alltogether.

Else I will do 3. at some point (until it's fixed).

**Comment by askmike** [comment]
I went for option 2 for now, so that anyone else can easily pick up 1 (without having to look to far for the current code).
