### ISSUE TITLE
(INFO): NOT selling, already no exposure

### ISSUE THREAD

**Issue by genesiscrew** [askmike/gekko#2432]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[tick ] question about the decisions made in the repository

**Action taken** (what you did)
i ran the live trader and a sell signal arrived.

**Expected result** (what you hoped would happen)
I expected to sell.

**Actual result** (unexpected outcome)
it did not sell

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
 here is the output of console:

2018-08-11 17:45:57 (DEBUG):	Price = 0.01875, Prediction = 0.010593008869813203
entering sell trade
2018-08-11 17:45:57 (INFO):	NOT selling, already no exposure

**Comment by genesiscrew** [comment]
just like to clarify that this is not a bug, but i just like understand the logic behind why it wont sell unless there is exposure, can someone explain what is the purpose of the exposure variable?
Thanks

**Comment by askmike** [comment]
Great question! If other questions like this pop up please use [the forum](https://forum.gekko.wizb.it/) next time. It's archived better on google and other people with the same question might find it easier.

It might make sense to check out this video, I'll go over the basics of some gekko concepts: https://youtu.be/PKIxZ-Qaphk?t=2m48s

To answer your question:

> (INFO): NOT selling, already no exposure

Means that your strat signalled a sell, however there is nothing (or not enough) to sell since all/most of your money is already in your base currency (USD in case of BTC/USD).
