### ISSUE TITLE
MACD  reports 0 activity (Kraken dataset XLM/USD)

### ISSUE THREAD

**Issue by mutenroch** [askmike/gekko#2456]
Hello¡
just installed, first trials on default strats with default settings.
Every strat reports activity but MACD. It reports 0 (fictionall) trades. Both with defaults and custom settings.
Used three month, kraken, xlm-usd dataset.
would it be a bug? I'm worried about integrating MACD with other indicators if it is not working (can't see the supossed/expected bug by myself)
thanks¡

**Comment by askmike** [comment]
Would you mind posting something we can reproduce this with? For example what strategy you tried and some market data (from history folder). That way we can reproduce and have a look at your exact situation.

**Comment by mutenroch** [comment]
Sure, sorry.
Used MACD strat with default settings, with different candle size and warm-up periods.
Attached will find binance data from history folder and some screen shots.

thanks¡


[history.zip](https://github.com/askmike/gekko/files/2300282/history.zip)
![macd res](https://user-images.githubusercontent.com/10659481/44308421-eddea680-a3b5-11e8-9185-38098bc483e0.PNG)
![macd param](https://user-images.githubusercontent.com/10659481/44308422-eddea680-a3b5-11e8-9a75-958674016652.PNG)

**Comment by mutenroch** [comment]
should this post be in the forum instead of here, shouldn't it?

**Comment by 77cc33** [comment]
I have the same issue with MCAD for poloniex:BTC:LTC

I tried to install it at custom dedicated server Ubuntu 16.04, and with docker as well, and it has the same issue as described above for many strategies - just empty results.

For test I used poloniex BTC full dataset.

Any advice how to fix it, will be awesome.

**Comment by 77cc33** [comment]
Ok after some testing, seems this issue is related only to Gekko-datasets. 

So if I'am testing datasets what were imported with gekko directy from exchanges, everything is fine. 

But if I'am downloading datasets from Gekko-datasets as sqlite database, I'am getting in this issue for, SOME strategies, as described above. 

I tried to change gekko versions (stable 0.6.5, 0.6.4, 0.6.2, develop) they have all the same behavior, so seems it's some issue with https://github.com/xFFFFF/Gekko-Datasets

**Comment by storshun** [comment]
@askmike this sounds like the same issue I am having, but mine was broken with locally imported data via gekko. I didn't pull data from anywhere except the gekko importer.
