### ISSUE TITLE
Backtest import in GUI doesn't import to the correct date. Loader starts in negative.

### ISSUE THREAD

**Issue by rkingy** [askmike/gekko#2563]
**I'm submitting a ...**
[ X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Went to import from binance, set my date range clicked import.
Progress started from negative. And never imported to the date (current time) as requested.

**Expected result** (what you hoped would happen)
Import imports to when I say

**Actual result** (unexpected outcome)
Doesn't import the correct amount of data.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I discovered that in core/markets/import.js the dates need to be converted to UTC. This fixed the issue for me.. the old version had .utc() around the to and from dates. Not sure why this was removed?

**Comment by askmike** [comment]
> never imported to the date (current time) as requested.

All times are supposed to be in UTC, so if you are not in a timezone equal to UTC the time you fill in there is not what Gekko will import.

> Progress started from negative.

Yes it's a timezone issue. I think the bug was introduced here: https://github.com/askmike/gekko/pull/2263#discussion_r199354415 @mark-sch maybe you can weigh in? EDIT: That only seems to impact kraken importing, while this bug is preset everywhere. Might not be that PR - but I'm sure something changed along the lines where we dropped an UTC conversion somewhere.

**Comment by rkingy** [comment]
It looks like the .utc() conversions were removed in commit #1ce10f455ebab261e3ab43a121b2058236ff11aa 

I'll push up a fix.

**Comment by askmike** [comment]
this is fixed in latest develop.
