### ISSUE TITLE
Run 2 Tradebots On Same platform

### ISSUE THREAD

**Issue by LoayGhreep** [askmike/gekko#2584]
Hello ,
All things works well
my question is :
i want to trade VET/BNB and XRP/ETH at same time
Gekko refuses this ... how can i do it ?

**Comment by askmike** [comment]
This is not supported for a number of reasons. If you really want to:

1. Create different binance accounts and deposit funds accordingly.
2. Download 2 seperate gekko installations and configure them to run on different ports (this document tells you what files to edit, https://gekko.wizb.it/docs/installation/configuring_gekko_on_a_server.html - though it doesn't tell exactly what you need to do since you are the first person who ever asked me this -> you need to have both installations run on different ports).
3. configure each instance for a different binance account.
4. run one bot per gekko instance.
