### ISSUE TITLE
slippage is no longer used in backtesting

### ISSUE THREAD

**Issue by wddxnyr** [askmike/gekko#2621]
**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
running backtests

**Expected result** (what you hoped would happen)
The result is affected by simulated slippage 

**Actual result** (unexpected outcome)
No difference

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
After checking the code, I found that slippage is no longer used in backtests anymore

**Comment by askmike** [comment]
This was changed to mimic the live order execution strategy: Gekko doesn't do market orders so as such never has slippage in the traditional definition (slipping into the orderbook by trading more volume than there is liquidity at the top of the book).

I'm going to rework the wording, so that paper trader uses slippage again but everyone understands this represents the difference between expected execution price and actual execution price (either the same or worse, never better).
