### ISSUE TITLE
[Feature Request] Backtest progress to UI

### ISSUE THREAD

**Issue by H256** [askmike/gekko#2645]
**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository
[x] feature request

While sitting here waiting on my 1 minute candle backtest result... I was just wondering if it would be possible to send backtesting progress to the client when Gekko has beenstarted using the `--ui` option. 

Just like the import also has a progress-display. That would be very helpful if that could be done.

**Comment by askmike** [comment]
Would be possible yes:

The backtest happens in a child process which communicates with the main process (gekko server). We can introduce a new [gekko event](https://gekko.wizb.it/docs/internals/events.html) that describes a portion of a backtest is now completed (for example 5%). Alternatively this event can come every second or something. The main process can relay that via websocket to the frontend. The frontend can render a loading bar.

We need to do some rewiring since as of right now the backtest handler right now relays a single completed callback used by the server.

Unfortunately I will be too busy for this in the short term. In the long term I will work on this for Gekko Plus anyway :)
