### ISSUE TITLE
[Feature Request] Passing SSL Certificates to gekko in SSL mode

### ISSUE THREAD

**Issue by blastbeng** [askmike/gekko#2658]
Hello,
i am trying to configure gekko using SSL but i am getting from chrome:

ERR_SSL_PROTOCOL_ERROR

and gekko doesn't even load.

I am using apache2 and certbot, but do i need to put these certificates obtained with certboot in any config file in gekko? or do i have to launch node gekko.js --ui specifying SSL files?

Thanks

**Comment by blastbeng** [comment]
EDIT:

I made some changes on server.js to make ssl working, now it is working fine. but i had to add this to 
server.js at the head of the file:


```
const tls = require('https');
const server = null;
if(config.ui.ssl){
  var options = {
    key: fs.readFileSync('/etc/certdir/privkey.pem').toString(),
    cert: fs.readFileSync('/etc/certdir/cert.pem').toString(),
    passphrase: 'yourchoosenpw',
    rejectUnauthorized: true,
};
  server = tls.createServer(options);
}else{
  server = http.createServer();
}
```

Do you think we can integrate this in Gekko with configurable SSL options ?

something like:

node gekko.js --ui --key=/etc/certdir/privkey.pem --cert=/etc/certdir/cert.pem --passphrase=yourchoosenpw

I can make this edit but I've never pushed anything on github and I need some opinions since i'm a node.js noob.

**Comment by askmike** [comment]
I don't want to pass SSL security to the Gekko server for a number of reasons*. I do highly recommend you use SSL if your Gekko is publicly accessible (such as on a server exposed to the open internet). Though please use a proper webserver for this. See the docs here: https://gekko.wizb.it/docs/installation/configuring_gekko_on_a_server.html

*the biggest reason being doing security properly is very hard - with SSL you need to think about proper and secure cipher suites, etc. Gekko doesn't have a release procedure in place so we can tell our users they need to update their Gekko in case we update those in the future, etc. The second biggest reason is that you probably also want auth, since else everyone can access your server anyway, which is pretty hard to do securely. We recommend Basic Auth as managed by a proper webserver (such as nginx).

FYI, we use the same tactic as another open source project called Prometheus: https://prometheus.io/docs/guides/tls-encryption/
