### ISSUE TITLE
error api key is required!

### ISSUE THREAD

**Issue by ikoom** [askmike/gekko#279]
error api key is required!

**Comment by Nargren** [comment]
Sorry, where are you getting this error? A bit more information would be useful.

**Comment by ikoom** [comment]
when i try to run gekko i get throw new error: api key is required.
the error has somthing to do with pushbullet!

**Comment by Nargren** [comment]
Pushbullet pushes messages to your computer and/or phone if set up, so that you can follow price movements and act on it manually. You have to first register at https://www.pushbullet.com/ and get an authentication token that you must then enter in your config file on line 238. (by default pushbullet is enabled)

Alternatively try disabling pushbullet, set variable on line 235 to false.

**Comment by ikoom** [comment]
thank you xD
