### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by massaroni** [askmike/gekko#2837]
Is this project still under active development or has it been effectively abandoned?  My PRs are going stale after months of inactivity, and there hasn't been a new release or new commits pushed up in a while.  Does anyone else out there in the internet want to maintain this?

**Comment by uspen** [comment]
I going to https://www.freqtrade.io. Its have cool features!

**Comment by dcsan** [comment]
i think the author moved on to a python server project, there was a group on discord to discuss. 
it's a shame as the project seems very well built...

**Comment by uspen** [comment]
Hmm, there are not enough features that the gekko bot should provide. For example, options for stop loss, trailing etc...

**Comment by massaroni** [comment]
> i think the author moved on to a python server project, there was a group on discord to discuss.
> it's a shame as the project seems very well built...

@dcsan Is said python server project supposed to be a replacement for Gekko, or is it unrelated?  Is there still a place for Gekko in the algo trading scene?  It's so easy to set up and get started that it's hard to ignore, and it's easy to extend because it's so well built.  What are your thoughts?

**Comment by fabohax** [comment]
I think this project may continue, if not by the author, by the community. There is a lot of good and new programmers who want to help. Just be in touch. :)

**Comment by dcsan** [comment]
I believe the said python project is the basis of the paid offering, gekkoplus, and this project is basically abandoned at least by the original author. however as @fbport says maybe people will pick it up. he told me the reason was mainly the python libraries for technical trading were a lot more advanced.

personally I started working on something similar from the ground up cos i wanted to understand the code more and I prefer working in typescript. I'll post a link to that later after a bit of cleanup

There seems to be a lot of community interest in this project, it's a shame @askmike has moved on to other things. I think the "free" version here could be a good feeder to GekkoPlus paid service. I found that a bit unappealing myself as you can only backtest 30 strats/month. I feel i have a **loooong** way to go before i want to go live with my strats!
https://gekkoplus.com/pricing/

Also in the python world there are a few other systems, that gekko seems to have been inspired by that are already open source, eg https://github.com/alpacahq/pylivetrader

When the owner of an OSS project disappears it does make things difficult to proceed as PRs then stop getting merged etc, the community gets splintered, confusion on how to proceed. 

Is there anyone that would be willing to step in as maintainer and take over as the main "fork" and accept PRs?
https://github.com/tresor-llc/gekko/network

**Comment by askmike** [comment]
There is zero python in Gekko Plus. The whole project is running on Gekko
and javascript. All statistical libraries used (TA lib and Tulip) are
written in C, there exists bridges for both javascript and python.

Gekko is not abandoned by me. I have just been very busy so have been
unable to deal with the daily influx of support tickets for a while. Will
try to pick up ASAP.

**Comment by massaroni** [comment]
Thanks guys, that's good to hear.

Mike is a really busy guy, maybe some of us power users who know the codebase really well can step up and close out some of these Issue tickets so that Mike can focus on bigger stuff?  I see about 30 issues right now, so if we each closed out one per week then we could probably clean it all up in about one week.  I can do one this week.

**Comment by mboremski** [comment]
I also would love to see more activity here.
Either by @askmike or someone else who is able to help.
Maybe there could be some trusted collaborators here to help keeping the stale-bot away from this project.
The last month some good PRs have been closed.. 😢

**Comment by dcsan** [comment]
yes
> @stale stale bot closed this 6 days ago
seems to be on a lot of PRs. 

but 777 merged PRs at this point! since 2013...

**Comment by askmike** [comment]
I'll go over closed PRs when I have some time!

**Comment by anal0g** [comment]
@askmike Really nice to hear open source Gekko is not abandoned. Looking forward to a new release!

**Comment by melroy89** [comment]
@askmike Good to hear! I hope you can create a new stable release. Maybe indeed appoint a person you trust to support this project?

**Comment by nick-dolan** [comment]
> @askmike Really nice to hear open source Gekko is not abandoned. Looking forward to a new release!

\+

**Comment by sanitariu** [comment]
I think it is abondoned. Latest commit is from April 2019.
If you plan to use bots better go for zenbot or freqtrade.
They are based on cxxt and support almost all exchanges.
Maybe owner here is going for paid bot.......

**Comment by cwouter** [comment]
Try [SockTrader](https://github.com/SockTrader/SockTrader). Its a websocket based tradingbot written in typescript. Its still under development but it has some unique features compared to other trading bots.

**Comment by skylinetech-team** [comment]
@askmike after we tried fretrade and zenbots, Gekko still the most feature rich - smooth to use crypto trade bots platform.

we are trying to load our trade bot with Kraken, got errors - pls see #2874 complaining assets with kraken not valid when running live trade bots with Kraken.

we looked at https://github.com/askmike/gekko/blob/develop/exchange/wrappers/kraken-markets.json
can't figure out whats the issue here.

could you please help ?

thanks much ! @askmike

**Comment by ritzeng** [comment]
> I think it is abondoned. Latest commit is from April 2019.
> If you plan to use bots better go for zenbot or freqtrade.
> They are based on cxxt and support almost all exchanges.
> Maybe owner here is going for paid bot.......

If you have read carefully the history then you would notice that the owner is very busy. That can happen with projects where nothing is paid and all is free.

**Comment by sanitariu** [comment]
I read it carefully. He went for a paid bot but he abandoned that project too and will return here when he have more time. I am still using gekko on one place only for 1 currency and it works to some extent.
All my other bots i moved to freqtrade which is also open source.

**Comment by askmike** [comment]
Unfortunately the cat is out of the bag now :(

I am not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
