### ISSUE TITLE
issue on  install exchange dependencies on win 7

### ISSUE THREAD

**Issue by hamidus** [askmike/gekko#2839]
hello

i have an issue on instaling gekko dependencies
when i go install exchange dependencies

cd exchange
npm i --only=production

it show this :
C:\Users\Système\Desktop\gekko-develop\exchange>npm i --only=production
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Système\AppData\Roaming\npm-cache\_logs\2019-08-25T22_09_
8_644Z-debug.log

i have tried to fix this many time by reinstalling node js and deleting npm cash and folder
without success

what can i do to fix that ??or is that another way to install  exchanges one by one 
for example i want to install only binance exchange 
the npm error  is showing only i go to  exchange folder not on gekko develop folder there are 0 vulnerability warning
if there is another way to install only binance exchange please show me how
thanks

**Comment by PGTBoos** [comment]
I had problems to, there is something wrong with the windows installations.
Eventually i solved it (even without running on bash), but it was a lot of work.
As i had another instal in ubuntu in virtual box, i copied over that content.
Since its mainly node based javascript that is executed (and that's OS independant).

However i also had to edit a lot of module files since the filesystem on linux doenst match ubuntu's style mounting.. so local folder references had to be renamed (in my case to g:\gekko\ (etcetera)

Maybe...just maybe, you might give it a try here is a clone of my windows gekko install
https://drive.google.com/open?id=1R1vwV9Vn87IvBLL5jarCCRIpIcPlILj2
You could in windows use subst command to connect to it as g:\gekko as well...
