### ISSUE TITLE
New trading method - stop loss

### ISSUE THREAD

**Issue by siergiej** [askmike/gekko#37]
Mike, correct me if I'm wrong, wouldn't it be quite simple to implement a stop-loss trading method in gekko? This would be useful in bubble territory :-) what do you think?

**Comment by HornKild** [comment]
I try to set up Trailing Stop after a new position is open, what is the best solution to achieve this ?

**Comment by AdityaNayak** [comment]
Were you able to achieve trailing? Would appreciate some direction.

**Comment by laredoza** [comment]
Hi,

I've added an initial implementation of a TrailingStop strategy:
https://github.com/laredoza/gekko/blob/stable/strategies/L1-TrailingStop.js
https://github.com/laredoza/gekko/blob/stable/config/strategies/L1-TrailingStop.toml
Still needs a lot of testing though, so don't trust it.

**A nice description can be found here:**
https://www.youtube.com/watch?v=kY9n8EQqs7w

**A. Where this strategy works:**
1) Initial buy at $100, sell order at $110, stop order = 98$(trailingValueIncrement = $2)  --> Market value hits $110. You == Trading God 
2) Initial buy at $100, sell order at $110, stop order = 98$(trailingValueIncrement = $2)  --> Market value hits $108. then drops to $90. This strategy would have sold at $106. You == Trading God

**B. Where this strategy doesn't work so well:**
1) Initial buy at $100, sell order at $110, stop order = 98$(trailingValueIncrement = $2)  --> Market value drops to $98, then rises to $110 immediately. You != Trading God as you would have sold at $98. You would have lost $2 + $10

The problem here is that the stop order was too tight. If you used a stop increment of $4 you would have got your full profit but in A.2 you would have lost another $2. Using the correct stop order is key. As far as I lnow the ASR indicator can be used to dermine the correct stop order increment.

This is a semi-automated system so I'm not 100% sure if it belongs in Gekko to be honest.

**Comment by jurepetrovic** [comment]
Hello Gents, 

Currently looking at Bitstamp API. These are the possible orders:
BUY LIMIT ORDER
BUY MARKET ORDER
SELL LIMIT ORDER
SELL MARKET ORDER

In their web UI they also support STOP ORDERs with trailing stop. 
Do you know any exchange that supports stop orders over the API? 

Thanks, 
Jure

**Comment by uipko** [comment]
If I remeber correctly the API of kraken does support stoploss, don't know
if it supports trailing stoploss.

**Comment by drush** [comment]
GDAX supports Stop + Stop Limit orders as well.

**Comment by der-seemann** [comment]
@laredoza 
I'm trying to set up your trailing Stopploss strategy, but have some difficulties.
I don't want it to buy anything, just keep the stopp loss 5% below the highest price. If the market drops below that value, all of my holdings should go short.
Can you or anyone else help me with the correct settings?

**Comment by laredoza** [comment]
Hi @der-seemann, currently this doesn't support percentage but you can add a value.

trailing Value Increment = 10
initialStopValue = 300
movingStopValue = true
buy = false
buyPrice = 0
sell = false
sellPrice = 0

In this example the initial stop value is $300. If the current value goes to 400 the stop order will become 400 - 10 (trailing Value Increment). If the value goes below $390 all your crypto will be sold.

Please test this on the paper trader as I don't have a pc to test this at the moment. You can of course update the strategy to support percentage.

Make sure you test this properly before using it with real fiat / crypto
