### ISSUE TITLE
error sending to IRC channel

### ISSUE THREAD

**Issue by Stoner19** [askmike/gekko#474]
```
2016-10-09 18:10:37 (ERROR):    IRC ERROR: { prefix: 'leguin.freenode.net',
  server: 'leguin.freenode.net',
  command: 'err_cannotsendtochan',
  rawCommand: '404',
  commandType: 'error',
  args: [ 'mygekkobot', '#my_channel', 'Cannot send to channel' ] }
2016-10-09 18:10:37 (ERROR):    IRC ERROR: { prefix: 'leguin.freenode.net',
  server: 'leguin.freenode.net',
  command: 'err_cannotsendtochan',
  rawCommand: '404',
  commandType: 'error',
  args: [ 'mygekkobot', '#my_channel', 'Cannot send to channel' ] }
2016-10-09 18:10:37 (ERROR):    IRC ERROR: { prefix: 'leguin.freenode.net',
  server: 'leguin.freenode.net',
  command: 'err_cannotsendtochan',
  rawCommand: '404',
  commandType: 'error',
  args: [ 'mygekkobot', '#my_channel', 'Cannot send to channel' ] }
```

Bot connects to IRC but doesn't appear to actually be able to send any messages to the channel.

```
config.ircbot = {
  enabled: true,
  emitUpdats: true,
  channel: '#my_channel',
  server: 'irc.freenode.net',
  botName: 'mygekkobot'
}
```

**Comment by askmike** [comment]
strange, it's working for me:

![screen shot 2016-10-10 at 14 39 06](https://cloud.githubusercontent.com/assets/969743/19237986/551ade8e-8ef7-11e6-8cb0-8769abd48d2c.png)

could you let me know the ouput of:

```
node gekko --version
```

**Comment by Stoner19** [comment]
After letting it run for several hours it did write to the IRC channel, but I still can't explain the errors showing initially when launching gekko.

**Comment by askmike** [comment]
Very strange, it looks like the error you got (`err_cannotsendtochan`) has to do with the IRC channel:

> Sent to a user who is either (a) not on a channel which is mode +n or (b) not a chanop (or mode +v) on a channel which has mode +m set and is trying to send a PRIVMSG message to that channel.

([source](http://moepii.sourceforge.net/irclib/javadoc/org/schwering/irc/lib/IRCConstants.html#ERR_CANNOTSENDTOCHAN))

Did you maybe start multiple Gekkos trying to register under the same username in the same channel? Or did you do something with the IRC channel?

Anyway, I'll close this for now since it seems like this is an issue with the IRC channel.
