### ISSUE TITLE
Multi timeframe strategies

### ISSUE THREAD

**Issue by tomih** [askmike/gekko#496]
Hi,

I'm trying to add additional timeframe candles available to strategies, but got stuck with sync and async indicator results.
 
goal:
I want to be able to use multiple indicators in one strategy (mix of sync & async indicators) with multi timeframe candles.
In addition, I'd like to access history of candles & indicator values in a trading method. something like this:
history.open[0] - returns last candles open price
history.mymacd[1].signal - returns previous candle macd signal value

Full code:
https://github.com/tomih/gekko/tree/multitimeframe

Walk through:
Multi timeframes are configured in config.tradingAdvisor.timeframes. (look at sample-config)
CandleBatcher makes different timeframe candles and emits them as candle_tf5, candle_tf15, ...
BaseTradingMethod receives completed candle and calculates sync and ta indicators.

Problem:
Results of sync macd and talib macd are different/wrong and/or history of candles is out of sync with current processed tick.

I think I've done it right up to calculating indicators in propagated candle. (BaseTradingMethod.tick).
I obviously don't understand how sync and async functions work together :(.

Currently BaseTradingMethod is a mess and I believe the approach is completely wrong. Please point me to the right direction.

I'm new to node so please, bear with me. :)

btw: @askmike great job on webUI.

T.

**Comment by askmike** [comment]
Hey Tomi,

Awesome to see that you posted your work in progress!

---

> Currently BaseTradingMethod is a mess

It already was a bit of a mess to be honest, can't blame you to much for that...

Also: the [current latest BaseTradingMethod](askmike/gekko/develop/plugins/tradingAdvisor/baseTradingMethod.js) (found in develop) is a bit different from the one you worked on top of (stable).

> In addition, I'd like to access history of candles & indicator values in a trading method.

I do see this as two very different features, mind if we create a seperate issue for that? Until then you can always stuff any candle you see in your method into it's own array.

> I obviously don't understand how sync and async functions work together :(.

So the problem is that with how the BaseTradingMethod currently works it is very hard and hacky to get it all working there (the BaseTradingMethod is already to big imo, it used to be simple before TAlib which I just hacked in there). It might be time to re approach the whole situation.

---

I've looked at your code and there I really like the idea of the timeframes array. But before we hack until it works could we take a step back and think about how we want Gekko to work?

## The idea (before multipletimeframes)

Every time you run a strategy there are three parts involved:
- custom settings (right now stored under `config[strat-name]`)
- candle settings that influence over how the big candles are you want to calculate over (and also the historySize, which tells Gekko how long your strat needs to warmup. (stored in `config.tradingAdvisor`)
- a custom strategy (the actual code)

The main idea is that without changing strat settings or the strat itself you have control over how "zoomed in" you want your strat to see the market (5min candles paint a very different picture than 12hour candles). By changing the strat settings you can tweak thresholds and whatnot (and indicator parameters).

---

Everyone is free to make a strat that _should_ only work in a very specific market (say BTC:USD over 60min candles). However I do want Gekko to facilitate maximum configurability.

## The idea (including multipletimeframes)

What do you think of something like:

The config.tradingAdvisor.candleSize now takes an object of different candles the strategy is interested in? Something like:

```
config.tradingAdvisor.candleSize = {
  quick: 10, // 10 minute candle
  slow: 15 + 60 // 15 hour candle
}
```

_(this way the user can easily change the size of either one of those candles)_

And in your method you can "attach" indicators to a certain timeframe (very similar to what you did [here](https://github.com/tomih/gekko/blob/multitimeframe/core/baseTradingMethod.js#L257)):

```
 this.addTalibIndicator(name, type, settings, timeframe)
```

and then in either the BaseTradingMethod or the [tradingAdvisor](https://github.com/askmike/gekko/blob/develop/plugins/tradingAdvisor/tradingAdvisor.js) we calculate the correct candles, and feed them into correct indicators

_However, when do we do something with the results? Say someone has a 3 minute and a 7 minute timeframe. Should we fire the `tick` method after either one updates?_

**Comment by tomih** [comment]
Mike,

You are right. Lets leave the BaseTradingMethod problem until we decide on core components and functionality.

Regarding multitimeframes:
I see multitimeframe candles and history a must for every strategy (the days for simple macd bots are gone).

> However, when do we do something with the results? Say someone has a 3 minute and a 7 minute timeframe. Should we fire the tick method after either one updates?

I'll try to explain on my example:
I create all configured candles in [tradingAdvisor.js](https://github.com/tomih/gekko/blob/multitimeframe/plugins/tradingAdvisor.js#L73) via CandleBatcher and then [emit](https://github.com/tomih/gekko/blob/multitimeframe/core/candleBatcher.js#L36) them to  [BaseTradingMethod](https://github.com/tomih/gekko/blob/multitimeframe/core/baseTradingMethod.js#L157). **That means a strategy is called on each full candle** (1min, 5min, 15min). We just have to pass timeframe parameter to methods (update, log, check) to properly handle the events.
Since all indicators are calculated in baseTradingMethod, I thought that would be the best place to store the indicator history as well (we actually already have a history for the candles there, used for talib).
To finish this multitimeframe saga, I must assure that everything is calculated before I call a strategy and that no further calculations are made until the strategy is done (backtesting problem).

> ```
> config.tradingAdvisor.candleSize = {
>   quick: 10, // 10 minute candle
>   slow: 15 + 60 // 15 hour candle
> }
> ```

I think every timeframe should have its own warmupSize and historySize properties as well. 

One more thing: since timeframes are strategy dependant (you don't need 1m candle if it is not handled in strategy) we could configure it in strategy.toml.
I know that current implementation of webUI works with single timeframe (we have pulldown), but timeframes could be easily edited in toml file as well.

another nice day,
T.

**Comment by askmike** [comment]
Since the UI any possible integration into mainline Gekko would need to be rediscussed. If you want to restart that discussion please let me know!
