### ISSUE TITLE
Trades Executed as History Loads

### ISSUE THREAD

**Issue by KryptoNova** [askmike/gekko#515]
Is the trader part of gekko supposed to wait till all the history is loaded before the calls for buy and sell are made?

I had an experience that when the history was loaded for an exchange, it was causing the trading mechanism to buy and sell based on history.  I would expect that the trades would start until all the history has been loaded.

I am new to Github and am not versed in how to search through existing issues.  Apologies in advance if this is something that has already been addressed.

**Comment by askmike** [comment]
Hey @KryptoNova,

> Is the trader part of gekko supposed to wait till all the history is loaded before the calls for buy and sell are made?

Sort of, the trader will always act on signals. However the trading method will only send an advice signals after a "warmup period". The warmup period is: [historySize](https://github.com/askmike/gekko/blob/stable/sample-config.js#L33) * [candleSize](https://github.com/askmike/gekko/blob/stable/sample-config.js#L32) in minutes.

So if you watch hourly candles (by having a candleSize of 60) and your historySize is 25, gekko will only do anything after at least 25 hours of data*.

*Note that when Gekko starts it tries to get the historical data either from the exchange or from locally saved data (when you restart it for example).

------

Could you let me know:

- What trading method are you using (see [this line](https://github.com/askmike/gekko/blob/stable/sample-config.js#L31))?
- What candleSize and historySize is in your config?

**Comment by KryptoNova** [comment]
Thanks @askmike ,

I think you nailed it.  I was using MACD and wanting to watch the candles by the minute after there were 36 of them.  So based on you explanation, that would indicate that after the first 36 minutes of history/candles from the exchange is processed, it would start executing buys and sells.

Now I know and can plan accordingly.  Thank you very much and love the project!!!

**Comment by askmike** [comment]
> I was using MACD and wanting to watch the candles by the minute after there were 36 of them.

You can do that yourself by going logging some stuff in the [MACD method](https://github.com/askmike/gekko/blob/stable/methods/MACD.js) (gekko/methods/MACD.js), if you change:

    // what happens on every new candle?
    method.update = function(candle) {
      // nothing!
    }

into:

    // what happens on every new candle?
    method.update = function(candle) {
      console.log('MACD update')
      console.log('iteration:', this.age)
      console.log('candle time:', candle.start.format())
    }

-----

Additionally since I see you are trying to create something like Gekko yourself:

- Methods need to have a "check" method and an "update" method, the first one is only called "after" the warmup page, see [here](https://github.com/askmike/gekko/blob/stable/core/baseTradingMethod.js#L193-L197).
- In Gekko the trading method doesn't care where the data is coming from, so on start Gekko does it's best to figure out what historical data the exchange is able to provide (Gekko supports a number of exchanges, some like BTC-E only give you the last xx trades and you need to figure out how far that spans back). Gekko will also try to combine live exchange data with local available data (if you run gekko all data is saved in DB), that logic is a bit ugly at the moment but can be found [here](https://github.com/askmike/gekko/blob/develop/core/tools/dataStitcher.js#L39-L42).

If you run into anything or have any questions feel free to ask :)
