### ISSUE TITLE
Backtester Trading Double

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#575]
In may current test for a trading strategy, the back tester is making two buy trades after another and then also two short trades after another.

<img width="1897" alt="bildschirmfoto 2017-01-30 um 16 54 20" src="https://cloud.githubusercontent.com/assets/9429219/22429987/e3268062-e70c-11e6-951d-ed7b59239883.png">

**Comment by GenXau** [comment]
Hi Decoye,

May i ask how you created the graph showing the back tester trades? Is this something you could share? It would be very useful to be able to visualize the trading decisions. 

Thanks,

**Comment by askmike** [comment]
This has to do with your trading method: a trading method is treated like a black box within gekko: market data goes in and advice comes out. Triggering the same advice twice is something that could be handled in the trading method (not sure which one you are using), but there is not negative effect (since the paper trader and the real trader would have already traded into that position).
