### ISSUE TITLE
CandleSize less than minute

### ISSUE THREAD

**Issue by sad8c** [askmike/gekko#598]
Can somebody advice me, how can i make candleSize less than a minute? Maybe 30 seconds or even 10 seconds.
Is it possible to make some changes in candleCreator or candleBatcher files for this case?

**Comment by sad8c** [comment]
I've already changed a heartbeat ih heart.js to 5 seconds (for bitfinex), Also i need to make candles less than a minute...

**Comment by askmike** [comment]
Unfortunately this is currently not possible within Gekko.. If you want to deal with a lower resolution you probably want to use websockets over polling (because polling becomes to slow) and have a different strategy for storing historical data. To keep Gekko simpler I made the choice the minimum candle time to 1 minute.

I am locking this for now as this is not within Gekkos scope. But please reply and let me know how you would use gekko that would work up to the 1 second level.

**Comment by sad8c** [comment]
@askmike , Thank you for your answer. I've found that i can use tradeBatcher for my own advising speed. But i have only one question. How can i init advice method from tradeBatcher correctly. I don't need candles functionality already, i need only init advice from tradeBatcher....

**Comment by askmike** [comment]
If you want to do that you need to hack gekko a bit to suit your needs, gekko currently works:

- it hooks up an exchange to the tradebatcher to a candlecreater. The last one is exposed in a "market".
- Your strategy (trading method) code expects candles and is wrapped into a gekkoStream.

![architecture](https://camo.githubusercontent.com/49d5d933a0857db0f3d42bd7b463a539aacbc9c1/68747470733a2f2f77697a622e69742f67656b6b6f2f7374617469632f6172636869746563747572652e6a7067)

If you want to take the candles out and act directly on trades you need to hack a bunch of things:

- the market, the stream, and the gekkoStream all assume only candles.
- the code that integrates your strategy (and exposes indicators) only deals with candles.

I guess the easiest would be to move away from the full Gekko architecture and directly hook up the tradebatcher to your code that executes your strat and quickly creates some candles so you can use indicators (if you want too).

**Comment by sad8c** [comment]
@askmike Can we chat by skype and maybe you can help for payment? My skype: kotov.altmedia
