### ISSUE TITLE
Code for Ta-lib indicators

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#604]
The documentation is excellent on how to code the indicators, however, I am lost as to how to find out the return values for the ta lib indicators and then what to do with them. 

For example; the Talib-DEMA seems straight forward enough, pass in a time component, and using an inspect on the return array I see that it returns outReal; but what is this and what do I do with it remains a mystery. I can't find anything in the talib documentation either. 

Does anyone know?

**Comment by askmike** [comment]
outReal is the result of the calculation, in the case of DEMA:

    DEMA = ( 2 * EMA(n)) - (EMA(EMA(n)) ), where n= period

[source](http://www.investopedia.com/ask/answers/121814/what-double-exponential-moving-average-dema-formula-and-how-it-calculated.asp)

More info about the DEMA:

> Thus, the DEMA still reflects a moving average while keeping pace with current, daily changes. Traders commonly utilize this tool to confirm what they see as reversal signals. For example, if DEMA (50) and DEMA (200) create a death cross amid increased selling pressure, the trader can confirm the price is likely entering a bearish trend. Meanwhile, if short-lived, the bearish trend may already be reversing by the time the EMA and SMA catch up. Therefore, DEMA is well-suited for short-term trend indications.

-----

also the outReal array is an array that maps to previous candles (the last item in the array corresponds to the most recent candle). But you shouldn't have to deal with the array, as gekko will automatically take the last value of the array if you registered the talib indicator via gekko. If that doesn't answer your question, please let me know!

**Comment by thegamecat** [comment]
I think I must not be understanding how this works then - which is probably my fault :)

Please acknowledge that the code below is very much a work in progress, and I'm trying to understand the inputs and outputs for now. 

This is far as I have got. I have made this method and passed in the following from config.js:


`// Bollinger bands settings:
//profit
config['talib-bbands'] = {
parameters: {  
	optInTimePeriod: 5,
  	optInNbDevUp: 2,
	optInNbDevDn: 2,
	optInMAType: 0
	},
  thresholds: {
    down: -0.025,
    up: 0.025
  }
};

`

This is talib-bbands.js

`// If you want to use your own trading methods you can
// write them here. For more information on everything you
// can use please refer to this document:
// 
// https://github.com/askmike/gekko/blob/stable/docs/trading_methods.md
const util = require('util');
var config = require('../core/util.js').getConfig();
var settings = config['talib-bbands'];

// Let's create our own method
var method = {};

// Prepare everything our method needs
method.init = function() {
	this.name = 'talib-bbands'
	// keep state about the current trend
	// here, on every new candle we use this
	// state object to check if we need to
	// report it.
	this.trend = 'none';

	// how many candles do we need as a base
	// before we can start giving advice?
	this.requiredHistory = config.tradingAdvisor.historySize;

	var customBBSettings = settings.parameters;
	console.log(util.inspect(settings.parameters));
	// define the indicators we need
	this.addTalibIndicator('mybb', 'bbands', customBBSettings);
}

// What happens on every new candle?
method.update = function(candle) {
	// nothing!
}


method.log = function() {
  // nothing!
}

// Based on the newly calculated
// information, check if we should
// update or not.
method.check = function() {
	//upperband, middleband, lowerband = BBANDS(close, timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)	
	var price = this.lastPrice;
	var result = this.talibIndicators.mybb.result;
	//var macddiff = result['outMACD'] - result['outMACDSignal'];
	//  console.log(util.inspect(result, {showHidden: false, depth: null}))

	var lower = result['outRealLowerBand'];
	var medium = result['outRealmediumBand'];
	var upper = result['outRealhighBand'];
/*
Bollinger Bands consist of three lines. The middle band is a simple moving average (generally 20 periods) of the typical price (TP). The upper and lower bands are F standard deviations (generally 2) above and below the middle band. The bands widen and narrow when the volatility of the price is higher or lower, respectively.

Bollinger Bands do not, in themselves, generate buy or sell signals; they are an indicator of overbought or oversold conditions. When the price is near the upper or lower band it indicates that a reversal may be imminent. The middle band becomes a support or resistance level. The upper and lower bands can also be interpreted as price targets. When the price bounces off of the lower band and crosses the middle band, then the upper band becomes the price target.

See also Bollinger Width, Envelope, Price Channels and Projection Bands.
*/

//this section to be updated once I understand how this works
// if(settings.thresholds.down > macddiff && this.trend !== 'short') {
  //  this.trend = 'short';
   // this.advice('short');

  //} else if(settings.thresholds.up < macddiff && this.trend !== 'long'){
  //  this.trend = 'long';
  //  this.advice('long');

  //}
}

module.exports = method;
`




Your explanation is rather relevant and interesting: 

> also the outReal array is an array that maps to previous candles (the last item in the array corresponds to the most recent candle). But you shouldn't have to deal with the array, as gekko will automatically take the last value of the array if you registered the talib indicator via gekko. If that doesn't answer your question, please let me know!

It is possible I simply don't understand how to use this. So a few key answers may help me:

1) Do I need a new method to call a talib indicator?

2) How do I determine the direction of the market? It seems like Gecko does that but I'm struggling to understand where I see this for my method.

3) How does one chain multiple indicators at different thresholds of priority?

**Comment by askmike** [comment]
Would you mind formatting the code? It's not really readable atm.

As to your questions, I think it will be more clear by explaining Gekko terminology:

Within gekko, a *trading method* is a *strategy*, it is a piece of code that will take candles (via the `update` and `check` methods) and will eventually send out advice on what position to take in the market (long or short). This trading method can use a number of tools to figure out what to do, most trading methods (incl. the ones that come with gekko) use a strategy based around trend watching, the idea is that if the trading method thinks the current trend is UP it will advice to LONG (under the assumption that the price will go even higher).

These trading methods use a number of tools to try and figure out the current trend:

- indiciators (gekko has a few native indicators, and exposes 100+ via TAlib)
- thresholds: ex. MACD: some signal needs to do more than cross some other signal, it needs to go over with a threshold).
- trendduration: if someone buys a lot of an asset, the price will go up but this doesn't have to mean that it's an uptrend. Methods can keep track of how long the price has been going up and only if it has been going up for X candles, really trigger the advice.

But you are free to come up what ever kind of other logic you want!

------

If you create your own method Gekko gives you easy access to add indicators, if you look at the talib-macd method:

It registers the indicator (using the talib library) MACD:

    this.addTalibIndicator('mymacd', 'macd', customMACDSettings);

it fetches the result of the indicator:

    var result = this.talibIndicators.mymacd.result;

The MACD indicator is based on a calculation that needs to be run every candle (and the result comes back async in a hard to work with format). So Gekko will do all that work for you, you only need to register it and handle the result. You can use all [these talib indicators](https://github.com/askmike/gekko/blob/develop/docs/trading_bot/talib_indicators.md) within your method.

----

EDIT: to answer your questions:

1. When creating a method you normally don't create your own indicators (especially since when using TAlib you already have so many available). If you want to use another indicator, you have to create a new method that does whatever you want with whatever indicator youwant.
2. Indicators try to detect directions in the market, but because they are very raw they are part of a more abstract *trading method*, this will include things like thresholds and trendDurations.
3. the current tresholds you see in other trading methods are just an idea, you can structure your method however you want, with how many indicators you want.

**Comment by thegamecat** [comment]
Thanks for your response, I think that's what I'm doing in my talib-bband.js as above (I have tried to reformat it).

**Comment by askmike** [comment]
Could you maybe put it in a gist and give the link here?

**Comment by thegamecat** [comment]
[talib-bbands.txt](https://github.com/askmike/gekko/files/818773/talib-bbands.txt)

**Comment by askmike** [comment]
I think I figured your problem out:

There was a bug in Gekko that caused Gekko to not correctly pass data to (for bbands) TAlib, I fixed that now.


Also: You were expecting these properties:

    var lower = result['outRealLowerBand'];
    var medium = result['outRealmediumBand'];
    var upper = result['outRealhighBand'];

However, Talib returns these properties:

    var lower = result['outRealLowerBand'];
    var medium = result['outRealMiddleBand'];
    var upper = result['outRealUpperBand'];

This way your method will have the values lower, medium and upper filled. Let me know if that fixes your problems!

**Comment by thegamecat** [comment]
Ah I didn't have an issue, the values were all be returned just fine.

What I'm confused about is how do I see those values over time to see if a trend has changed? 
Or in more reasonable terms for me (the noob) - what do I do with this ? :)

**Comment by askmike** [comment]
So different people have different opions about indicators and how to interpet them, you picked an interesting one, according [to wikipedia](https://en.wikipedia.org/wiki/Bollinger_Bands#Interpretation):

> Some traders buy when price touches the lower Bollinger Band and exit when price touches the moving average in the center of the bands. Other traders buy when price breaks above the upper Bollinger Band or sell when price falls below the lower Bollinger Band.

A lot of indicators (like MACD) are more generally agreed upon as to how to interpet them, but let's say you want to build your trading method with bbands so that:

1. buy when price touches the lower Bollinger Band
2. exit when price touches the moving average in the center of the bands.

For this you basically need to know 3 things:

- `var price = candle.close`
- `var lower = result['outRealLowerBand'];`
- `var medium = result['outRealMiddleBand'];`

And with simple if checks you can check whether the market satisfies those conditions. You can use thresholds if you see that the conditions are met way to often for example.

After writing those if checks in your `check` function you can do `this.advice..` as soon as they are true. And Gekko will run the check function on every candle and handle the advice (whatever you have configured to be listening to it, eg. paper trader or real trader).

----

EDIT: you want to have some state in there to keep track of the current advice you gave (eg. currentTrend) so that you won't be advicing the same thing the whole time.

**Comment by thegamecat** [comment]
Thanks for your help. Really useful. I now get exactly what's happening. I think Bollinger is not necessarily the right place to start but it's taught me a lot about how methods work in gecko.

**Comment by AdityaNayak** [comment]
Hey @thegamecat was the code in your file working at your end? 

I tried running it and this is the error that I get:

```
/Users/AdityaNayak/Bots/trading/gekko/strategies/bbands.js:26
  var customBBSettings = settings.parameters;
                                 ^

TypeError: Cannot read property 'parameters' of undefined
```

Any help on what needs to be done, would be helpful.

**Comment by thegamecat** [comment]
You need to ensure your stratname is setup and has a corresponding entry in the config file.

**Comment by AdityaNayak** [comment]
Yup. Did that, any other pointers?

**Comment by thegamecat** [comment]
Look at what settings is being set to and why it isn't being found.

**Comment by AdityaNayak** [comment]
My apologise for not updating this thread earlier. I got it to work. It was a syntax issue. :)

**Comment by thegamecat** [comment]
Excellent, good job.

**Comment by hmavrodiev** [comment]
2017-11-23 21:59:44 (INFO):              Using the strategy: talib-bbands
{ optInTimePeriod: 5,
  optInNbDevUp: 2,
  optInNbDevDn: 2,
  optInMAType: 0 }

/home/ubuntu/gekko-stable/core/talib.js:32
            throw talibError + methodName + ' requires ' + paramName + '.';
            ^
Gekko was unable to configure talib indicator:
        bbands requires optInTimePeriod.
  xxx POST /api/backtest 500 3,768ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/ubuntu/gekko-stable/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by askmike** [comment]
@stamun8 looks like your not passing that config object you are logging to the indicator. Can you post your strat's init method?
