### ISSUE TITLE
ta-lib

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#612]
Is it very necessary ?

**Comment by askmike** [comment]
No, unless you use a trading method that uses talib indicators. TAli is mostly for people writing their own strategies.

**Comment by Pascal66** [comment]
Just ask because when you start gekko (and when I'm following it) you asked someone for a Genetic Algorithm without ta-lib wich is incompatible for Win32) 
I wrote since a long time my own strategies.. Thank you

**Comment by askmike** [comment]
> you asked someone for a Genetic Algorithm without ta-lib wich is incompatible for Win32)

Ah yes, this was some exploring: This Genetic Algorithm never ended up in Gekko (mostly because of differences in how positions are taken in that project compared to how gekko deals with them). So right now you cannot use that in combination with gekko...

-----

> I wrote since a long time my own strategies.. Thank you

If you write your own you only need talib if you want to [add talib indicators](https://github.com/askmike/gekko/blob/develop/docs/trading_bot/creating_a_trading_method.md#indicators) to your method. If you don't use them it will not make a difference.

**Comment by Pascal66** [comment]
My fifferent point of vue is that this library need ta-lib that I cant use in Win.
It was a very very good way, but the owner never answerd even if he worked on a version without Ta-lib wich was a good start.

I just use my own strategie on old gekko without talib.
Thank you to answered
