### ISSUE TITLE
Genetic algorithm for gekko indicators

### ISSUE THREAD

**Issue by stonescenter** [askmike/gekko#661]
Hello

Is there an algorithm to setup the best configuration for each indicator or a combination of indicators to get the best profit,  a majority of time people lost time testing the best candle, history and parameter of an indicator. For example  a genetic algorithm to improve a fitness function or profit?. Any ideas to integrate? may I am wrong?

**Comment by askmike** [comment]
That is a great idea, I would propose the following (since speed will be of major importance):

1. Register to a new plugin that will store all candles in memory (to be used during the training)
2. Spawn X sets with (strat + paperTrader) at the same time (X = population size) and feed them all candles.
3. Select the best performer and mutate strat config based on that.
4. Go to step 2.

I do think it would be easiest to limit this to a single strat with specified parameters it can try to optimise. I won't have time for this for quite a while though.

**Comment by thegamecat** [comment]
I now have a GA up and running but tbh it isn't particularly useful because it take ages to run an epoch of 50/200. 

Multi CPU doesn't help, I've tried this on aws. 

I do have an i7700k now but i cant get talib working on windows or gekko working properly on bash on windows. So i will have to dual boot ubuntu to try and get the max speed from the CPU on gekko.

**Comment by askmike** [comment]
@thegamecat you are more than welcome to share your code, this questions comes up every once in a while and it would be great to show an example implementation.

This won't have priority from me for a while, so unless someone is willing to pick it up soon I don't think this will be implemented any time soon. I can def reopen once this changes!
