### ISSUE TITLE
Insane Simulation -- Can this happen for real?? Please just tell me that i am wrong please...

### ISSUE THREAD

**Issue by nozyqubis** [askmike/gekko#678]
![simulation_1](https://cloud.githubusercontent.com/assets/26750756/24826660/b4c8f6fc-1c43-11e7-86bf-ec3d38c4f57f.png)

2017-04-08 01:15:18 (INFO):	(PROFIT REPORT) amount of trades:		 1136
2017-04-08 01:15:18 (INFO):	(PROFIT REPORT) original simulated balance:	 0.03500000 BTC
2017-04-08 01:15:18 (INFO):	(PROFIT REPORT) current simulated balance:	 171.76453140 BTC
2017-04-08 01:15:18 (INFO):	(PROFIT REPORT) simulated profit:		 171.72953140 BTC (490655.80401150%)
2017-04-08 01:15:18 (INFO):	(PROFIT REPORT) simulated yearly profit:	 381.70510050 BTC (1090586.00143971%)

![sim2](https://cloud.githubusercontent.com/assets/26750756/24826840/85496ea8-1c47-11e7-9138-3f241173ffd5.png)

**Comment by askmike** [comment]
Woah, not sure. Some questions:

- What version (branch) of gekko are you running?
- Did you change the paper trade settings (especially the fee & slippage)? If not, what are they set to?

**Comment by nozyqubis** [comment]
Its the Latest Updated Version, i didnt change anything on paper trading, the fee is 0.25% as per poloniex.
I have let running live simulation on one of my VM, will update with the results.I am getting similar results fro different coins, for different timespan.

**Comment by askmike** [comment]
I mean the fee within gekko: if on the backtest page you click on "Change paper trader settings" they should exactly look like this:

![screen shot 2017-04-08 at 11 03 07](https://cloud.githubusercontent.com/assets/969743/24827933/186e763a-1c4b-11e7-89be-76b362fda6e9.png)

Please let me know if they look different.

**Comment by nozyqubis** [comment]
they are the same, i have set to 0 the asset and 0.025 the currency.The only i can think is that i have found the correct numbers :).

**Comment by askmike** [comment]
Could you please send me your database (file inside the history folder) to
mike@mvr.me

And let me know what strat you ran with what settings.

**Comment by Virkis** [comment]
I -may- be able to add some insight to this. I too noticed crazy gains just plugging in numbers which I assumed couldn't be right. After about 8 hours of plugging and backtesting at various timeframes, I came to something more reasonable and let a few gekkos at different strats go for about 8 hours after that. 


This is running a test on BTC/Doge with a strat that seems to be working pretty well, actually. It's set at 21 minute candles. However, the listed price on the left is incorrect.
![dogegekko](https://cloud.githubusercontent.com/assets/23392451/24830327/8eb610fc-1c49-11e7-9011-cd18c571137d.png)



This is the prices on Polonex for the last two days at 15 minute candles. It seems that gekko lists the price somewhere around 10 higher than the listed price. This happens with all three gekkos I have running paper. 
![dogepol](https://cloud.githubusercontent.com/assets/23392451/24830338/e3203b9a-1c49-11e7-81b2-981f5cda3768.png)


I'm not sure if this is possibly related to what's going on with @nozyqubis, and I'm also thinking that Gekko may not support such small prices, but I thought it may be worth mentioning either way. Weather or not this is usable still despite the 10~ discrepancy is yet to be seen. I was gonna put in a small chunk of Doge and let it actually trade for a while as the loss wouldn't bother me too much, but since I posted this I may just wait for your opinion on the matter.

This is running the most current stable I'm assuming, as I pulled less than 24 hours ago from Git.

**Comment by stonescenter** [comment]
Hello 

I saw your results, could you plaese share your strategy and what parameters you used. This is my address lord.ataucuri at ucsp.edu.pe

**Comment by askmike** [comment]
Gekko's backtester runs simulations based on very limited data, simply OHLC candles. Gekko does not take the spread and depth into account while backtesting (since this information is not available).

Judging by your screenshots you are backtesting over very small altcoin market. I just wrote some documentation explaining what could possibly go wrong:

https://github.com/askmike/gekko/blob/develop/docs/features/backtesting.md#simplified-simulation

**Comment by Virkis** [comment]
Nice, appreciate the write up. I figured it was a limitation of some kind as I assumed Gekko wasn't meant for smaller markets like these where the price generally stays -mostly- stable aside from the odd pump/dump. If it looks too good to be true, 99.995% of the time it usually is. :D 

But I didn't realize that Gekko only used OHCL candles as it's sole source. Were there any plans of having it interpret spread and depth? Or would that go beyond the initial idea/be too much to work out? Either way I'm fine with what it is. It's simply a tool to help people read the market, and through just backtesting and tinkering I've learned far more than I did years ago over  just reading up on the terms when bitcoin first got off the ground.

**Comment by askmike** [comment]
> But I didn't realize that Gekko only used OHCL candles as it's sole source. Were there any plans of having it interpret spread and depth? Or would that go beyond the initial idea/be too much to work out? Either way I'm fine with what it is.

Yes there were/are plans, the main reason is that it was always important for Gekko to behave 100% the same during backtests as well as on live markets. So Gekko only uses data that is actually stored (and can thus be used for backtesting). Unless you store a complete snapshot of the orderbook every minute, you will be estimating slippage anyway. So if you really want precision you need to store the full orderbook per minute which adds significant storage requirements (as well as code complexity for gekko to store/sync/read all this data).

Pros:

- Reliable backtesting for altcoins that are worth < 0.0001 BTC/USD (and have very low liquidity & volume). <- I am not sure if you want to automate these markets using TA strategies..
- Always more precision in backtesting <- I am convinced that people who want a certain amount of precision would not be running Gekko in the first place (it's written in javascript which is limited in precision due to floats).

Cons:

- Raises the bar for people who want to add an exchange (most supported exchanges were added by others).
- Requires more data to store (by at least a factor of 10, probably more).
- Makes everything a lot more complex.

-----

I'm very open to adding more data, it would just need to happen in a way that makes it optional (when monitoring), so that Gekko can figure out how much data is available.

**Comment by ghost** [comment]
what strategy did you use for this and what were the parameters

**Comment by askmike** [comment]
Documentation about what most likely happened can now be found here:

https://gekko.wizb.it/docs/features/backtesting.html#Simplified-simulation

**Comment by nozyqubis** [comment]
Hello everyone,
Mike is right, after spending many hours looking on charts and making new simulations and testing it, the conclusion is that if any of altcoin that we simulate with gekko doesnt have liquidity then one transaction can hit a low signal and another one can hit high signal.I have tested many strategy and spend many hours in the last week, so be careful and wish you a happy day.
P.S. The strategy i use regulary is RSI.
