### ISSUE TITLE
importing data slow on GDAX

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#691]
I tried importing a year of data from gdax and it was taking hours and only did 3 weeks? Is there a way to make this faster?

**Comment by askmike** [comment]
ping @smurfy 

I'll have a look as well.

**Comment by smurfy** [comment]
Problem is, its only possible to import 100 trades per request. Depending on the asset type and trade volume this is in fact slow :(.

There are other api endpoints available but they do not return the data in the format / with the infos gekko needs for import.

**Comment by saurabhbansal123** [comment]
do you have an offline data source which doesn't use poloniex API?  Downloading the data is a mess especially if I want to look into longer periods. Maybe users can pool in funds to get a database up?

**Comment by askmike** [comment]
there are some ideas about that, see #607 I also have some ideas about hosting data (see wizb.it)

**Comment by tuxitor** [comment]
I support the idea. Historical data from Bitffinex and Bitstamp and probably more are badly needed, because the exchanges lack of long term historical data via their API.

**Comment by saurabhbansal123** [comment]
@askmike Couldn't find much from the wizb.it website but is it going to be an open platform or users will have to pay to access the data. Is there a legal angle to hosting ?

I have a few other suggestions as well on the hosting/data import side.

a.) does the pot pull trade level data from Polo? Looking at the pull speeds it does seem like trade data. --> Polo also provides candles, will it be easier(quicker) to fetch 1 hour/15 minute candles?

b.) are you looking for any contributions/collaborators for the projects - the bot or the data hosting service?

I find the concept and the active development overwhelming. I am a Data scientist and have a fledgling interest in crypto since the last few months. I intend to use the data and come up with statistical models using standard trading signals/indicators and machine learning.

**Comment by askmike** [comment]
> @askmike Couldn't find much from the wizb.it website but is it going to be an open platform or users will have to pay to access the data.

Not sure! Have a ton of ideas of what to do with it, but kind of undecided (since I'm pretty busy these days). I want to host it for free but unsure.

>  Is there a legal angle to hosting ?

I guess if you put some heavy disclaimers on there about how it might be not correct and it's for demonstration purposes only you'd get pretty far. There are some sites selling this data.

> a.) does the pot pull trade level data from Polo? Looking at the pull speeds it does seem like trade data. --> Polo also provides candles, will it be easier(quicker) to fetch 1 hour/15 minute candles?

It pulls trade level data, because the (minimum) candles offered by polo are 5 min, and gekko uses 1 min candles.

> b.) are you looking for any contributions/collaborators for the projects - the bot or the data hosting service?

the bot most definitely, I have been working on 0.5 for a while (see #653 and #737), but very busy unfortunately :(

> I find the concept and the active development overwhelming. I am a Data scientist and have a fledgling interest in crypto since the last few months.

Maintaining gekko is pretty overwhelming haha, esp if I only do it in my free time.

> I intend to use the data

I would highly recommend using Gekko to import and store data (and run a live gekko per market to keep data up to date). You'll end up with 1min candle data in a database (sqlite default, gekko also supports postregsql and some others that might be out of date). Just import these and use python or whatever you want for data analysis. If you rather work with csv or so let me know and I'll provide some scripts to transform data.

The TA environment gekko provides is very basic: it only supports a single market at a time and order execution simulation is limited as well. Gekko is more of a "quick getting started kit" that sets up a very basic and simple environment - provides some stats about performance of simple algos (profit, sharpe, etc).

If you want to continue this discussion, please create a new issue!

**Comment by askmike** [comment]
I am actually closing this:

gdax are slow and will be until we provide a way to get data from somewhere else.

**Comment by mattgarmon2018** [comment]
Hello.  I trade the CME Bitcoin contract (i.e., cash-settled, regulated futures contract on Bitcoin); which is referenced via the CME-designed 2 price index products: the BRR (Bitcoin Reference Index); which is the equivalent of the 'spot market' price of BTC & the BRRR (Bitcoin Realtime Reference Rate); which is a live price index product which is calculated (if anyone is interested in the full back-history on the design of these 2 products; please call me @ 347-346-0077) via an aggregation of bitcoin price data from [X X X X?] exchanges, I believe in theory.  I am *not sure* if it is utilizing the actual bitcoind block-chain transactions to determine this price.  

Now, the BTC product itself, which is the futures contract that you trade; is quite impressive.  

I'd like to up the power of the gekko platform (and am privately; in experimentation)... 

My comment here is:  These "Exchanges" that people are "trading" cryptocurrencies on; like GDAX, are somewhat of a joke.  How long does it take to go in and out of a trade, and can you short on these exchanges; or not?

Anyway; excited to make a lot of money in Bitcoin and any other cash liquid product in general.  I just don't have the patience for the exchanges unless you can trade intra-day.

**Comment by xFFFFF** [comment]
When someone has unearthed an old topic, he will advertise my repository. :)

A ready database with the history of all exchange available in Gekko can be downloaded from my Google Drive. All details are here: https://github.com/xFFFFF/Gekko-Datasets

The databases are updated once a day. Available files with full history or last 7, 14, 30 or 60 days.
