### ISSUE TITLE
Added Gemini in exchanges folder and exchanges.js, it's not showing up. 

### ISSUE THREAD

**Issue by US-Mining-Rentals** [askmike/gekko#712]
Am I mssing something? Where do I go to expose the new object

**Comment by askmike** [comment]
Awesome! I'd love to see a PR for this if you like to share (you don't have to as per license).

The docs for exchange addition were written before the UI, if you want the exchange to be visible there you need to recompile the UI (single page web app). How to do that is explained here:

https://gekko.wizb.it/docs/internals/gekko_ui.html#Developing-for-the-Gekko-UI-frontend

**Comment by KevTheRev13** [comment]
Hi @askmike 

Did you ever receive a PR for this?

I think Gemini's API is almost exactly the same as Bitfinex (https://docs.gemini.com/rest-api/#introduction). It might be as simple as updating names, comments, and the capabilities. 

I plan to give it a try if I have a minute. How do you recommend I test it out before sending the PR? Just run a high-frequency paper trader + a traderbot in a funded test account, and check logs to make sure everything looks good?

Or is there some JS equivalent of a Junit or Mockito test you are using?

**Comment by askmike** [comment]
Hey!

No, I've never received a PR for gemini.

> How do you recommend I test it out before sending the PR? 

I usually use these strategies to force buy and sell actions (first one does it once, second one keep toggling):  https://gist.github.com/askmike/3031ea7aa587b61e20e38238cdcff770

> Or is there some JS equivalent of a Junit or Mockito test you are using?

I am using [mochajs](https://mochajs.org/) for unit tests, however there are currently only unit tests for some core components. We are currently not unit testing exchange integrations since it's a lot of work ton keep them up to date (and if an exchange API changes the integration breaks anyway).
