### ISSUE TITLE
Live trading

### ISSUE THREAD

**Issue by kza95** [askmike/gekko#714]
Not really a feature request since the gui gekko says live trading not yet available....just was wondering what the timeframe for it being implemented is.

**Comment by askmike** [comment]
On the roadmap! See #653 :)

Unfortunately I cannot give a timeframe since I work on Gekko whenever I have spare time (besides my full time work). Note that Gekko is open and free for everyone and I get don't get anything in return. This also means that anyone can contribute, if someone needs any guidance on how to add live trading (a few things need to happen) let me know!
