### ISSUE TITLE
Fresh import from poloniex results in duplicate price on 10 minute candles using talib

### ISSUE THREAD

**Issue by generalectric** [askmike/gekko#728]
I get the same results using both sqlite and pgsql on every currency tested though the output in the gist and config, import date ... is for ETC.... 

I'm getting candle price from this.lastPrice and writing using log method... each candle should have a difference price correct?

i made a gist with some output, my config settings, and the strategy that was slightly modified to include price output.

https://gist.github.com/generalectric/46643e3d790796408090c2ab42e0d6bc

**Comment by generalectric** [comment]
Ok I narrowed it down.... It is not pgsql or sqlite as the candle price works fine switching to native indicators. This is a talib issue. I posted additional details in the gist.

**Comment by askmike** [comment]
Nice find! This is very related to #715, basically the same bug but for another property.

`this.lastPrice` was very old, and I forgot that I used that in the strategies. It works great with Gekko's native indicators, but it might not be reliable in strategies that use talib because of async race conditions. I now removed it completely. You can use the candle passed to the function (log, check and update) if you need to know the last price.

Can you check the develop branch? It should be fixed there.

**Comment by thegamecat** [comment]
That's interesting, what was this.lastprice? Was it the previous candle price?

**Comment by askmike** [comment]
Well it was supposed to be the price of the "current" candle (close prop on default). But it's very old internal code that wasn't used internally but apparently used in all the example strategies.

It works fine with sync indicators (all example strats except for talib-macd), but is not guaranteed to work in talib (see #715 for a description of the same race condition). So you shouldn't use it, just use the candle passed to your check, log and update functions. I also removed it in the develop branch.

**Comment by generalectric** [comment]
I didn't realize we stopped using this.lastPrice. I'm still using my strategies from older gekkos so the old code came along with them. I Switched to candle.close and it works as expected. Appreciate you Mike thanks again, keep up the good work!
