### ISSUE TITLE
Cannot backtest in UI if dataset is too big

### ISSUE THREAD

**Issue by torroferri** [askmike/gekko#744]
Hello!

I'm running Gekko in an ancient Raspberry Pi B+ and I'm getting some problems to get strategies backtested through the UI. If I reduce the dataset enough, it works, but anything bigger than one month does not. I don't any error in the browser, nor in the ssh console. After a while the message "running backtest" dissapears... Any ideas? 

Thanks a lot in advance!

![captura1](https://cloud.githubusercontent.com/assets/7229046/25968370/81109a3c-3691-11e7-9a51-bef2e0d47a9f.PNG)
![captura2](https://cloud.githubusercontent.com/assets/7229046/25968449/d1c798a4-3691-11e7-8c62-7934dd2f95c4.PNG)

**Comment by askmike** [comment]
Could you check your browser console, if you use chrome can you go to:

- right click on page - click inspect element
- network tab
- at the bottom there should be a request called `backtest`, if you click it and go to response do you see anything?

**Comment by torroferri** [comment]
I hope this is enough information. If you need something else, just let me know. 

Thanks a lot! 


![captura1](https://cloud.githubusercontent.com/assets/7229046/26024512/c712f0e2-37d2-11e7-9fff-5e50af5524d0.PNG)
![captura2](https://cloud.githubusercontent.com/assets/7229046/26024510/c710731c-37d2-11e7-8d3e-838566348450.PNG)
![captura](https://cloud.githubusercontent.com/assets/7229046/26024511/c711f610-37d2-11e7-9fea-d132499e4a45.PNG)
![captura3](https://cloud.githubusercontent.com/assets/7229046/26024513/c713a0dc-37d2-11e7-8dac-1a640db6ee4b.PNG)

**Comment by askmike** [comment]
Ah yes: the problem has to do with the UI communicates with Gekko. The way it is currently setup the backtest needs to be finished within 2 minutes or it will fail (what you are seeing now). We can change the communication channel to get around this (from REST POST call to websocket), but that will take some time.

As for now you'd need to get the backtest time down to under 2 minutes, workarounds are:

- Make sure the data history of gekko (default `gekko/history`) is on the SD card of the pi (instead of a slow USB harddrive or a network drive) - the slowest thing about backtesting is getting historical data from disk (assuming you are not using a really slow custom strat).
- make the daterange smaller (you can also run two backtests over half the time)
- make the candle size bigger

Let me know how that goes! I'll leave this issue open until I implement a proper fix.

**Comment by thegamecat** [comment]
I think I posted a solution that extends the timeout variable, but I forget where it's documented. It's against one of the issues.

**Comment by rockbit** [comment]
I have got the exactly same issue backtesting on a raspberry pi, im pulling the git since months and hoping for a fix all the time :) Good to know what the issue is. The problem sounds quite simple, there must be a way to fix it for normal sockets. Please fix this, it makes gekko backtesting unusable for raspberry pi

**Comment by thegamecat** [comment]
There is a timeout setting which helps.

**Comment by rockbit** [comment]
do you know where the setting is? I searched with grep and looked into some files, but could not find it.

**Comment by thegamecat** [comment]
There is a similar issue here where I documented it, easier to link I think:
https://github.com/askmike/gekko/issues/686

**Comment by rockbit** [comment]
awesome it works. Thank you so much @thegamecat
@askmike thanks for your work, please add fix to repo

**Comment by bsliran** [comment]
setting timeout directly on the server also seem to solve the problem.
on web/server.js:
server.setTimeout(60 * 60 * 1000); // one hour

**Comment by askmike** [comment]
Ah yes, I think @thegamecat spotted that as well at some point. I am very open to a PR for this :)
