### ISSUE TITLE
Error "UnhandledPromiseRejectionWarning"

### ISSUE THREAD

**Issue by KimHono** [askmike/gekko#749]
While trying a backtest with a TAlib strategy, this error appears : 
`
        Gekko v0.4.10
	I'm gonna make you rich, Bud Fox. 

TAlib is enabled
Serving Gekko UI on http://localhost:3000/

(node:3635) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
`
I've tried to reinstall npm, with no effect. My OS is Debian.

**Comment by askmike** [comment]
You can ignore that error, it is caused by Gekko automatically wanting to start a browser window to open Gekko. But it can't on a server (because there is no browser). To remove that, set headless to true in the UI config.

See here for details: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#Configuring-Gekko-to-run-headless-in-a-trusted-environment
