### ISSUE TITLE
Candles are not being created when there are no trades

### ISSUE THREAD

**Issue by andreialecu** [askmike/gekko#773]
I have a strategy with candle times of 2 minutes, and sometimes there can be up to 10 minutes without a trade. For these 10 minutes there will be no candles created, and the strategy isn't called. 

When there is a trade, a sudden rush of candles will come, for the duration that was missed. If the strategy is supposed to stop loss after n candles, for example, this will make it delay the advice until the next trade is available, resulting in further potential losses.

Candles should come regardless of trades being made.

**Comment by askmike** [comment]
The problem is that trades might be delayed or the exchange API might return errors. When this happens should Gekko assume no trade was made and make empty candles? What if later it turns out that there were trades in the time Gekko assumed there were none?

There are a few exchanges that don't report trades up until multiple seconds / a few minutes during very volatile times.

----

Note that most TA strategies operate on hourly candles (or bigger), so this is only really a problem if you build strats around minutely candles (or trade on markets without volume). In that case I don't think Gekko can help you at all (since you probably want to act on a livestream of candles or so).

**Comment by andreialecu** [comment]
I see.

I guess it might be worth it to have this as a configurable option. 

It seems easy to implement, just emit a new `trade batch`, but with empty data whenever the exchange is queried and doesn't return any new trades. Right now all the functions return early when this happens, so candles are not created.

**Comment by askmike** [comment]
>  Right now all the functions return early when this happens, so candles are not created.

Yes, this is by design.

> It seems easy to implement, just emit a new trade batch, but with empty data whenever the exchange is queried and doesn't return any new trades.

As stated above: keep in mind that if I query an exchange at 12:00:00 and also at 12:00:05 I might only get trades that happened at 11:59:55 on the second poll. In some exchanges this is a lot worse than other exchanges. So implementing what you suggest would mean making a choice of after what time Gekko "should" consider the candle to be empty.

And if the assumption turns out to be wrong the "wrong" candles are not just emitted to strategies, they are also stored "wrong" on disk forever (Gekko has no way to purge persisted market data). Another disadvantage here is that Gekko tries to be as deterministic as possible: if you run we both run a gekko with the same settings, we should get exactly the same results. If you send me historical data from your Gekko that should be the same as if I were to have run the Gekko myself. Introducing subtle options like this makes it a lot more complicated for everyone (what if you decided you wanted to have Gekko "guess" empty candles, this choice is now reflected in the data you send to me (it might include wrongly guessed candles, whilst I never made that choice and might not even be aware you made it).

--------

Gekko is not perfect, I have made a lot of decisions a lot of people don't agree with. It's meant as a framework/starting kit for people who want to write TA strategies without having to do all the exchange plumbing themselves. You are more than welcome to patch your changes in and submit a PR, but what you propose doesn't have only advantages imo so we'd have to weight out all the benefits against the disadvantages (most likely depend on proposed implementation).
