### ISSUE TITLE
can't import history

### ISSUE THREAD

**Issue by find-happiness** [askmike/gekko#781]
ERROR: The exchange OkCoin does not provide full history (or Gekko doesn't supp
ort importing it)

**Comment by askmike** [comment]
Unfortunately importing is only supported at some exchanges. This is partly because some exchanges flat out don't support providing historical data and partly because importing is not fully integrated for all exchanges.

See here for a list of what exchange support importing: https://gekko.wizb.it/docs/introduction/supported_exchanges.html
