### ISSUE TITLE
can be writed a strategy using the orderbook?

### ISSUE THREAD

**Issue by scidran** [askmike/gekko#791]
Hi.
I want to write a strategy using the orderbook datas... into live not into testmode... because i don't know if exist orderbook datas that i can download for test mode.
I would like to combine a RSI strategy with an other oscillator strategy and a buing and selling stategy into orderbook. But i'm not able to understand if it's possible or not.

**Comment by thegamecat** [comment]
Go into local data on Ui then import data. Then backrest.

To combine rsi with an oscillator you need to write your own strategy.

**Comment by scidran** [comment]
Yes i know this...
But i want also to put a function that find if there are great movement placed into orderbook and stop or start my stategy before this order take exchange...
I need to verify orders volume into the order book before that the order is taked from the exchage company.

**Comment by askmike** [comment]
Unfortunately the choice was made when designing Gekko to not include orderbook data. The main reasons are:

- There is definitely value in orderbook data, but because of arbitrage (triangular, inter-exchange) just looking at a single orderbook won't get you very far.
- All orders can be pulled, so there is a ton of noise in the orderbooks because of people trying to show depth that is not really there.
- Within Gekko strategies should behave 100% the same under backtest as against the live market, so this means Gekko should also store orderbook data, which automatically means either snapshotting (=losing precision to save data) or storing all updates (=gekko would store a ton of data)
- Ignoring makes it a lot easier to store market data, as Gekko supports a huge number of exchanges that have very different ways of providing orderbook data (if any).

So this means that when writing a strategy for Gekko you cannot look at orderbook data. The strategy merely suggests what position you should take and it is up to the portfolio manager to execute orders (the PM will look at the top of the book - note that this behaviour is changing in the next release of Gekko).

Feel free to respond here, but I am closing this since it is an active design decision.

**Comment by scidran** [comment]
ok thanks
