### ISSUE TITLE
Error importing data from Kraken

### ISSUE THREAD

**Issue by uxdxdev** [askmike/gekko#825]
Why am I seeing this? 

![gekko error](https://user-images.githubusercontent.com/3397660/27842579-112fe69a-6103-11e7-849d-26ea530b6f3c.png)
![gekko error console](https://user-images.githubusercontent.com/3397660/27842580-1130e518-6103-11e7-9c0b-b456fc1aef87.png)

**Comment by askmike** [comment]
Importing means downloading historical market data directly from an exchange. In order to do this the exchange must support this - and in an easy consumable format by Gekko.

Here you can see which exchanges Gekko can import historical data for: https://gekko.wizb.it/docs/introduction/supported_exchanges.html

*Kraken does provide OHLC data (the market data Gekko would need), but Gekko currently does not have the functionality to import this - since other exchanges expose this data differently. Maybe in the future someone can add this to Gekko.*

**Comment by uxdxdev** [comment]
Ok great thanks.

**Comment by askmike** [comment]
Note that you can run a live gekko - market watcher to have Gekko watch the live market. If run one for a week you'll have a week of "historical data" to backtest over.
