### ISSUE TITLE
Multiple market watches via command line

### ISSUE THREAD

**Issue by Demannu** [askmike/gekko#849]
Greetings!

Great work on Gekko so far, I'm hoping to present a PR or two in the following days. I have read through most of the code and documentation, however I'm unsure from the command line how to create multiple watchers and perhaps multiple trade advisors from a single application start.

Currently I'm running 2 separate instances of Gekko, one for CryptoA and one from CryptoB but I would like to combine them if possible into a single instance.

**Comment by mcowger** [comment]
As it stands right now, from the CLI, you need 2 starts.

**Comment by askmike** [comment]
Gekko commandline instances are pretty light, so running a few shouldn't not be a problem. If you create a PR please use a design similar to the UI: create a common (CL) interface that only controls, but run the actual watchers in child processes ("workers").

Note that right now all gekkos are managed poorly in the UI. I started on a "gekko manager" that properly manages all running Gekkos (instead of [this big file](https://github.com/askmike/gekko/blob/stable/web/routes/startGekko.js)), if I ever get around finishing that up it could be used as a backend for whatever interface to control gekkos.

I am closing this as I don't see it as a pressing issue, but love to see more discussion and/or a PR.
