### ISSUE TITLE
Trend duration

### ISSUE THREAD

**Issue by Tatara88** [askmike/gekko#851]
Is there a built in method for keeping track of the trend duration for custom strats or do I need to code in some way to track it? And if i do need to code it in any ideas on a good way to approach it?

**Comment by askmike** [comment]
Not at this moment, I have a few ideas of creating common functionality (besides indicators), but nothing is implemented yet.

> And if i do need to code it in any ideas on a good way to approach it?

Easiest would be:

In your check method, as soon as you trigger a new advice register the time:

    this.adviceTime = candle.start;

And when you want to see the time since this moment:

    var minutesSinceLastAdvice = candle.start.diff(this.adviceTime, 'minutes')

Note that the candle.start property is a moment object, so you can use all methods provided by momentjs: https://momentjs.com/docs/
