### ISSUE TITLE
Disconnected message on develop branch ui

### ISSUE THREAD

**Issue by onehit** [askmike/gekko#881]
Hi, I'm trying to get this working on a headless server with nginx as a reverse proxy. I am able to connect from a remote location to the ui, but immediately get a Disconnected message. Gekko is running on port 3000 with a reverse proxy from port 993 (successfully accessed through http://myserver:993/). The Inspect console says it can't connect to http://myserver:3000/api/imports.

Two things... where does it get the /api/ folder, as it doesn't appear to be in my gekko directory, and why is it trying port 3000?

Thanks

**Comment by askmike** [comment]
Hey,

When you start the node gekko process you start a webserver that will set up an api (responds to `/api/x` calls). It also starts up a browser with a frontend connecting to this API.

> where does it get the /api/ folder

The `/api` path does not correspond to any files, it's just there to tell the webserver what information the frontend needs.

> and why is it trying port 3000?

That's the default.

------

If you want to reverse proxy Gekko you want something like this:

    [ frontend UI ] --[host:port]--> [ reverse proxy (nginx)  ] --[host:port]--> [ gekko webserver ]

What you need to do is edit the UIconfig.js file located here: gekko/web/vue/UIconfig.js and edit it so that it reflects the host:port you want the frontend to connect to as well as the host:port you want the backend to listen on. See this page for an example (under `Configuring Gekko to run in the cloud` ): https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#Configuring-Gekko-to-run-in-the-cloud
