### ISSUE TITLE
Backtest: 0 trades but Simulated Profit lower than Market profit

### ISSUE THREAD

**Issue by rasmuswinchester** [askmike/gekko#883]
Hi,

While playing around with the backtesting, I encoutered the following:

Did a backtrade, which resulted in 0 trades made. However, the simulated profit was 37.09981% while the market ended at 40.04805%. 

Is this possible? Does Gekko assume there are fixed costs for the trading platform? 

Thanks in advance. 

![trade strat](https://user-images.githubusercontent.com/30421972/28549700-47ffae76-70b2-11e7-8e08-a008e1f69936.png)
![backtest resukt](https://user-images.githubusercontent.com/30421972/28549699-47fda720-70b2-11e7-8566-0030de359654.png)

**Comment by askmike** [comment]
The paper trader has a simulated balance: if your simulated balance has at least some currency the total worth will be less than the market (buy and hold profit). Example

If you are trading USD/BTC and the price for 1 BTC is 1000 at the beginning and 2000 at the end:

Under simulationBalance you configured the paper trader to have 1 BTC and 100 USD. So value at the beginning is: `1000 + 100 = 1100 USD`, and the value at the end is (assuming no trades) `2000 + 100 = 2100 USD`. So even though the market went up 100% your balance did not since you had some USD.
