### ISSUE TITLE
Back testing: slippage what should it be really?

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#887]
As I understand it, it would appear that the default setting for slippage is 0.05%.

  // how much fee in % does each trade cost?
  fee: 0.25,
  // how much slippage/spread should Gekko assume per trade?
  slippage: 0.05,

And this is used in this calculation to work out the total fee of a trade:
  this.fee = 1 - (calcConfig.fee + calcConfig.slippage) / 100;

Which means by default the fee is 0.003, which is then reversed to give a multiplier of 99.7%.

If I have understood the above correctly shouldn't slippage be 5 and not 0.05?

Indeed is 5% the "right" slippage?

**Comment by thegamecat** [comment]
Have I understood the mechanic correctly?

**Comment by askmike** [comment]
Yes, you are right. Though slippage is currently not an issue since (the new trader in) Gekko will place orders on the top of (your side of) the book. But in reality you almost always have to move this a few times (similar effect to slippage).

If you want you can go to these two pages:

- https://github.com/askmike/gekko/blob/develop/config/plugins/paperTrader.toml
- https://github.com/askmike/gekko/blob/develop/sample-config.js

And press edit and update the numbers. This will create a pull request :)

**Comment by thegamecat** [comment]
Thanks for the guide!

I'm not going to change anything because I'm not clear on what the values should be, once 0.5.0 is in stable I'll start playing with it in live and the new trader mechanism.

I actually wrote my own buying and selling mechanism in the trader based on a % either side of the buy/sell price but found that wasn't really effective so really looking forward to trying out your new version.

**Comment by askmike** [comment]
Note that the new trader is new and very basic: it won't make aggressive orders, which means buying and selling will be very slow as Gekko will wait for a buyer (in case of selling) or a seller (vice versa). So if your strat trades more than once every ~20 minutes (depending on market) it might not have executed the trade before the new advice comes in.

**Comment by thegamecat** [comment]
Ok I will take a look at the logic tomorrow. Most of my strats are based on 1m but are not high frequency. I have tried a few that have been high freq but they fail miserably in live because of this exact subject.
