### ISSUE TITLE
Adding exchange to application

### ISSUE THREAD

**Issue by Yamakaza** [askmike/gekko#892]
Hi I'm having issues when trying to add an exhange.

I followed the step in https://gekko.wizb.it/docs/extending/add_an_exchange.html but after recompiling th e UI the exchange is not added to the dropdownbox. I tried to see what the effect is of the exchange.js files in the exchange folder. When i remove some of the standard exchanges and then recompile the ui the dropdownbox stops working.

![image](https://user-images.githubusercontent.com/30527407/28717337-aa8f15b2-73a1-11e7-93f2-236c73e38d68.png)

Any idea on how to proceed?

**Comment by askmike** [comment]
Hey @Yamakaza,

Since #750 you don't need to recompile the UI anymore (but instead restart the node process). I will update the documentation to reflect this.

If you added an exchange to the exchange folder that exposes a getCapabilities method, you can start the UI and browse to `http://localhost:3000/api/exchanges` to get a JSON list of capabilities for every exchange. Can you let me know if that is still working? And if not if there is any error or so?

**Comment by Yamakaza** [comment]
Hey @askmike thank you for reaching out to me so quick. My exchange has the getCapabilities method but is not showing up in the exchange list. Also I don't seem to find the exchange the api/exchanges.

I tried removing that function from another exchange and restart the node and that removes it from the list. Gekko just reads the JS files in the exchanges folder right? And checks if they have that function? 

Can you help me out? :)

**Comment by askmike** [comment]
Here is method for the `api/exchanges` call: https://github.com/askmike/gekko/blob/stable/web/routes/exchanges.js

So yes, what it does is: look at all files inside the exchanges folder (that end with `.js`) and tried to load them. If it is possible to call `getCapabilities()` on the trader inside it will be added. If you post the exchange file here I can help debug.

**Comment by askmike** [comment]
Let me know if you have any more information.
