### ISSUE TITLE
Shows double "Live Watchers" and "Strat Runners"

### ISSUE THREAD

**Issue by ElscottHavoc** [askmike/gekko#894]

**Comment by ElscottHavoc** [comment]
Whenever I start a Live Watcher or Strat Runner, it shows up as a duplicate in the list and seems to be doing a double process.

**Comment by askmike** [comment]
Yea I noticed that, goes away when you refresh. Will try to debug soon :)

**Comment by Thunderbelch** [comment]
This also happens in command line mode. After I launch it I sometimes see several candles processed the instant the strategy starts running. What makes this a very serious problem is the fact that those extra candles don't show correct real-time data, but seem to somehow remember prices from previous runs on the same market. This can cause a strategy to trigger incorrect advice on launch!

**Comment by Thunderbelch** [comment]
The problem gets progressively worse over multiple runs, no matter how far apart. It always loads a bunch of old candles at startup. The fix for now is to check the candle age in the update() function of your strategy script, which would obviously not work for back-testing:
`
if ((candle.start._i + 1000*60*3) < Date.now())
{
	log.info("======= Skipping invalid/outdated candle =======");
	return;
}
`
