### ISSUE TITLE
BudFox - Advanced Usage question

### ISSUE THREAD

**Issue by kbimplis** [askmike/gekko#896]
I'm following the documentation on gekko internals and particularly BudFox.

How can I utilize the usage example? Which file do I edit/create with the following?  ( example from docs quoted below)

Thank you so much in advance.

> 
> var config = {
>     exchange: 'Bitstamp',
>     currency: 'USD',
>     asset: 'BTC'
> }
> 
> new BudFox(config)
>   .start()
>   // convert JS objects to JSON string
>   .pipe(new require('stringify-stream')())
>   // output to standard out
>   .pipe(process.stdout);  
>

**Comment by thegamecat** [comment]
Out of interest what are you trying to do?

**Comment by kbimplis** [comment]
I'm trying to do a custom export of BudFox data and take advantage of the fact that gekko already knows how to communicate with various exchange APIs.  I could then feed the data to another tool.

**Comment by thegamecat** [comment]
Ah-ha, I had not realised that was possible. Interesting.

**Comment by askmike** [comment]
Hey @kbimplis! Great question:

Here is a gist, if you place that in your gekko root it will work: https://gist.github.com/askmike/4ed86723f6b13895eed9e234fdd1425a

You can move it anywhere else if you want but you need to update the `pathToGekko` var to match.

----

When you run this code BudFox will connect to an exchange and every time there is a new 1 minute candle pump it over stdout (your terminal / command prompt).

----

Since I wrote those docs a few bug fixes now require some verbose stuff (everything with a `temp..` comment at the end. If you want let me know and I can fix those, might make the code a bit cleaner.

**Comment by kbimplis** [comment]
@askmike,  much appreciated. That did the job, thank you!
