### ISSUE TITLE
Insert Data to sqlite is too slow.

### ISSUE THREAD

**Issue by flier268** [askmike/gekko#933]
you can see this,it can solve this problem.
http://blog.darkthread.net/post-2017-07-16-sqlite-insert-slow.aspx

**Comment by askmike** [comment]
Hey, the article talks about sqlite in C#, Gekko is a javascript (nodejs) project and we are using this sqlite library: https://github.com/mapbox/node-sqlite3

Reading that article it is not very clear to me what the slow bottleneck is in that example (is it the C# sqlite implementation, or something else?). I am aware that the schema design Gekko uses as well as some other implementation specific details are very slow. Have you encountered problems because of slow inserting in Gekko so far?

**Comment by flier268** [comment]
I think this problem is the same
I search in the node-sqlite API, I found this code,maybe is the answer

  'insert with transaction': 
function(finished) {
        var db = new sqlite3.Database('');

        db.serialize(function() {
            db.run("CREATE TABLE foo (id INT, txt TEXT)");
            db.run("BEGIN");
            var stmt = db.prepare("INSERT INTO foo VALUES (?, ?)");
            for (var i = 0; i < iterations; i++) {
                stmt.run(i, 'Row ' + i);
            }
            stmt.finalize();
            db.run("COMMIT");
        });

        db.close(finished);
    }

by the way,i have never learn npde-js,so i am nog sure it is right，you should test yourself
