### ISSUE TITLE
[NEW FEATURE] store roundtrips in CSV

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#978]
This would be new plugin. If you specify Gekko to store roundtrips in CSV it will generate a new CSV file on start and store all roundtrips in it.

**Comment by thegamecat** [comment]
I think it needs to write all the data that is processed and allows people to put indicator outputs as well - and it needs to be per tick. 

The roundtrips are useful too.

**Comment by decoye** [comment]
id love this

**Comment by thegamecat** [comment]
This is how I've implemented it (I haven't done a PR because I am sure there are better ways).

Config.js:

config.writer = {
	enabled: true,
	logpath: "/mnt/f/bash/gekko052/gekko/strategy_logs/"
};

Logger.js:

Line 14

var writecsv = config.writer.enabled;
var logpath = config.writer.logpath;
if(writecsv===true){
	var fsw = require('fs');
	var grtimestamp = '';
	var grreadtime = '0';
	var outtxt = '0';
	var headerset = '';
	var headertxt = '';
	var csize = config.tradingAdvisor.candleSize;
	var exchange = config.watch.exchange;
	var currency = config.watch.currency;
	var asset = config.watch.asset;
	var strat = config.tradingAdvisor.method;
	var filetime = new Date().toISOString();
	filetime = filetime.replace(/:/g, "-"); 
	var obvoutput = 0;
	var fname = logpath+strat+"-"+csize+"-"+exchange+"-"+currency+"-"+asset+"-"+filetime+"-roundtrips.csv";	
}





Then in new line 85:
var writecsv = config.writer.enabled;
if(writecsv===true){
  headertxt = "Entry at,Exit at, Entry price, Exit price, Entry balance, Exit balance,Duration,PnL, Profit\n";
  outtxt = rt.entryAt.format('YYYY-MM-DD HH:mm')+","+ rt.exitAt.format('YYYY-MM-DD HH:mm')+","+ rt.entryPrice+","+rt.exitPrice+","+rt.entryBalance.toFixed(3)+","+rt.exitBalance.toFixed(3)+","+moment.duration(rt.duration).humanize()	+","+rt.pnl+","+ rt.profit+"\n";
  	

    if (headerset === "") {
        fsw.appendFileSync(fname, headertxt, encoding = 'utf8');
        headerset = "1";
    }
    // console.log(this.fname);
    fsw.appendFileSync(fname, outtxt, encoding = 'utf8');

	outtxt = "";    
}  
  

Then to write out all candles plus indicators in a strategy:

Just above var method={};

var writecsv = config.writer.enabled;
var logpath = config.writer.logpath;
if(writecsv===true){
	var fsw = require('fs');
	var grtimestamp = '';
	var grreadtime = '0';
	var outtxt = '0';
	var headerset = '';
	var headertxt = '';
	var buytime = "";
	var selltime ="";
	var csize = config.tradingAdvisor.candleSize;
	var exchange = config.watch.exchange;
	var currency = config.watch.currency;
	var asset = config.watch.asset;
	var strat = config.tradingAdvisor.method;
	var filetime = new Date().getTime();
	var obvoutput = 0;
	var fname = logpath+strat+"-"+csize+"-"+exchange+"-"+currency+"-"+asset+"-"+filetime+".csv";
}


Then at the end of update (assuming your logic is in there):

if(writecsv===true){	
	grreadtime = candle.start.toDate();
	headertxt = "date,price,roc,rsi,tmprsi,stochrsi,obvoutput,buys (USD),sells (BTC),ema20, ema50,ema100,ema200,emapercentage\n";
	outtxt = grreadtime+","+ price+","+ roc+","+ rsi+","+ this.tmprsi+","+ this.stochRSI+","+obvoutput+","+buytime+","+selltime+","+ema20+","+ema50+","+ema100+","+ema200+","+ emapercentage+"\n";
  	

    if (headerset === "") {
        fsw.appendFileSync(fname, headertxt, encoding = 'utf8');
        headerset = "1";
    }
    // console.log(this.fname);
    fsw.appendFileSync(fname, outtxt, encoding = 'utf8');

	outtxt = "";
	buysell = "";
	buytime = "";
	selltime = "";
}	

Roundtrips example:

[test-all-1-poloniex-USDT-ETH-2017-08-14T07-51-56.384Z-roundtrips.csv.txt](https://github.com/askmike/gekko/files/1236312/test-all-1-poloniex-USDT-ETH-2017-08-14T07-51-56.384Z-roundtrips.csv.txt)


All candles / trades:
[test-dmi-1440-poloniex-USDT-ETH-1502550698242.csv.txt](https://github.com/askmike/gekko/files/1236311/test-dmi-1440-poloniex-USDT-ETH-1502550698242.csv.txt)

Note:

The file name indicates:

Strategy used
Candle size
Exchange
Currency pair
Date / time (the example of all candles / trades is a little old, the date time is be humanized now)

**Comment by askmike** [comment]
This code isn't formatted, hard to see what is going on.

Anyway this functionality really needs to end up in a plugin that simply listens to an event coming from the peformanceAnalyzer (like a roundtrip). Also the sync file write ;)

**Comment by thegamecat** [comment]
I have no argument with that :)

Just putting this up for reference to show how I would see it working in terms of output / variables and not how it is all actually written. 

And I have validated that there is zero issue with writing the file with async :P

Finally, it would be good if someone can validate that round trip and calculations are actually accurate for a backtest.

**Comment by decoye** [comment]
my way of solving this was to make the trading advisor append to a txt file whenever he made a full trade. it was stupidly simple but it does the trick i needed it to do for me. i used fs, moment, and the variables he has in this moment, like currency and asset, formatted it alittle and i recieved detailed information about every transaction that he made.

**Comment by thegamecat** [comment]
Yep, but don't you want to see what the indicator values are?

**Comment by decoye** [comment]
no actually i dont, this is what i use the back test for. once i know this strategy has profits over more then 2 months of time im fine. i care about the profits monthly, depended if big changes in the profits happen, i got and adjust my strategy.

**Comment by decoye** [comment]
```
fs.appendFile('(ROUNDTRIP)', 'entry date\t\texit date\t\texposed duration P&L\t\t\tprofit');
  fs.appendFile('account.txt','\r\n' + display.join('\t') ,  function (err) {
  if (err) return console.log(err);
```

ive added this to my logger.js

**Comment by verbraucher** [comment]
I think this feature is already part in the gekko Quasar UI:
https://github.com/H256/gekko-quasar-ui
https://raw.githubusercontent.com/H256/gekko-quasar-ui/master/img/gekko-quasar-10.png
