### ISSUE TITLE
"GDAX trading fee will be: 0%" but should be 0.25%

### ISSUE THREAD

**Issue by GuyPaddock** [askmike/gekko#979]
* **I'm submitting a ...**
[x] bug report

* **Action taken** (what you did)
Started Gekko with trading active at GDAX.

* **Expected result** (what you hoped would happen)
[GDAX trading fee](https://www.gdax.com/fees/BTC-USD) is indicated at `0.25%` for trades under `4,664.47 BTC`.

* **Actual result** (unexpected outcome)
```
2017-08-16 09:38:35 (INFO):     trading at GDAX ACTIVE
2017-08-16 09:38:35 (INFO):     GDAX trading fee will be: 0%
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Current using `stable` branch.

**Comment by askmike** [comment]
Gekko will only add orders to the book, which means that Gekko will always be making which has a fee of 0.

If you encountered Gekko adding take orders please let me know because that would be a bug!

**Comment by GuyPaddock** [comment]
@askmike but the documentation I linked to from GDAX indicates:

> When you place an order at the market price that gets filled immediately, you are considered a taker and will pay a fee between 0.10% and 0.25% for BTC books and 0.10% and 0.30% for ETH books.
> 
> When you place an order which is not immediately matched by an existing order, that order is placed on the order book. If another customer places an order that matches yours, you are considered the maker and your fee will be 0%.
>
> When you place an order that gets partially matched immediately, you pay a taker fee for that portion. The remainder of the order is placed on the order book and, when matched, is considered a maker order. The fee is 0% for that part of the total order.

Doesn't that mean that the fee depends on what portion of the order added by Gekko gets filled immediately?

**Comment by askmike** [comment]
Yes it does, but Gekko will always (try to) stay on your side of the book. Meaning that it will place the order in a way where it will make the book:

<img width="328" alt="screen shot 2017-08-17 at 11 03 31" src="https://user-images.githubusercontent.com/969743/29407285-d346e4a4-833b-11e7-8cb1-7030f4eec56e.png">

if that is the state of the orderbook and gekko receives a BUY signal it will place an order at `3805.04` which is not matched immediately but placed in the book. This means that Gekko will place the order and check back later to see if it was filled (since it won't be filled immediately).

**Comment by GuyPaddock** [comment]
That's clever. Once again, thank you @askmike for your a detailed explanation.
