### ISSUE TITLE
Just my thanks

### ISSUE THREAD

**Issue by GuyPaddock** [askmike/gekko#981]
Hey, so, this isn't really an issue -- I just wanted to thank the maintainer(s) for an awesome trading tool. I know there's a lot you guys are working on with this, but I have to complement you -- this was a lot of work.

Before I knew about Gekko, I was thinking about writing something like this, but it would not have had even an eighth of the features you guys have. So often, trading software is proprietary, not open source and/or doesn't engage with its user community.

Keep up the good work!

**Comment by arnold-maderthaner** [comment]
word !

**Comment by askmike** [comment]
Thanks a lot! I really appreciate this. Gekko actually grew quite big from my own little hobby project:

> This project is a learning exercise of me, a student with some experience in programming (mostly web) and zero experience in economics and trading. I figured writing my own trade bot would be the best way to learn about implementing mathematical trading algorithms. So here is my very first attempt at anything related to trading / algorithmic decision making.

[(from the gekko README @ 2013)](https://github.com/askmike/gekko/tree/e6935f3dd50645e893a1765231e7c2caf21e64d8).

It only worked at Mt. Gox and it only did EMA calculations at the time haha (no paper trading, no backtesting, no storing of trade data, no UI, no calculating of profit, no plugins).

-----

It's been a long journey so far, but I am very glad to see what we all accomplished so far!

Though I do notice the amount of bugs that have been happening recently, and I want to update more conservatively from now own: The UI turned out a lot more complex than originally designed (and functionality wise it is still very limited). But I can't thank the help enough of all 81 contributers! Without everyone there Gekko would be a lot more buggy and limited in scope.

**Comment by alfredopalhares** [comment]
:+1: Love this tool!

**Comment by ghost** [comment]
I've enjoyed using gekko over the last week and am happy to see it's still actively maintained! Thanks to @askmike and others. Great job.
