### ISSUE TITLE
Video of my GA working with Gekko

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#997]
For peoples interest more than anything:

https://www.youtube.com/watch?v=93OiWRBRTJw

**Comment by askmike** [comment]
If you don't mind I def want to post a link to that here: https://gekko.wizb.it/docs/extending/other_software.html

*(as discussed we might at some point integrate into gekko, but that is not too close imo)*

**Comment by thegamecat** [comment]
Yep ofc.

**Comment by chrisedington** [comment]
Looks cool, would love to play with it.

**Comment by GuyPaddock** [comment]
It's funny. Just this morning I mentioned to my partner on the drive in that I was wondering if it would be possible to setup a "survival of the fittest" or genetic algorithm to work with Gekko.

**Comment by decoye** [comment]
looks interesting, would also love to play with it.

Question of interest, did you calculate on cpu or gpu?
And have you considered the possibiity of the ga to be bankrupt?

**Comment by bsliran** [comment]
I wanna see more! :) 
did you try this one live/paper trading?

**Comment by thegamecat** [comment]
> Question of interest, did you calculate on cpu or gpu?

CPU - it's written in node, I don't think you can run that on a GPU, in any case the speed is 100% dependant on Gekkos backtesting. At the moment I'm running 25 variations per epoch with 8 in parallel at any one time.

> And have you considered the possibiity of the ga to be bankrupt?

Well these are all backtests so if it goes bankrupt it will tell me.

> did you try this one live/paper trading?

No, this is only running backtests

**Comment by dlasher** [comment]
Would be interested in doing some testing as well - anything code-wise you can share?

**Comment by thegamecat** [comment]
At the moment I'm keeping it to myself, but I'm doing some optimizing work with a gekko user as well meaning he sends me strats and I run the GA and give him the results. It's quite interesting as we get to discuss strategies and such like. I could do something similar with you?

**Comment by thegamecat** [comment]
I've written some more detail about the ga here: http://gekkowarez.com/gekko-genetic-algorithm/

**Comment by decoye** [comment]
@thegamecat, would you like to make a test for me on poloniex eth/usdt timeframe 23.05.2017- 23.08.2017?

**Comment by thegamecat** [comment]
sure, you'll need to send me your strat and config for it.
I may not get to do it until the weekend though to be clear!

**Comment by decoye** [comment]
So you still need a strategy to back test?
I have to admit that ive pictured it completely differently in my head. Then never mind.

**Comment by mnoseworthy** [comment]
@decoye You may be thinking ML ? A GA would just vary the Thresholds and Variables ( Mutate ) for an instance, and run a back-test for the instance. Then I assume it would run a number of these instances ( A population ) in parallel and based on the output from the back-test results calculate how well the instance did ( Fitness ). Then any instances that had a fitness under a certain threshold would be removed from the population. This continues until your happy with the results, and you can pick your favorite instance out of the population to actually run against the market.

@bsliran  From what I wrote above, it probably isn't a great idea to run this live because some mutations may preform very badly, especially during initial training life cycles.

**Comment by thegamecat** [comment]
@decoye yes you run a strategy and the GA works out the optimal thresholds for that strategy. 

@mnoseworthy not quite true, you're thinking one dimensionally. I'm running the outputs from an optimal GA output and it's foolproof. It's a question of understanding what will work and what wont, then control that in your strat.

**Comment by dlasher** [comment]
I used to run a couple of dedicated boxes doing ga-bitbo.. was very useful at the time, but those boxes were scrapped, not finding my old configs. I have hardware again, need to get it back up and running. Love the idea of integration with Gekko, well done.

**Comment by decoye** [comment]
@thegamecat, ahh okay i see. I really had something completely different in my head. Saw a bunch of things during my research and evaluation period since you talked about it. Had things like marI/O in my head. And just thought if i need the bot to tell what is the way to the solution of the level the bot does not really learn anything.
Im sure im messing up toppics in my head here about what ga term means and what deep learning does. 

My theory about technical analysis is that it hast to stay for a while and you have to be strong and diciplined about your strategy for it to be profitable once you confirmed it is profitable with a back test.
So im struggeling abit with changing strategy over the time of running the strategy.
But thanks for your time and effort of explaining it to me.

**Comment by decoye** [comment]
Now thinking about it. Yes i was thinking about machine lesrning rather then ga. And now that i have thought about the terms it all makes sense...

**Comment by mnoseworthy** [comment]
@thegamecat Super interesting, looking forward to seeing your implementation if you ever release it, good work.

@decoye I agree 100% with your TA theory. I think the way I'd use this is train a specific indicator to the trend you're usually applying it to by backtesting on trades you've made before with said indicator. And like @thegamecat said, you'd want to start the training from a pre-determined set of values.

**Comment by thegamecat** [comment]
You can download my latest version here:
http://gekkowarez.com/gekko-genetic-algorithm/

**Comment by imkane** [comment]
Hey @thegamecat - thanks for sharing this :)

I'm getting an error at this step though:

```
[gekko]$ node run-ga-parallel.js
/home/gekko/run-ga-parallel.js:206
            "data": {
            ^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```
Any ideas?
